import test from 'node:test';import assert from 'node:assert/strict';import {createHandler} from '../api/ai-chat.js';
const image='data:image/png;base64,aGVsbG8=';
let sequence=0;
async function call(messages,env={GROQ_API_KEY:'test-key'},upstream={ok:true,status:200,data:{choices:[{message:{content:'## Hello\n\n**Readable reply**'}}]}}){let payload,answer;const h=createHandler(async(_url,options)=>{payload=JSON.parse(options.body);return {ok:upstream.ok,status:upstream.status,json:async()=>upstream.data}},env);const res={setHeader(){},end(text){answer=JSON.parse(text)}};await h({method:'POST',headers:{host:'nova.test',origin:'https://nova.test','x-real-ip':'test-'+sequence++},body:{messages}},res);return {status:res.statusCode,...answer,payload}}
test('text sends Markdown instructions and text model',async()=>{const r=await call([{role:'user',text:'Explain WWI'}]);assert.equal(r.status,200);assert.equal(r.payload.model,'openai/gpt-oss-20b');assert.match(r.payload.messages[0].content,/real line breaks/);assert.match(r.text,/Readable reply/)});
test('uploaded images reach the vision model',async()=>{const r=await call([{role:'user',text:'Describe this',image}]);assert.equal(r.status,200);assert.equal(r.payload.model,'qwen/qwen3.8-27b');assert.equal(r.payload.messages[1].content[1].image_url.url,image)});
test('screenshots and upload can be sent together with screen context',async()=>{const r=await call([{role:'user',text:'What is wrong?',image,screenImage:image}]);assert.equal(r.status,200);const content=r.payload.messages[1].content;assert.equal(content.filter(c=>c.type==='image_url').length,2);assert(content.some(c=>c.text?.includes('still image')))});
test('invalid images and excess images never reach provider',async()=>{assert.equal((await call([{role:'user',text:'hi',image:'javascript:evil'}])).status,400);assert.equal((await call(Array.from({length:4},()=>({role:'user',text:'hi',image})))).status,400)});
test('missing key gives an actionable setup error',async()=>{const r=await call([{role:'user',text:'hi'}],{});assert.equal(r.status,503);assert.match(r.error,/GROQ_API_KEY/)});
test('unavailable vision model gives a specific error',async()=>{const r=await call([{role:'user',text:'hi',image}],{GROQ_API_KEY:'test'},{ok:false,status:404,data:{error:{code:'model_not_found'}}});assert.equal(r.status,503);assert.match(r.error,/GROQ_VISION_MODEL/)});
