import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';
import {createPartyAdapter} from '../Public/src/buildnow-party-native.mjs';
function fixture(){const memory={buffer:new ArrayBuffer(65536)},words=new Uint32Array(memory.buffer),bytes=new Uint8Array(memory.buffer),calls=[],freed=[];const put=(p,v)=>words[p>>>2]=v;
 const object=(p,c,n,name,token)=>{put(p,c);put(p+8,1);put(c+8,n);put(c+164,token);bytes.set(Buffer.from(name+'\0'),n);};
 object(2048,10000,50001,'GameLobby',33556569);object(4096,10500,50101,'InputField',33554478);object(6500,11000,50201,'String',0);put(2048+96,4096);
 let connected=true,offline=false,inRoom=false,isParty=false,joinedCode='',inputCode='';
 const string=value=>{put(6500+8,value.length);new Uint16Array(memory.buffer,6512,value.length).set([...value].map(x=>x.charCodeAt(0)));return 6500;};
 const methods={31451:()=>2048,41560:()=>Number(connected),41570:()=>Number(offline),41587:()=>Number(inRoom),31576:()=>Number(isParty),31578:()=>string(joinedCode),31510:()=>{calls.push('leave');inRoom=false;isParty=false;},11650:(receiver,out,start,length,mi)=>{assert.equal(receiver,0);assert.equal(start,0);assert.equal(mi,0);return string(String.fromCharCode(...new Uint16Array(memory.buffer,out,length)));},81217:(input,p)=>{assert.equal(input,4096);inputCode=String.fromCharCode(...new Uint16Array(memory.buffer,p+12,words[(p+8)>>>2]));calls.push(['code',inputCode]);},31509:p=>{assert.equal(p,2048);calls.push(['join',inputCode]);}};
 const adapter=createPartyAdapter({ek:memory,Ck:{get:p=>{assert(methods[p],'unexpected method '+p);return methods[p];}},tk:()=>20000,uk:p=>freed.push(p)});
 return {adapter,calls,freed,put,bytes,join:(code,party=true)=>{inRoom=true;isParty=party;joinedCode=code;},offline:()=>offline=true,disconnect:()=>connected=false};}
test('native party join fills the real code input before normal ConnectToParty and confirms only a matching online party',()=>{const f=fixture();f.adapter.join('ABC123');assert.deepEqual(f.calls,[['code','ABC123'],['join','ABC123']]);assert.deepEqual(f.freed,[20000]);assert.equal(f.adapter.joined('ABC123'),false);f.join('WRONG');assert.equal(f.adapter.joined('ABC123'),false);f.join('ABC123',false);assert.equal(f.adapter.joined('ABC123'),false);f.join('ABC123');assert.equal(f.adapter.joined('ABC123'),true);f.offline();assert.equal(f.adapter.joined('ABC123'),false);});
test('native join respects actual component type, connection and pending-join gates',()=>{for(const invalidate of [f=>f.put(10500+164,0),f=>f.put(10000+164,0),f=>f.offline(),f=>f.disconnect(),f=>f.bytes[2048+265]=1]){const f=fixture();invalidate(f);assert.throws(()=>f.adapter.join('ABC123'));assert.equal(f.calls.length,0);}const f=fixture();for(const code of ['','a b','<script>','a'.repeat(33)])assert.throws(()=>f.adapter.join(code));assert.equal(f.calls.length,0);});
test('leaving an existing room delegates to the game normal party leave path',()=>{const f=fixture();f.join('OTHER');assert.equal(f.adapter.inRoom(),true);f.adapter.leave();assert.equal(f.adapter.inRoom(),false);assert.deepEqual(f.calls,['leave']);});

test('client join notification waits for native confirmation and retries failed acknowledgements without refiring the join',async()=>{
 const source=readFileSync(new URL('../Public/src/buildnow-party-client.js',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'').replace(/export /g,'');let now=1000,tick,joined=false,attempts=0,joinCalls=0,ackCalls=0;
 const data={id:'invite',code:'ABC123',nonce:'nonce',uid:'member',expiresAt:999999},storage=new Map([['nova_buildnow_party_join_v1',JSON.stringify(data)]]),nodes=[];
 const element=()=>({hidden:false,style:{},append(){},textContent:''});
 const context=vm.createContext({auth:{currentUser:{uid:'member'},authStateReady:async()=>{}},window:{addEventListener(){}},document:{body:{append:n=>nodes.push(n)},createElement:element},sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},Date:{now:()=>now},setInterval:fn=>{tick=fn;return 1;},clearInterval(){},setTimeout(){},control:async action=>{assert.equal(action,'buildNowInviteJoined');ackCalls++;if(attempts++<1)throw Error('connection unavailable');return {ok:true};}});
 context.runtime={adapter:()=>({ready:()=>true,inRoom:()=>false,join:()=>joinCalls++,joined:()=>joined})};vm.runInContext(source+'\nstartPartyJoin(runtime);',context);await new Promise(r=>setImmediate(r));assert.equal(joinCalls,1);assert.equal(ackCalls,0);
 joined=true;await tick();assert.equal(ackCalls,1);assert(storage.has('nova_buildnow_party_join_v1'));now+=3000;await tick();assert.equal(ackCalls,2);assert.equal(joinCalls,1);assert.equal(storage.has('nova_buildnow_party_join_v1'),false);
});
