import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {buildNowTools} from '../server/buildnow-tools.mjs';
test('BuildNow shader declarations follow required GLSL precision statements',()=>{const window={};vm.runInNewContext(readFileSync(new URL('../server/buildnow-visual.js',import.meta.url),'utf8'),{window});const source='#version 300 es\nprecision highp float;\nprecision highp int;\nout highp vec4 result;\nvoid main(){result=vec4(1.0);}',patched=window.NovaLOLVisual.patchShader(source,false);assert(patched.indexOf('uniform bool novaEnabled')>patched.indexOf('precision highp int;'));assert(patched.includes('result=vec4(novaColor,1.0)'))});
test('BuildNow bundle uses strict movement filtering and the correct game canvas',async()=>{const code=await buildNowTools();new vm.Script(code);assert(code.includes('UNIFORM_BLOCK_BINDING'));assert(code.includes('getBufferSubData'));assert(code.includes('model?.rows===15&&moving'));assert(code.includes("document.querySelector('#unity-canvas')"));assert(code.includes('movingOnly=true'));assert(!code.includes('get("moving").checked'));});

function tracking(){const window={};vm.runInNewContext(readFileSync(new URL('../server/buildnow-visual.js',import.meta.url),'utf8'),{window});return window.NovaLOLVisual}
const point=(x,y=0)=>({x,y,distance:x*x+y*y,width:30,height:60});
test('tracking holds a nearby moving target instead of switching to a closer shape',()=>{const lock=tracking().createTargetLock();assert.equal(lock.update([point(40)],256,256,0).x,40);const held=lock.update([point(44),point(5)],256,256,16);assert(held.x>40);assert(held.x<44);assert.equal(lock.update([],256,256,32),null);assert.equal(lock.update([point(5)],256,256,48).x,5)});
test('tracking drops missing and out-of-range targets and resets after focus loss',()=>{const lock=tracking().createTargetLock();lock.update([point(40)],256,256,0);assert.equal(lock.update([point(200)],256,256,16),null);lock.update([point(40)],256,256,32);lock.reset();assert.equal(lock.update([point(5),point(40)],256,256,48).x,5)});
test('aim correction is consistent across frame rates and remains bounded',()=>{const {aimDelta}=tracking();const full=aimDelta(point(20),.4,16).dx,half=aimDelta(point(20),.4,8).dx;assert(Math.abs((1-half/20)**2-(1-full/20))<1e-9);assert.equal(aimDelta(point(.5),.4,16).dx,0);assert(aimDelta(point(1000),1,1000).dx<=36)});
