import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const rules=JSON.parse(fs.readFileSync(new URL('../firebase-voice.rules.json',import.meta.url))).rules.novaChatV2;
const node=value=>({val:()=>value??null,exists:()=>value!==undefined&&value!==null,child:path=>node(path.split('/').reduce((v,k)=>v?.[k],value))});
function evaluate(expression,{uid='alice',role='member',channel='general',clock={},data=null,next={author:'alice',text:'hello'},now=10000,extra={}}={}){const root=node({novaAccounts:{alice:{name:'Alice'}},novaChatV2:{roles:{alice:role},sendClock:{alice:clock},friends:{alice:{bob:true},bob:{alice:true}}}});const env={root,auth:{uid,token:{firebase:{sign_in_provider:'password'}}},data:node(data),newData:node(next),now,$message:'m1',$channel:channel,$uid:'alice',$a:'alice',$b:'bob',...extra};return Function(...Object.keys(env),'return ('+expression+')')(...Object.values(env))}
const write=rules.channels.$channel.messages.$message['.write'];
test('new messages require their own matching send reservation',()=>{assert.equal(evaluate(write),false);assert.equal(evaluate(write,{clock:{at:9900,key:'m1',path:'channels/general/messages'}}),true);assert.equal(evaluate(write,{clock:{at:9900,key:'m2',path:'channels/general/messages'}}),false);assert.equal(evaluate(write,{clock:{at:9900,key:'m1',path:'channels/updates/messages'}}),false)});
test('send reservations have a server-enforced cooldown and cannot be deleted',()=>{const rule=rules.sendClock.$uid['.write'];assert.equal(evaluate(rule,{data:{at:9500},next:{at:10000}}),false);assert.equal(evaluate(rule,{data:{at:8000},next:{at:10000}}),true);assert.equal(evaluate(rule,{next:null}),false)});
test('staff lounge is private and reports cannot become public messages',()=>{const read=rules.channels.$channel.messages['.read'];assert.equal(evaluate(read,{channel:'owner-lounge'}),false);assert.equal(evaluate(read,{channel:'owner-lounge',role:'owner'}),true);assert.equal(evaluate(read,{channel:'report',role:'owner'}),false)});
test('only owner reads the full feedback inbox',()=>{assert.equal(evaluate(rules.feedback['.read']),false);assert.equal(evaluate(rules.feedback['.read'],{role:'admin'}),false);assert.equal(evaluate(rules.feedback['.read'],{role:'owner'}),true);assert.equal(evaluate(rules.feedback.$uid['.read'],{extra:{$uid:'bob'}}),false)});
test('only owner can customize server; preview cosmetics cannot be newly equipped',()=>{assert.equal(evaluate(rules.server['.write']),false);assert.equal(evaluate(rules.server['.write'],{role:'owner'}),true);assert.equal(evaluate(rules.profiles.$uid.effect['.validate'],{data:'old',next:'new'}),false)});
