import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const source=(await readFile(new URL('../Public/src/computer.js',import.meta.url),'utf8')).replace(/^import .*;\r?\n/,'');
function harness({relayConfigured=true}={}){
 const elements=new Map(),listeners=new Map(),intervals=new Map(),timeouts=new Map(),requests=[],packets=[];let next=1,authListener,peer;
 const classes={add(){},remove(){},toggle(){}};
 const get=id=>{if(!elements.has(id))elements.set(id,{hidden:false,textContent:'',classList:classes,replaceChildren(){},attrs:new Map(),setAttribute(k,v){this.attrs.set(k,v)},getAttribute(k){return this.attrs.get(k)},removeAttribute(){},events:new Map(),addEventListener(name,fn){this.events.set(name,fn)},setPointerCapture(){},focus(){},blur(){},videoWidth:1920,videoHeight:1080,getBoundingClientRect:()=>({left:0,top:0,width:1920,height:1080}),getVideoPlaybackQuality:()=>({totalVideoFrames:120})});return elements.get(id)};
 const channel={label:'nova-input',readyState:'open',bufferedAmount:0,send:value=>packets.push(JSON.parse(value)),close(){this.readyState='closed'}};
 class Peer{constructor(config){this.config=config;peer=this;this.connectionState='connected';this.remoteDescription=null}async setRemoteDescription(v){this.remoteDescription=v}async createAnswer(){return{type:'answer',sdp:'test'}}async setLocalDescription(v){this.localDescription=v}async addIceCandidate(){}async getStats(){return new Map([['video',{type:'inbound-rtp',kind:'video',framesPerSecond:58}]])}close(){this.closed=true}}
 const context={console,auth:{onAuthStateChanged:fn=>{authListener=fn}},document:{getElementById:get,hidden:false,body:{classList:classes},addEventListener:(name,fn)=>listeners.set(name,fn)},navigator:{userAgent:'test'},performance:{now:()=>2000},location:{origin:'https://nova.test'},parent:{},matchMedia:()=>({matches:false}),RTCPeerConnection:Peer,MediaStream:class{},setInterval:(fn,delay)=>{const id=next++;intervals.set(id,{fn,delay});return id},clearInterval:id=>intervals.delete(id),setTimeout:(fn,delay)=>{const id=next++;timeouts.set(id,{fn,delay});return id},clearTimeout:id=>timeouts.delete(id),addEventListener:(name,fn)=>listeners.set(name,fn),fetch:async(url,options)=>{if(url.startsWith('/downloads'))return{ok:true,json:async()=>({parts:[]})};const body=JSON.parse(options.body);requests.push(body);const data=body.action==='list'?{devices:[]}:body.action==='connect'?{session:'s'}:body.action==='poll'?{offset:1,status:'active',signals:[{type:'offer',sdp:'test'}],iceServers:[],relayConfigured}:{};return{ok:true,json:async()=>data}}};
 vm.runInNewContext(source+'\nglobalThis.testViewer={connectDevice,stop,send};',context);
 return {context,get,listeners,intervals,timeouts,requests,packets,channel,peer:()=>peer,login:async()=>{authListener({uid:'u',getIdToken:async()=> 'token'});await new Promise(resolve=>setImmediate(resolve))}};
}
test('remote viewer suspends the list, uses low delay, reports actual FPS and disconnects cleanly',async()=>{
 const h=harness();await h.login();assert.equal(h.intervals.size,1);await h.context.testViewer.connectDevice({id:'pc',name:'PC'});assert.equal(h.intervals.size,0);assert.ok([...h.timeouts.values()].some(t=>t.delay===8000));const peer=h.peer(),receiver={jitterBufferTarget:100};peer.ondatachannel({channel:h.channel});peer.ontrack({receiver,streams:[{}],track:{}});assert.equal(receiver.jitterBufferTarget,0);assert.equal(h.get('waiting').hidden,true);await [...h.intervals.values()][0].fn();assert.equal(h.get('stream-stats').textContent,'1920 × 1080 · 58 FPS');h.get('desktop').onpointermove({clientX:50,clientY:50});assert.ok(h.timeouts.size);h.context.testViewer.stop();await new Promise(resolve=>setImmediate(resolve));assert.ok(h.requests.some(r=>r.action==='disconnect'&&r.session==='s'));assert.ok(h.packets.some(p=>p.type==='release'));assert.equal(peer.closed,true);assert.equal(h.get('session').hidden,true);assert.equal(h.get('screen').srcObject,null);assert.equal(h.timeouts.size,0);assert.equal([...h.intervals.values()][0].delay,8000);
});
test('input congestion drops motion while preserving key releases',()=>{const h=harness();h.channel.bufferedAmount=20000;/* channel is assigned only after the peer accepts it */return h.login().then(async()=>{await h.context.testViewer.connectDevice({id:'pc',name:'PC'});h.peer().ondatachannel({channel:h.channel});h.context.testViewer.send({type:'move',x:0,y:0});h.context.testViewer.send({type:'key',code:'KeyA',down:false});assert.equal(h.packets.length,1);assert.equal(h.packets[0].type,'key')})});
test('installation prompt remains user initiated',async()=>{const h=harness();let prompted=false;h.listeners.get('beforeinstallprompt')({preventDefault(){},prompt:async()=>{prompted=true},userChoice:Promise.resolve({outcome:'accepted'})});assert.equal(prompted,false);await h.get('install-viewer').onclick();assert.equal(prompted,true)});

test('click locks the mouse, sends relative movement, and Escape releases held input',async()=>{
 const h=harness();await h.login();await h.context.testViewer.connectDevice({id:'pc',name:'PC'});h.peer().ondatachannel({channel:h.channel});const desktop=h.get('desktop');let locks=0;
 desktop.requestPointerLock=()=>{locks++;h.context.document.pointerLockElement=desktop;h.listeners.get('pointerlockchange')();return Promise.resolve()};h.context.document.exitPointerLock=()=>{h.context.document.pointerLockElement=null;h.listeners.get('pointerlockchange')()};
 desktop.onpointerdown({button:0,pointerId:1,clientX:50,clientY:50,preventDefault(){}});desktop.onpointerup({button:0,clientX:50,clientY:50,preventDefault(){}});desktop.onclick();assert.equal(locks,1);assert.deepEqual(h.packets.filter(p=>p.type==='button').map(p=>p.down),[true,false]);
 desktop.events.get('mousemove')({movementX:12,movementY:-4});const movement=[...h.timeouts.values()].find(t=>t.delay===8);movement.fn();assert.ok(h.packets.some(p=>p.type==='relative'&&p.dx===12&&p.dy===-4));desktop.onclick();assert.equal(locks,1);
 desktop.onkeydown({key:'Escape'});assert.equal(h.context.document.pointerLockElement,null);assert.equal(h.packets.at(-1).type,'release');desktop.onclick();assert.equal(locks,2);
});
test('a rejected mouse lock can be retried on a later click',async()=>{const h=harness();await h.login();await h.context.testViewer.connectDevice({id:'pc',name:'PC'});h.peer().ondatachannel({channel:h.channel});const desktop=h.get('desktop');let attempts=0;desktop.requestPointerLock=()=>{attempts++;return attempts===1?Promise.reject(Error('Denied')):Promise.resolve()};desktop.onclick();await new Promise(resolve=>setImmediate(resolve));assert.match(desktop.title,/retry/);desktop.onclick();assert.equal(attempts,2)});

test('FPS selector requests host changes and keeps actual FPS separate from the target',async()=>{const h=harness();await h.login();await h.context.testViewer.connectDevice({id:'pc',name:'PC'});h.peer().ondatachannel({channel:h.channel});h.get('fps-menu').hidden=true;h.get('stream-stats').onclick();assert.equal(h.get('fps-menu').hidden,false);h.get('fps-240').onclick();assert.ok(h.packets.some(p=>p.type==='stream-settings'&&p.fps===240));assert.equal(h.get('fps-120').disabled,true);assert.equal(h.get('fps-240').getAttribute('aria-checked'),'false');h.channel.onmessage({data:JSON.stringify({type:'stream-settings',fps:240,ok:true,captureFps:120})});assert.match(h.get('stream-stats').title,/Target: 240/);assert.equal(h.get('fps-240').getAttribute('aria-checked'),'true');assert.equal(h.get('fps-120').disabled,false);h.peer().ontrack({receiver:{},streams:[{}],track:{}});await [...h.intervals.values()][0].fn();assert.equal(h.get('stream-stats').textContent,'1920 × 1080 · 58 FPS');h.get('fps-120').onclick();h.channel.onmessage({data:JSON.stringify({type:'stream-settings',fps:120,ok:false})});assert.match(h.get('stream-stats').title,/Target: 240/);assert.match(h.get('fps-status').textContent,/current stream continues/)});

test('a brief network disconnect retains the session and cancels recovery on reconnect',async()=>{const h=harness();await h.login();await h.context.testViewer.connectDevice({id:'pc',name:'PC'});const peer=h.peer();peer.connectionState='disconnected';peer.onconnectionstatechange();assert.equal(peer.closed,undefined);assert.equal(h.get('session').hidden,false);assert.match(h.get('notice').textContent,/recovers/);assert.ok([...h.timeouts.values()].some(t=>t.delay===15000));peer.connectionState='connected';peer.onconnectionstatechange();assert.ok(![...h.timeouts.values()].some(t=>t.delay===15000));peer.connectionState='disconnected';peer.onconnectionstatechange();assert.ok([...h.timeouts.values()].some(t=>t.delay===15000));});
test('a sustained disconnect releases the session and preserves the network explanation',async()=>{const h=harness();await h.login();await h.context.testViewer.connectDevice({id:'pc',name:'PC'});const peer=h.peer();peer.connectionState='disconnected';peer.onconnectionstatechange();[...h.timeouts.values()].find(t=>t.delay===15000).fn();await new Promise(resolve=>setImmediate(resolve));assert.equal(peer.closed,true);assert.equal(h.get('session').hidden,true);assert.match(h.get('notice').textContent,/relay/);assert.ok(h.requests.some(r=>r.action==='disconnect'));});
test('a temporarily failed poll retries without tearing down the viewer',async()=>{const h=harness();await h.login();await h.context.testViewer.connectDevice({id:'pc',name:'PC'});const old=h.context.fetch;h.context.fetch=async(url,options)=>{if(JSON.parse(options?.body||'{}').action==='poll')throw Error('Temporary network failure');return old(url,options)};await [...h.timeouts.values()].find(t=>t.delay===8000).fn();assert.equal(h.peer().closed,undefined);assert.equal(h.get('session').hidden,false);assert.ok([...h.timeouts.values()].some(t=>t.delay===2000));});

test('connection timeout explains a missing relay without silently returning to the device list',async()=>{const h=harness({relayConfigured:false});await h.login();await h.context.testViewer.connectDevice({id:'pc',name:'PC'});h.peer().connectionState='connecting';[...h.timeouts.values()].find(t=>t.delay===45000).fn();await new Promise(resolve=>setImmediate(resolve));assert.equal(h.peer().closed,true);assert.match(h.get('notice').textContent,/No TURN relay is configured/);assert.equal(h.get('session').hidden,true)});

test('restricted Wi-Fi choice reaches the server and forces relay candidates',async()=>{const h=harness();await h.login();h.get('network-mode').value='relay';const old=h.context.fetch;h.context.fetch=async(url,options)=>{const response=await old(url,options);if(JSON.parse(options?.body||'{}').action==='poll'){const data=await response.json();return {...response,json:async()=>({...data,iceTransportPolicy:'relay'})}}return response};await h.context.testViewer.connectDevice({id:'pc',name:'PC'});assert.equal(h.requests.find(r=>r.action==='connect').networkMode,'relay');assert.equal(h.peer().config.iceTransportPolicy,'relay')});
