import {patchProxyWorklets} from '../scripts/patch-proxy-worklets.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {patchProxyXHR} from '../scripts/patch-proxy-xhr.mjs';
const root=new URL('../Public/',import.meta.url);
test('catalog game IDs and local files identify distinct entries',async()=>{const games=JSON.parse(await readFile(new URL('library-games.json',root),'utf8'));assert.equal(new Set(games.map(g=>String(g.id))).size,games.length)});
test('proxy sync XHR uses the actual flagEnabled client API and guards source changes',()=>{const s='if(!e.getFlag("syncxhr"))return;';assert.equal(patchProxyXHR(s),'if(!e.flagEnabled("syncxhr"))return;');assert.throws(()=>patchProxyXHR('other'),/implementation changed/)});
async function sdk(file,path='/content/games/375-f.html',storage=new Map()){const window={},context={window,location:{pathname:path,href:'https://nova-content.invalid'+path},navigator:{language:'en-US'},document:{hidden:false,addEventListener(){},removeEventListener(){}},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},URL,Date};vm.runInNewContext(await readFile(new URL('content/runtime/'+file,root),'utf8'),context);return {window,storage}}
test('Yandex standalone games preserve local saves separately for each title',async()=>{const a=await sdk('nova-yandex.js'),api=await a.window.YaGames.init(),player=await api.getPlayer();await player.setData({level:3});await player.setStats({wins:1});await player.incrementStats({wins:2});assert.equal((await player.getData()).level,3);assert.equal((await player.getStats()).wins,3);const b=await sdk('nova-yandex.js','/content/games/376.html',a.storage);assert.equal((await (await b.window.YaGames.init()).getPlayer()).getMode(),'lite');assert.equal(Object.keys(await (await(await b.window.YaGames.init()).getPlayer()).getData()).length,0)});
test('standalone host adapters do not grant rewards for unavailable ads or enable purchases',async()=>{const y=await sdk('nova-yandex.js'),api=await y.window.YaGames.init();let rewarded=false,error=false;api.adv.showRewardedVideo({callbacks:{onRewarded(){rewarded=true},onError(){error=true}}});assert.equal(rewarded,false);assert.equal(error,true);await assert.rejects(api.getPayments(),/unavailable/);const p=await sdk('nova-poki.js');assert.equal(await p.window.PokiSDK.rewardedBreak(),false);const t=await sdk('nova-ytgame.js');assert.equal(await t.window.ytgame.ads.requestAd(),'AD_NOT_SHOWN')});

test('AudioWorklet bytes bypass DOM proxy rewriting while regular scripts still rewrite',async()=>{const old='i=await (0,A.B)(e,t,u,y),(0,a.tW)(u,b)';const patched=patchProxyWorklets(old);for(const destination of ['audioworklet','script']){let calls=0;const body='registerProcessor("processor", Processor)';const headers=new Map([['content-encoding','gzip'],['content-length','123']]);const context={e:{},t:{},u:{destination,url:new URL('https://game.example/processor.js')},y:{body},A:{B:async()=>{calls++;return 'rewritten'}},a:{tW(){}},b:headers};const value=await vm.runInNewContext('(async()=>{let i;'+patched+';return i})()',context);assert.equal(value,destination==='audioworklet'?body:'rewritten');assert.equal(calls,destination==='audioworklet'?0:1);assert.equal(headers.has('content-encoding'),destination!=='audioworklet')}assert.throws(()=>patchProxyWorklets('changed'),/rewriter changed/)});
