import test from 'node:test';import assert from 'node:assert/strict';import {leaderboard,leaderboardGames,awardGameRoles} from '../server/leaderboard.mjs';
function store(data={}){const get=path=>path.split('/').reduce((v,k)=>v?.[k],data)??null;const set=(path,value)=>{const keys=path.split('/');let p=data;for(const k of keys.slice(0,-1))p=p[k]??={};p[keys.at(-1)]=structuredClone(value)};return {get,db:{ref:path=>({get:async()=>({val:()=>structuredClone(get(path))}),transaction:async fn=>{set(path,fn(structuredClone(get(path))));return{committed:true}}})}}}
test('all Nova accounts are ranked and paginated without exposing private account fields',async()=>{const accounts=Object.fromEntries(Array.from({length:105},(_,i)=>['u'+i,{name:'Player '+String(i).padStart(3,'0'),email:'secret',password:'secret',photo:'javascript:alert(1)'}]));const s=store({novaAccounts:accounts,novaControl:{progress:{u4:{activeSeconds:100}}}});const first=await leaderboard(s.db,'u0','leaderboard',{});const second=await leaderboard(s.db,'u0','leaderboard',{offset:first.next});assert.equal(first.total,105);assert.equal(first.players.length,80);assert.equal(second.players.length,25);assert.equal(second.next,null);assert.equal(first.players[0].uid,'u4');assert.equal(first.players[0].seconds,100);assert.equal(new Set([...first.players,...second.players].map(p=>p.uid)).size,105);assert.ok(first.players.every(p=>!('email'in p)&&!('password'in p)&&p.photo===''))});
test('per-game rankings are separate, empty games stay empty, and search preserves global rank',async()=>{const games=await leaderboardGames(),a=games[0].key,b=games[1].key;const s=store({novaAccounts:{a:{name:'Alpha'},b:{name:'Beta'},c:{name:'Gamma'}},novaControl:{leaderboardTime:{a:{seconds:500,gameSeconds:{[a]:10}},b:{seconds:300,gameSeconds:{[a]:70}}}}});const r=await leaderboard(s.db,'a','leaderboard',{game:a});assert.equal(r.players[0].uid,'b');assert.equal(r.players.length,2);assert.equal((await leaderboard(s.db,'a','leaderboard',{game:b})).total,0);const search=await leaderboard(s.db,'a','leaderboard',{search:'beta'});assert.equal(search.players[0].rank,2);await assert.rejects(()=>leaderboard(s.db,'a','leaderboard',{game:'bad'}))});
test('activity is server timed, caps gaps, separates games and does not double-count concurrent tabs',async()=>{const games=await leaderboardGames(),game=games[0].key;const s=store({novaControl:{progress:{u:{activeSeconds:90}}}});await leaderboard(s.db,'u','leaderboardPulse',{active:true,game},100000);await leaderboard(s.db,'u','leaderboardPulse',{active:true,game},115000);await leaderboard(s.db,'u','leaderboardPulse',{active:true,game},115000);assert.equal(s.get('novaControl/leaderboardTime/u/seconds'),105);assert.equal(s.get('novaControl/leaderboardTime/u/gameSeconds/'+game),15);await leaderboard(s.db,'u','leaderboardPulse',{active:true,game},110000);assert.equal(s.get('novaControl/leaderboardTime/u/at'),115000);await leaderboard(s.db,'u','leaderboardPulse',{active:true,game},200000);assert.equal(s.get('novaControl/leaderboardTime/u/seconds'),105);await leaderboard(s.db,'u','leaderboardPulse',{active:false,game},215000);assert.equal(s.get('novaControl/leaderboardTime/u/seconds'),105)});
test('profile view exposes only public fields',async()=>{const s=store({novaAccounts:{u:{name:'Player',email:'secret',password:'secret'}},novaChatV2:{profiles:{u:{bio:'Hello',effect:'spark',private:'secret'}},roles:{u:'owner'}}});const r=await leaderboard(s.db,'x','leaderboardProfile',{uid:'u'});assert.equal(r.profile.bio,'Hello');assert.equal(r.profile.role,'owner');assert.equal(r.profile.email,undefined);assert.equal(r.profile.password,undefined);assert.equal(r.profile.private,undefined);await assert.rejects(()=>leaderboard(s.db,'x','leaderboardProfile',{uid:''}))});

test('game rank roles track only positive verified standings, top three and deterministic ties',()=>{const games=[{key:'game:x',name:'Game X',art:'cover.png'}],players=[{uid:'a',name:'Alpha',gameSeconds:{'game:x':20}},{uid:'b',name:'Beta',gameSeconds:{'game:x':40}},{uid:'c',name:'Gamma',gameSeconds:{'game:x':20}},{uid:'d',name:'Delta',gameSeconds:{'game:x':10}},{uid:'e',name:'Empty',gameSeconds:{'game:x':0,'bad':900}}];awardGameRoles(players,games);assert.equal(players[1].gameRoles[0].rank,1);assert.equal(players[0].gameRoles[0].rank,2);assert.equal(players[2].gameRoles[0].rank,3);assert.deepEqual(players[3].gameRoles,[]);assert.deepEqual(players[4].gameRoles,[]);players[3].gameSeconds['game:x']=80;awardGameRoles(players,games);assert.equal(players[3].gameRoles[0].rank,1);assert.deepEqual(players[2].gameRoles,[]);assert.equal(players[0].gameRoles[0].art,'cover.png')});


test('app playtime is tracked separately and can select an app top player',async()=>{const games=await leaderboardGames(),app=games.find(g=>g.key.startsWith('app:'));assert.ok(app);const s=store({novaAccounts:{u:{name:'User'}},novaControl:{progress:{u:{activeSeconds:0}}}});await leaderboard(s.db,'u','leaderboardPulse',{active:true,game:app.key},100000);await leaderboard(s.db,'u','leaderboardPulse',{active:true,game:app.key},115000);assert.equal(s.get('novaControl/leaderboardTime/u/gameSeconds/'+app.key),15);const result=await leaderboard(s.db,'u','leaderboard',{game:app.key},115000);assert.equal(result.players[0].uid,'u');assert.equal(result.players[0].seconds,15);const other=games.find(g=>g.key.startsWith('game:'));assert.equal((await leaderboard(s.db,'u','leaderboard',{game:other.key},115000)).total,0)});
