import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {webcrypto} from 'node:crypto';
const source=(await readFile(new URL('../Public/src/login-handoff.js',import.meta.url),'utf8')).replace(/^import .*;\n/,'').replaceAll('export ','');
const primary='https://novaoffical.vercel.app',target='https://new-nova.example';
function harness({path='/home.html',origin=target,search='',currentUser=null,trusted=[primary,target],unreachable=false}={}){
 const store=()=>{const data=new Map();return {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k)}};
 const localStorage=store(),sessionStorage=store(),requests=[],navigations=[],signins=[],auth={currentUser};
 const location={origin,pathname:path,search,hash:'',replace:url=>{navigations.push(url);if(path==='/home.html')throw Error('navigation simulated')}};
 const window={};window.top=window;
 const context=vm.createContext({window,location,history:{replaceState:()=>location.hash=''},sessionStorage,localStorage,crypto:webcrypto,TextEncoder,URL,URLSearchParams,AbortSignal,Date,Uint8Array,btoa:s=>Buffer.from(s,'binary').toString('base64'),browserLocalPersistence:'local',setPersistence:async()=>{},signInWithCustomToken:async(_auth,token)=>signins.push(token),fetch:async(url,options={})=>{requests.push({url:String(url),options});if(unreachable&&String(url).startsWith(primary))throw Error('offline');return {ok:true,json:async()=>options.method==='POST'?JSON.parse(options.body).action==='issue'?{code:'a'.repeat(64)}:{token:'same-account-token'}:{primary,trusted}}}});
 new vm.Script(source+'\nglobalThis.api={automaticLogin,bridge,completeLogin};').runInContext(context);
 return {...context,auth,requests,navigations,signins,api:context.api};
}
test('approved new home probes original and starts a secret-bound request without putting verifier in URL',async()=>{const h=harness();await h.api.automaticLogin(h.auth);assert.equal(h.navigations.length,1);const url=new URL(h.navigations[0]),pending=JSON.parse(h.sessionStorage.getItem('nova-login-handoff'));assert.equal(url.origin,primary);assert.equal(url.pathname,'/login-bridge.html');assert.equal(new URLSearchParams(url.hash.slice(1)).get('target'),target);assert.equal(url.href.includes(pending.verifier),false);assert.equal(h.requests.length,2)});
test('existing accounts, add-account, explicit logout, unapproved copies, and offline originals skip redirects',async()=>{for(const options of [{currentUser:{uid:'existing'}},{search:'?add=1'},{search:'?logout=1'},{trusted:[primary]},{unreachable:true}]){const h=harness(options);await h.api.automaticLogin(h.auth);assert.equal(h.navigations.length,0)}const out=harness({search:'?logout=1'});await out.api.automaticLogin(out.auth);out.location.search='';await out.api.automaticLogin(out.auth);assert.equal(out.navigations.length,0)});
test('original signed-in bridge issues a code using its own token; logged-out bridge returns normal login fallback',async()=>{for(const user of [null,{uid:'same',getIdToken:async()=>'existing-id-token'}]){const h=harness({path:'/login-bridge.html',origin:primary,currentUser:user});h.location.hash='#'+new URLSearchParams({state:'s'.repeat(43),challenge:'c'.repeat(43),target});await h.api.bridge(h.auth);const url=new URL(h.navigations[0]),result=new URLSearchParams(url.hash.slice(1));assert.equal(url.origin,target);assert.equal(url.pathname,'/login-callback.html');assert.equal(url.href.includes('existing-id-token'),false);assert.equal(result.has(user?'code':'error'),true);assert.equal(h.location.hash,'')}});
test('callback checks state, redeems with the tab secret and signs into the same account',async()=>{const h=harness({path:'/login-callback.html'});h.sessionStorage.setItem('nova-login-handoff',JSON.stringify({state:'s'.repeat(43),verifier:'v'.repeat(43),primary,expiresAt:Date.now()+90000,returnPath:'/home.html'}));h.location.hash='#'+new URLSearchParams({state:'s'.repeat(43),code:'a'.repeat(64)});await h.api.completeLogin(h.auth);assert.deepEqual(h.signins,['same-account-token']);assert.deepEqual(h.navigations,['/home.html']);assert.equal(h.sessionStorage.getItem('nova-login-handoff'),null);assert.equal(h.location.hash,'');const post=h.requests.find(r=>r.options.method==='POST');assert.equal(post.url,primary+'/api/login-handoff');assert.equal(JSON.parse(post.options.body).verifier,'v'.repeat(43))});
test('unrequested callbacks cannot replace an account or redeem credentials',async()=>{const h=harness({path:'/login-callback.html'});h.location.hash='#state=attacker&code='+'a'.repeat(64);await assert.rejects(h.api.completeLogin(h.auth),/expired/);assert.equal(h.signins.length,0);assert.equal(h.requests.length,0)});
