import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {createHandler,configuration,privateRules} from '../api/login-handoff.js';
const primary='https://novaoffical.vercel.app',target='https://new-nova.example';
const verifier='a'.repeat(43),challenge=createHash('sha256').update(verifier).digest('base64url');
function harness(){
 let time=1000,revoked=false,disabled=false,validAfter=0,issued=0,rules={'.read':false,'.write':false,novaAuthHandoffs:{'.read':false,'.write':false,'.indexOn':'expiresAt'}},values=new Map();
 const db={getRulesJSON:async()=>({rules}),ref:path=>({get:async()=>({exists:()=>path.startsWith('novaAccounts/'),val:()=>values.get(path)}),set:async value=>values.set(path,value),transaction:async callback=>{const next=callback(values.get(path));if(next===undefined)return {committed:false};values.set(path,next);return {committed:true,snapshot:{val:()=>next}}}})};
 const auth={verifyIdToken:async(token,checkRevoked)=>{assert.equal(checkRevoked,true);if(token!=='valid'||revoked)throw Error();return {uid:'same-account',firebase:{sign_in_provider:'password'}}},getUser:async uid=>{assert.equal(uid,'same-account');return {disabled,tokensValidAfterTime:new Date(validAfter).toISOString()}},createCustomToken:async uid=>{issued++;return 'custom-'+uid}};
 const handler=createHandler(async()=>({auth,db}),()=>({primary,trusted:[primary,target]}),()=>time);
 async function call(body,origin=primary,method='POST',token='valid'){const headers={};const res={setHeader:(k,v)=>headers[k]=v,end(value){this.body=value?JSON.parse(value):null}};await handler({method,headers:{origin,authorization:'Bearer '+token},body},res);return {...res,headers}}
 return {call,expire:()=>time+=90001,revoke:()=>revoked=true,disable:()=>disabled=true,invalidate:()=>validAfter=time+1,unprotect:()=>rules.novaAuthHandoffs['.read']=true,tokens:()=>issued};
}
test('only exact HTTPS origins are approved; config never exposes secrets',()=>{const config=configuration({NOVA_LOGIN_TRUSTED_ORIGINS:'https://new-nova.example,https://new-nova.example/,http://bad.example,https://new-nova.example/path,*'});assert.deepEqual(config,{primary,trusted:[primary,target]})});
test('an existing login transfers the same UID, once, with a browser-bound verifier',async()=>{const h=harness(),start=await h.call({action:'issue',target,challenge});assert.equal(start.statusCode,200);assert.match(start.body.code,/^[a-f0-9]{64}$/);const requests=await Promise.all([h.call({action:'redeem',code:start.body.code,verifier},target),h.call({action:'redeem',code:start.body.code,verifier},target)]);assert.deepEqual(requests.map(r=>r.statusCode).sort(),[200,401]);assert.equal(h.tokens(),1);assert.equal(requests.find(r=>r.statusCode===200).body.token,'custom-same-account')});
test('wrong verifier and wrong destination cannot consume a legitimate handoff',async()=>{const h=harness(),s=await h.call({action:'issue',target,challenge});assert.equal((await h.call({action:'redeem',code:s.body.code,verifier:'b'.repeat(43)},target)).statusCode,401);assert.equal((await h.call({action:'redeem',code:s.body.code,verifier},primary)).statusCode,401);assert.equal((await h.call({action:'redeem',code:s.body.code,verifier},target)).statusCode,200)});
test('unapproved origins and destinations are rejected without CORS access',async()=>{const h=harness();const r=await h.call({action:'issue',target,challenge},'https://attacker.example');assert.equal(r.statusCode,403);assert.equal(r.headers['Access-Control-Allow-Origin'],undefined);assert.equal((await h.call({action:'issue',target:'https://attacker.example',challenge})).statusCode,400);assert.equal(h.tokens(),0)});
test('expired, revoked, and disabled accounts cannot obtain a login',async()=>{const h=harness(),s=await h.call({action:'issue',target,challenge});h.expire();assert.equal((await h.call({action:'redeem',code:s.body.code,verifier},target)).statusCode,401);h.revoke();assert.equal((await h.call({action:'issue',target,challenge})).statusCode,401);const d=harness(),code=(await d.call({action:'issue',target,challenge})).body.code;d.disable();assert.equal((await d.call({action:'redeem',code,verifier},target)).statusCode,403);assert.equal(d.tokens(),0)});
test('handoff storage must be private including inherited and descendant grants',async()=>{assert.equal(privateRules({'.read':false,'.write':false,novaAuthHandoffs:{'.read':false,'.write':false,child:{'.write':true}}}),false);assert.equal(privateRules({'.read':true,'.write':false,novaAuthHandoffs:{'.read':false,'.write':false}}),false);const h=harness();h.unprotect();assert.equal((await h.call({action:'issue',target,challenge})).statusCode,503)});
test('approved cross-origin redemption has no-store and explicit CORS, never wildcard',async()=>{const h=harness(),r=await h.call({},target,'OPTIONS');assert.equal(r.statusCode,204);assert.equal(r.headers['Access-Control-Allow-Origin'],target);assert.equal(r.headers['Cache-Control'],'no-store');assert.equal((await h.call({},primary,'GET')).body.primary,primary)});

test("published handoff rules are server-only",async()=>{const rules=JSON.parse(await readFile(new URL("../firebase-voice.rules.json",import.meta.url),"utf8")).rules;assert.ok(privateRules(rules))});
test("revoking sessions after issuance also invalidates the pending handoff",async()=>{const h=harness(),code=(await h.call({action:"issue",target,challenge})).body.code;h.invalidate();assert.equal((await h.call({action:"redeem",code,verifier},target)).statusCode,403);assert.equal(h.tokens(),0)});
