import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const source=readFileSync('Public/src/lol-input.js','utf8');
function runtime(){class EventTarget{addEventListener(){}removeEventListener(){}}class Event{constructor(type,options){this.type=type;Object.assign(this,options)}}const window={EventTarget},document={},canvas={getBoundingClientRect:()=>({left:10,top:20,width:800,height:600}),dispatchEvent(){canvas.fallbacks=(canvas.fallbacks||0)+1}};vm.runInNewContext(source,{window,document,MouseEvent:Event,KeyboardEvent:Event});return{api:window.NovaLOLInput,window,document,canvas,EventTarget};}
test('Unity callback bridge delivers key events without bubbling into macro handlers',()=>{const r=runtime(),received=[],JSEvents={};function jsEventHandler(event){JSEvents.currentEventHandler=event;received.push(event);}r.api.capture(r.window,'keydown',jsEventHandler,true);const key={key:'g',code:'KeyG',keyCode:71};assert.equal(r.api.keyboard(r.canvas,'keydown',key),true);assert.equal(received.length,1);assert.equal(received[0].target,r.canvas);assert.equal(received[0].keyCode,71);assert.equal(r.canvas.fallbacks,undefined);});
test('mouse bridge supplies the relative movement and center coordinates Unity reads',()=>{const r=runtime(),received=[],JSEvents={};function jsEventHandler(event){JSEvents.currentEventHandler=event;received.push(event);}r.api.capture(r.document,'mousemove',jsEventHandler,false);r.api.mouse(r.canvas,'mousemove',{dx:10,dy:-4});assert.equal(received[0].movementX,10);assert.equal(received[0].mozMovementX,10);assert.equal(received[0].movementY,-4);assert.equal(received[0].clientX,410);assert.equal(received[0].clientY,320);});
test('ordinary page handlers are not captured, unknown input falls back to dispatch',()=>{const r=runtime();r.api.capture(r.window,'keydown',()=>{},true);assert.equal(r.api.keyboard(r.canvas,'keyup',{key:'g',keyCode:71}),false);assert.equal(r.canvas.fallbacks,1);});
test('removing Unity listeners also removes them from the input bridge',()=>{const r=runtime(),target=new r.EventTarget(),JSEvents={};function jsEventHandler(event){JSEvents.currentEventHandler=event;}target.addEventListener('keydown',jsEventHandler,true);target.removeEventListener('keydown',jsEventHandler,true);r.api.keyboard(r.canvas,'keydown',{key:'g',keyCode:71});assert.equal(r.canvas.fallbacks,1);});

test('macro clicks use zero relative movement',()=>{const r=runtime(),received=[],JSEvents={};function jsEventHandler(event){JSEvents.currentEventHandler=event;received.push(event);}r.api.capture(r.window,'mousedown',jsEventHandler,true);r.api.mouse(r.canvas,'mousedown',{button:0,buttons:1});assert.equal(received[0].movementX,0);assert.equal(received[0].movementY,0);assert.equal(received[0].buttons,1);});
