import test from 'node:test';
import assert from 'node:assert/strict';
import {createMusicHandler} from '../api/music.js';
import {song,playbackPosition} from '../Public/src/music-core.mjs';
const track={id:'abc123',src:'ytm',title:'Night Drive',artist:'Nova',thumb:'https://example.com/cover.jpg',duration:180};
function setup(cold=false){const reads=new Set();let time=1000000;const data={novaAccounts:Object.fromEntries(['host','a','b','c','d','e'].map(uid=>[uid,{name:uid}]))};const read=path=>path.split('/').reduce((p,k)=>p?.[k],data);const write=(path,value)=>{const parts=path.split('/');let p=data;for(const k of parts.slice(0,-1))p=p[k]??={};if(value===null)delete p[parts.at(-1)];else p[parts.at(-1)]=structuredClone(value)};const snap=value=>({val:()=>structuredClone(value??null),exists:()=>value!=null});let unsafe=false;const db={getRulesJSON:async()=>({rules:{'.read':false,'.write':false,novaMusic:{'.read':unsafe,'.write':false}}}),ref:path=>({get:async()=>{reads.add(path);return snap(read(path))},set:async v=>write(path,v),remove:async()=>write(path,null),transaction:async fn=>{if(cold&&(path.startsWith('novaMusic/libraries/')||path.startsWith('novaMusic/parties/'))&&read(path)!=null){if(fn(null)===undefined)return {committed:false};}const next=fn(structuredClone(read(path)??null));if(next===undefined)return {committed:false};write(path,next);return {committed:true,snapshot:snap(next)}}})};const handler=createMusicHandler(async()=>({db,auth:{verifyIdToken:async token=>{if(!data.novaAccounts[token])throw Error();return {uid:token,firebase:{sign_in_provider:'password'}}}}}),()=>time);const call=async(uid,body)=>{const res={setHeader(){},end(v){this.body=JSON.parse(v)}};await handler({method:'POST',headers:{authorization:'Bearer '+uid},body},res);return {status:res.statusCode,...res.body}};return {call,data,advance:n=>time+=n,unsafe:()=>unsafe=true}}
test('private per-account likes are idempotent and removable',async()=>{const h=setup();for(let i=0;i<2;i++)assert.equal((await h.call('host',{action:'like',song:track,liked:true})).status,200);assert.equal((await h.call('host',{action:'library'})).library.liked.length,1);assert.equal((await h.call('a',{action:'library'})).library.liked.length,0);await h.call('host',{action:'like',song:track,liked:false});assert.equal((await h.call('host',{action:'library'})).library.liked.length,0)});
test('provider-prefixed search songs save to likes and playlists without loosening playlist IDs',async()=>{const h=setup(),t={...track,id:'qobuz:30332818',src:undefined,source:'qobuz'};const liked=await h.call('host',{action:'like',song:t,liked:true});assert.equal(liked.status,200);assert.equal(liked.library.liked[0].id,t.id);assert.equal(liked.library.liked[0].src,'qobuz');const created=await h.call('host',{action:'createPlaylist',name:'Search results'}),id=Object.keys(created.library.playlists)[0];const added=await h.call('host',{action:'playlistSong',id,song:t});assert.equal(added.status,200);assert.equal(added.library.playlists[id].songs[0].id,t.id);assert.equal((await h.call('host',{action:'playlistSong',id:'qobuz:30332818',song:t})).status,400);for(const id of ['../bad','qobuz:../bad','qobuz:a:b','https://example.com'])assert.throws(()=>song({id}));});
test('playlist CRUD and pinning stay in owner library',async()=>{const h=setup(),r=await h.call('host',{action:'createPlaylist',name:'Aura'}),id=Object.keys(r.library.playlists)[0];await h.call('host',{action:'playlistSong',id,song:track});await h.call('host',{action:'playlistSong',id,song:track});let pinned=await h.call('host',{action:'pinPlaylist',id,pinned:true});assert.equal(pinned.library.playlists[id].songs.length,1);assert.equal(pinned.library.playlists[id].pinned,true);assert.equal((await h.call('a',{action:'pinPlaylist',id,pinned:true})).status,400);await h.call('host',{action:'renamePlaylist',id,name:'New name'});const removed=await h.call('host',{action:'deletePlaylist',id});assert.deepEqual(removed.library.playlists,{})});
test('party membership is limited to five including host',async()=>{const h=setup(),{code}=await h.call('host',{action:'createParty'});for(const uid of ['a','b','c','d'])assert.equal((await h.call(uid,{action:'joinParty',code})).status,200);assert.equal((await h.call('e',{action:'joinParty',code})).status,400);assert.equal(Object.keys((await h.call('host',{action:'partyStatus',code})).party.members).length,5)});
test('every member adds songs but only host controls or kicks',async()=>{const h=setup(),{code}=await h.call('host',{action:'createParty'});await h.call('a',{action:'joinParty',code});assert.equal((await h.call('a',{action:'addSong',code,song:track})).status,200);assert.equal((await h.call('a',{action:'control',code,control:'play',value:0})).status,400);assert.equal((await h.call('a',{action:'kick',code,uid:'host'})).status,400);let p=await h.call('host',{action:'control',code,control:'play',value:0});assert.equal(p.party.playback.playing,true);h.advance(5000);p=await h.call('host',{action:'control',code,control:'toggle'});assert.equal(p.party.playback.playing,false);assert.equal(p.party.playback.position,5);await h.call('host',{action:'kick',code,uid:'a'});assert.equal((await h.call('a',{action:'partyStatus',code})).status,410);assert.equal((await h.call('a',{action:'joinParty',code})).status,400)});
test('outsiders cannot see the queue or add songs',async()=>{const h=setup(),{code}=await h.call('host',{action:'createParty'});assert.equal((await h.call('a',{action:'partyStatus',code})).status,410);assert.equal((await h.call('a',{action:'addSong',code,song:track})).status,400)});
test('next and previous wrap queue; seeking remains bounded',async()=>{const h=setup(),{code}=await h.call('host',{action:'createParty'});await h.call('host',{action:'addSong',code,song:track});await h.call('host',{action:'addSong',code,song:{...track,id:'xyz'}});await h.call('host',{action:'control',code,control:'play',value:0});let r=await h.call('host',{action:'control',code,control:'previous'});assert.equal(r.party.playback.index,1);r=await h.call('host',{action:'control',code,control:'next'});assert.equal(r.party.playback.index,0);r=await h.call('host',{action:'control',code,control:'seek',value:9999});assert.equal(r.party.playback.position,180)});
test('leaving frees a slot and host leaving ends the party',async()=>{const h=setup(),{code}=await h.call('host',{action:'createParty'});await h.call('a',{action:'joinParty',code});await h.call('a',{action:'leaveParty',code});assert.equal(Object.keys((await h.call('host',{action:'partyStatus',code})).party.members).length,1);await h.call('host',{action:'leaveParty',code});assert.equal((await h.call('a',{action:'joinParty',code})).status,410)});
test('expired hosts end parties and expired guests free capacity',async()=>{const h=setup(),{code}=await h.call('host',{action:'createParty'});await h.call('a',{action:'joinParty',code});h.advance(60000);await h.call('host',{action:'heartbeat',code});h.advance(40000);assert.equal(Object.keys((await h.call('host',{action:'partyStatus',code})).party.members).length,1);h.advance(300001);assert.equal((await h.call('host',{action:'partyStatus',code})).status,410)});
test('a user cannot silently join multiple active parties',async()=>{const h=setup(),one=await h.call('host',{action:'createParty'}),two=await h.call('a',{action:'createParty'});assert.equal((await h.call('host',{action:'joinParty',code:two.code})).status,400);assert.equal((await h.call('host',{action:'createParty'})).code,one.code)});
test('authentication, bans and private database rules are enforced',async()=>{const h=setup();assert.equal((await h.call('invalid',{action:'library'})).status,401);h.data.novaControl={siteBans:{a:true}};assert.equal((await h.call('a',{action:'library'})).status,403);const unsafe=setup();unsafe.unsafe();assert.equal((await unsafe.call('host',{action:'library'})).status,503)});
test('song identity is validated; unsafe art is stripped; paused clocks do not drift',()=>{assert.throws(()=>song({id:'../../bad'}));assert.equal(song({...track,thumb:'javascript:alert(1)'}).thumb,'');assert.equal(playbackPosition({position:20,updatedAt:1000,playing:true},6000),25);assert.equal(playbackPosition({position:20,updatedAt:1000,playing:false},6000),20)});

test('inherited object keys cannot be used as playlist or kick targets',async()=>{const h=setup();assert.equal((await h.call('host',{action:'renamePlaylist',id:'__proto__',name:'bad'})).status,400);const {code}=await h.call('host',{action:'createParty'});assert.equal((await h.call('host',{action:'kick',code,uid:'__proto__'})).status,400)});

test('unchanged parties return a small clock update without downloading queue again',async()=>{const h=setup(),created=await h.call('host',{action:'createParty'});assert.ok(created.version);const same=await h.call('host',{action:'partyStatus',code:created.code,version:created.version});assert.equal(same.unchanged,true);assert.equal(same.party,undefined);await h.call('a',{action:'joinParty',code:created.code});const changed=await h.call('host',{action:'partyStatus',code:created.code,version:created.version});assert.equal(Object.keys(changed.party.members).length,2);assert.notEqual(changed.version,created.version)});

test('cold function caches can update existing playlists and active party queues',async()=>{const h=setup(true),created=await h.call('host',{action:'createPlaylist',name:'Cold cache'}),id=Object.keys(created.library.playlists)[0];assert.equal((await h.call('host',{action:'playlistSong',id,song:track})).status,200);const party=await h.call('host',{action:'createParty'});assert.equal((await h.call('host',{action:'addSong',code:party.code,song:track})).status,200);assert.equal((await h.call('a',{action:'joinParty',code:party.code})).status,200)});
test('song identity agrees when the player omits its source field',()=>{assert.equal(song({id:'track',title:'Example'}).src,'ytm');});

test('new likes append at the bottom and repeated likes do not move existing songs',async()=>{const h=setup();for(const id of ['one','two','three','one'])await h.call('host',{action:'like',song:{...track,id},liked:true});assert.deepEqual((await h.call('host',{action:'library'})).library.liked.map(t=>t.id),['one','two','three'])});
test('reordering persists and cannot change another account or insert unknown songs',async()=>{const h=setup();for(const id of ['one','two','three'])await h.call('host',{action:'like',song:{...track,id},liked:true});assert.equal((await h.call('host',{action:'reorderSong',collection:'liked',songKey:'ytm:three',beforeKey:'ytm:one'})).status,200);assert.deepEqual((await h.call('host',{action:'library'})).library.liked.map(t=>t.id),['three','one','two']);assert.equal((await h.call('host',{action:'reorderSong',collection:'liked',songKey:'ytm:three',beforeKey:null})).status,200);assert.equal((await h.call('a',{action:'reorderSong',collection:'liked',songKey:'ytm:one',beforeKey:null})).status,400);assert.equal((await h.call('host',{action:'reorderSong',collection:'liked',songKey:'unknown',beforeKey:null})).status,400);const created=await h.call('host',{action:'createPlaylist',name:'Ordered'}),id=Object.keys(created.library.playlists)[0];for(const songId of ['one','two'])await h.call('host',{action:'playlistSong',id,song:{...track,id:songId}});assert.equal((await h.call('host',{action:'reorderSong',collection:'playlist',id,songKey:'ytm:two',beforeKey:'ytm:one'})).status,200);assert.deepEqual((await h.call('host',{action:'library'})).library.playlists[id].songs.map(t=>t.id),['two','one']);assert.equal((await h.call('a',{action:'reorderSong',collection:'playlist',id,songKey:'ytm:two',beforeKey:null})).status,400)});

test('cold party transaction retries its empty cache instead of falsely ending a join',async()=>{const h=setup(true),created=await h.call('host',{action:'createParty'});assert.equal((await h.call('a',{action:'joinParty',code:created.code})).status,200);assert.equal((await h.call('host',{action:'heartbeat',code:created.code})).status,200);await h.call('host',{action:'leaveParty',code:created.code});assert.equal((await h.call('b',{action:'joinParty',code:created.code})).status,410);assert.equal(h.data.novaMusic.parties[created.code],undefined)});
test('a brief background pause does not end the host party and resumed heartbeat keeps it alive',async()=>{const h=setup(),created=await h.call('host',{action:'createParty'});h.advance(120000);assert.equal((await h.call('a',{action:'joinParty',code:created.code})).status,200);assert.equal((await h.call('host',{action:'heartbeat',code:created.code})).status,200);h.advance(120000);assert.equal((await h.call('b',{action:'joinParty',code:created.code})).status,200);});

test('friend invitations are private and join without entering a code',async()=>{const h=setup();h.data.novaChatV2={friends:{host:{a:true},a:{host:true}}};const {code}=await h.call('host',{action:'createParty'});const friends=await h.call('host',{action:'partyFriends',code});assert.equal(friends.friends[0].uid,'a');assert.equal((await h.call('host',{action:'invitePartyFriend',code,uid:'a'})).status,200);const invites=await h.call('a',{action:'partyInvites'});assert.equal(invites.invites.length,1);const id=invites.invites[0].id;assert.equal((await h.call('b',{action:'partyInvites'})).invites.length,0);assert.equal((await h.call('b',{action:'acceptPartyInvite',id})).status,410);const joined=await h.call('a',{action:'acceptPartyInvite',id});assert.equal(joined.status,200);assert.equal(joined.code,code);assert.ok(joined.party.members.a);assert.equal((await h.call('a',{action:'partyInvites'})).invites.length,0);assert.equal((await h.call('host',{action:'invitePartyFriend',code,uid:'b'})).status,403)});
test('expired invites and outsiders cannot join or send invites',async()=>{const h=setup();h.data.novaChatV2={friends:{host:{a:true},a:{host:true}}};const {code}=await h.call('host',{action:'createParty'});assert.equal((await h.call('b',{action:'invitePartyFriend',code,uid:'a'})).status,403);await h.call('host',{action:'invitePartyFriend',code,uid:'a'});const id=(await h.call('a',{action:'partyInvites'})).invites[0].id;h.advance(600001);assert.equal((await h.call('a',{action:'acceptPartyInvite',id})).status,410)});
