import test from 'node:test';import assert from 'node:assert/strict';import {createHandler} from '../api/owner-control.js';
function setup(){const data={novaAccounts:{owner:{name:'Owner'},member:{name:'Member'}},novaChatV2:{roles:{owner:'owner',member:'member'}}};let user='owner';const get=p=>p.split('/').reduce((v,k)=>v?.[k],data)??null;const set=(p,v)=>{let n=data;const keys=p.split('/');for(const k of keys.slice(0,-1))n=n[k]??={};if(v===null)delete n[keys.at(-1)];else n[keys.at(-1)]=structuredClone(v)};const snap=v=>({val:()=>structuredClone(v),exists:()=>v!==null});const db={ref(p){return {get:async()=>snap(get(p)),set:async v=>set(p,v),remove:async()=>set(p,null),update:async v=>set(p,{...get(p),...v}),push:async v=>set(p+'/id'+Math.random().toString().slice(2),v),transaction:async fn=>{const next=fn(structuredClone(get(p)));if(next===undefined)return {committed:false,snapshot:snap(get(p))};set(p,next);return {committed:true,snapshot:snap(next)}}}}};const handler=createHandler(async()=>({db,auth:{verifyIdToken:async token=>{if(token==='invalid')throw Error();return {uid:user,firebase:{sign_in_provider:'password'}}}}}));return {data,get,set,as:u=>user=u,async call(action,body={},token='valid'){let value;const res={setHeader(){},end(v){value=JSON.parse(v)}};await handler({method:'POST',headers:{authorization:'Bearer '+token},body:{action,...body}},res);return {status:res.statusCode,...value}}}}
test('nonowners cannot read dashboard or grant themselves rewards',async()=>{const s=setup();s.as('member');assert.equal((await s.call('dashboard')).status,403);assert.equal((await s.call('user',{uid:'member',kind:'reward',coins:100})).status,403);assert.equal(s.get('novaControl/progress/member'),null)});
test('invalid authentication rejected',async()=>{const s=setup();assert.equal((await s.call('status',{},'invalid')).status,401)});
test('codes redeem once and keep grants atomic',async()=>{const s=setup();assert.equal((await s.call('code',{code:'NOVA-TEST',coins:50,xp:500,levels:1,multiplier:2})).status,200);s.as('member');const first=await s.call('redeem',{code:'nova-test'});assert.equal(first.status,200);assert.equal(first.progress.coins,50);assert.equal((await s.call('redeem',{code:'NOVA-TEST'})).status,400);assert.equal(s.get('novaControl/progress/member').coins,50)});
test('chat bans are separate from Nova bans and appeals restore correct scope',async()=>{const s=setup();await s.call('user',{uid:'member',kind:'chatBan',value:true});assert.equal(s.get('novaControl/siteBans/member'),null);s.as('member');assert.equal((await s.call('status')).ban,null);await s.call('appeal',{scope:'chat',reason:'Please review my chat suspension.'});s.as('owner');await s.call('appealReview',{uid:'member',approve:true});assert.equal(s.get('novaChatV2/bans/member'),null);await s.call('user',{uid:'member',kind:'siteBan',value:true});s.as('member');assert.equal((await s.call('pulse')).status,403);assert.equal((await s.call('appeal',{reason:'Please review my account suspension.'})).status,200)});
test('owner accounts cannot be demoted or banned',async()=>{const s=setup();assert.equal((await s.call('user',{uid:'owner',kind:'role',value:'member'})).status,400);assert.equal((await s.call('user',{uid:'owner',kind:'siteBan',value:true})).status,400)});
test('event multipliers capped and challenges reset through a version',async()=>{const s=setup();assert.equal((await s.call('event',{xpMultiplier:51,coinMultiplier:1,minutes:60})).status,400);assert.equal((await s.call('event',{xpMultiplier:50,coinMultiplier:2,minutes:60})).status,200);await s.call('resetChallenges');assert.equal(s.get('novaControl/events/challengeVersion'),1)});
test('pulse creates four challenges and does not award idle XP',async()=>{const s=setup();s.as('member');const r=await s.call('pulse',{active:false});assert.equal(r.status,200);assert.equal(r.progress.xp,0);assert.equal(r.progress.challenges.length,4);assert.deepEqual(r.progress.challenges.map(c=>c.reward),[50,100,150,250])});
test('public poll results do not expose voter account IDs',async()=>{const s=setup();s.set('novaControl/polls/p',{title:'Vote',options:['A','B'],votes:{secretUid:0},closesAt:Date.now()+10000});s.as('member');const r=await s.call('public');assert.deepEqual(r.polls.p.counts,[1,0]);assert.equal(r.polls.p.votes,undefined)});
import fs from 'node:fs';
const rules=JSON.parse(fs.readFileSync(new URL('../firebase-voice.rules.json',import.meta.url))).rules;
const snap=value=>({exists:()=>value!=null,val:()=>value??null,child:path=>snap(path.split('/').reduce((n,k)=>n?.[k],value))});
test('Chat writes reject site-banned and muted accounts',()=>{const expression=rules.novaChatV2.channels.$channel.messages.$message['.write'];for(const mode of ['normal','siteBan','mute']){const source={novaAccounts:{alice:{}},novaControl:{siteBans:mode==='siteBan'?{alice:{at:1}}:{}},novaChatV2:{roles:{alice:'member'},mutes:mode==='mute'?{alice:20000}:{},sendClock:{alice:{at:9900,key:'m1',path:'channels/general/messages'}}}};const context={auth:{uid:'alice',token:{firebase:{sign_in_provider:'password'}}},root:snap(source),data:snap(null),newData:snap({author:'alice',text:'hi',createdAt:10000}),now:10000,$channel:'general',$message:'m1'};assert.equal(Function(...Object.keys(context),'return '+expression)(...Object.values(context)),mode==='normal')}});
test('live broadcasts enforce ownership and one vote with private ballots',async()=>{const s=setup();s.as('member');assert.equal((await s.call('livePublish',{text:'Hi'})).status,403);s.as('owner');assert.equal((await s.call('livePublish',{kind:'poll',text:'Next game?',options:'A\nB',seconds:60})).status,200);const id=s.get('novaControl/live').id;s.as('member');assert.equal((await s.call('liveVote',{id,choice:1})).status,200);assert.equal((await s.call('liveVote',{id,choice:0})).alreadyVoted,true);const feed=await s.call('liveFeed');assert.deepEqual(feed.live.counts,[0,1]);assert.equal(feed.live.votes,undefined);assert.equal(feed.live.name,'Owner');s.set('novaControl/live/expiresAt',1);assert.equal((await s.call('liveFeed')).live,null);assert.equal((await s.call('liveVote',{id,choice:0})).status,400);s.as('owner');await s.call('liveEnd');assert.equal(s.get('novaControl/live'),null)});

test('votes stay isolated when a new live poll replaces the old one',async()=>{const s=setup();await s.call('livePublish',{kind:'poll',text:'One',options:'A\nB',seconds:15});const old=s.get('novaControl/live').id;await s.call('livePublish',{kind:'poll',text:'Two',options:'A\nB',seconds:15});s.as('member');assert.equal((await s.call('liveVote',{id:old,choice:0})).status,400);assert.deepEqual((await s.call('liveFeed')).live.counts,[0,0]);});

test('only existing owners can grant full owner access',async()=>{const s=setup();s.as('member');assert.equal((await s.call('user',{uid:'member',kind:'role',value:'owner'})).status,403);s.as('owner');assert.equal((await s.call('user',{uid:'member',kind:'role',value:'owner'})).status,200);s.as('member');assert.equal((await s.call('dashboard')).status,200);assert.equal((await s.call('user',{uid:'owner',kind:'role',value:'member'})).status,400);assert.ok(Object.values(s.get('novaControl/audit')).some(a=>a.role==='owner'))});
test('today timeline records concurrent rises and drops rather than cumulative visitors',async()=>{const s=setup();const realNow=Date.now;let time=realNow();Date.now=()=>time;try{s.set('novaControl/activity/member',{at:time});const first=await s.call('dashboard');assert.equal(Object.values(first.timeline).at(-1).count,1);time+=61000;const drop=await s.call('dashboard');assert.deepEqual(Object.values(drop.timeline).map(p=>p.count),[1,0]);s.set('novaControl/activity/owner',{at:time});s.set('novaControl/activity/member',{at:time});time+=61000;s.set('novaControl/activity/owner',{at:time});s.set('novaControl/activity/member',{at:time});const rise=await s.call('dashboard');assert.deepEqual(Object.values(rise.timeline).map(p=>p.count),[1,0,2])}finally{Date.now=realNow}});

test('codes with hash and underscore create and redeem case-insensitively once',async()=>{const s=setup();const reward={code:'AICHATUPDATE#2027',coins:50,xp:1000,levels:10,multiplier:5,minutes:60,days:30};assert.equal((await s.call('code',reward)).status,200);assert.equal((await s.call('code',reward)).error,'That code already exists.');s.as('member');const redeemed=await s.call('redeem',{code:'aichatupdate#2027'});assert.equal(redeemed.status,200);assert.equal(redeemed.progress.coins,50);assert.equal(redeemed.progress.multiplier,5);assert.equal((await s.call('redeem',{code:reward.code})).status,400);s.as('owner');assert.equal((await s.call('code',{code:'NOVA_TEST-2'})).status,200)});

test('staff replies deliver private bot messages and reject nonstaff impersonation',async()=>{const s=setup();s.set('novaChatV2/feedback/member/ticket',{kind:'report',subject:'Game issue',text:'Something broke'});s.as('member');assert.equal((await s.call('staffReply',{uid:'member',id:'ticket',text:'Fake reply'})).status,403);s.as('owner');assert.equal((await s.call('reply',{uid:'member',id:'ticket',text:'Fixed for you'})).status,200);const m=Object.values(s.get('novaChatV2/botMessages/member'))[0];assert.equal(m.author,'nova-bot');assert.equal(m.text,'Fixed for you');assert.equal(m.subject,'Game issue');assert.equal((await s.call('deleteFeedback',{uid:'member',id:'ticket'})).status,200);assert.equal(s.get('novaChatV2/feedback/member/ticket'),null);assert.ok(s.get('novaChatV2/botMessages/member'))});
test('leaving groups removes membership and index and transfers ownership',async()=>{const s=setup();s.set('novaChatV2/groups/g',{owner:'owner',name:'Friends',members:{owner:true,member:true}});s.set('novaChatV2/userGroups/owner/g',true);assert.equal((await s.call('leaveGroup',{id:'g'})).status,200);assert.equal(s.get('novaChatV2/groups/g/owner'),'member');assert.equal(s.get('novaChatV2/groups/g/members/owner'),null);assert.equal(s.get('novaChatV2/userGroups/owner/g'),null);assert.equal((await s.call('leaveGroup',{id:'g'})).status,400)});

test('staff commands enforce privilege and owner protection',async()=>{const s=setup();s.as('member');assert.equal((await s.call('staffCommand',{command:'ban',uid:'owner'})).status,403);s.as('owner');assert.equal((await s.call('staffCommand',{command:'ban',uid:'member',scope:'chat'})).status,200);assert.equal((await s.call('staffCommand',{command:'status',uid:'member'})).chatBanned,true);assert.equal((await s.call('staffCommand',{command:'unban',uid:'member',scope:'chat'})).status,200);assert.equal((await s.call('staffCommand',{command:'ban',uid:'owner',scope:'chat'})).status,400);s.set('novaChatV2/roles/member','admin');s.as('member');assert.equal((await s.call('staffCommand',{command:'give',uid:'member',reward:'coins',amount:10})).status,403)});
test('profiles validate media and gradients require a server Nitro entitlement',async()=>{const s=setup();s.as('member');assert.equal((await s.call('profileUpdate',{name:'New name',bio:'Hello',photo:'javascript:alert(1)',banner:'',status:'online'})).status,400);assert.equal((await s.call('profileUpdate',{name:'New name',bio:'Hello',photo:'',banner:'https://example.com/banner.gif',status:'dnd',novaTag:true})).status,200);assert.equal(s.get('novaChatV2/profiles/member/novaTag'),true);assert.equal((await s.call('chatTheme',{theme:'light'})).status,200);assert.equal((await s.call('chatTheme',{theme:'aurora'})).status,400);s.set('novaControl/nitro/member',true);assert.equal((await s.call('chatTheme',{theme:'aurora'})).status,200)});

test('Nitro charges once, preserves staff role and counts one server boost',async()=>{const s=setup();s.set('novaControl/progress/owner',{coins:6000,xp:0});const requestId='12345678-1234-1234-1234-123456789abc';const first=await s.call('buyNitro',{requestId});assert.equal(first.status,200);assert.equal(first.coins,1000);assert.equal(s.get('novaChatV2/roles/owner'),'owner');assert.equal(s.get('novaChatV2/profiles/owner/nitroBooster'),true);assert.equal(s.get('novaChatV2/server/boosts'),1);assert.equal((await s.call('buyNitro',{requestId})).coins,1000);assert.equal(Object.keys(s.get('novaChatV2/channels/general/messages')).length,1);assert.equal((await s.call('buyNitro',{requestId:'22345678-1234-1234-1234-123456789abc'})).status,400);assert.equal((await s.call('nitroAnimation',{animation:'orbit'})).status,200)});
test('Case purchases enforce funds, bundles, inventory and retry safety',async()=>{const s=setup();s.as('member');const requestId='12345678-1234-1234-1234-123456789abc';assert.equal((await s.call('openCase',{kind:'decoration',count:1,requestId})).status,400);s.set('novaControl/progress/member',{coins:5000,xp:0});const purchase=await s.call('openCase',{kind:'decoration',count:3,requestId});assert.equal(purchase.status,200);assert.equal(purchase.coins,3850);assert.equal(purchase.rewards.length,3);const repeat=await s.call('openCase',{kind:'decoration',count:3,requestId});assert.deepEqual(repeat.rewards,purchase.rewards);assert.equal(repeat.coins,3850);assert.equal((await s.call('equipCosmetic',{id:purchase.rewards[0].id})).status,200);assert.equal(s.get('novaChatV2/profiles/member/decoration'),purchase.rewards[0].id);assert.equal((await s.call('equipCosmetic',{id:'banner-0'})).status,400);assert.equal((await s.call('openCase',{kind:'effect',count:2,requestId:'22345678-1234-1234-1234-123456789abc'})).status,400);assert.equal((await s.call('nitroAnimation',{animation:'shimmer'})).status,400)});

test('case tiers expose exact odds and have rewards in every category',async()=>{const {odds,catalog}=await import('../server/chat-store.mjs');assert.equal(odds.reduce((sum,[,weight])=>sum+weight,0),1000000);assert.equal(odds.find(([tier])=>tier==='singularity')[1],100);const items=await catalog();for(const kind of ['decoration','effect','banner'])for(const [rarity]of odds)assert.ok(items.some(a=>a.kind===kind&&a.rarity===rarity))});
