import test from 'node:test';import assert from 'node:assert/strict';import {createHandler} from '../api/owner-control.js';
function setup(){const data={novaAccounts:{owner:{name:'Owner'},member:{name:'Member'}},novaChatV2:{roles:{owner:'owner',member:'member'}}};let user='owner';const get=p=>p.split('/').reduce((v,k)=>v?.[k],data)??null;const set=(p,v)=>{let n=data;const keys=p.split('/');for(const k of keys.slice(0,-1))n=n[k]??={};if(v===null)delete n[keys.at(-1)];else n[keys.at(-1)]=structuredClone(v)};const snap=v=>({val:()=>structuredClone(v),exists:()=>v!==null});const db={ref(p){return {get:async()=>snap(get(p)),set:async v=>set(p,v),remove:async()=>set(p,null),update:async v=>set(p,{...get(p),...v}),push:async v=>set(p+'/id'+Math.random().toString().slice(2),v),transaction:async fn=>{const next=fn(structuredClone(get(p)));if(next===undefined)return {committed:false,snapshot:snap(get(p))};set(p,next);return {committed:true,snapshot:snap(next)}}}}};const handler=createHandler(async()=>({db,auth:{verifyIdToken:async token=>{if(token==='invalid')throw Error();return {uid:user,firebase:{sign_in_provider:'password'}}}}}));return {data,get,set,as:u=>user=u,async call(action,body={},token='valid'){let value;const res={setHeader(){},end(v){value=JSON.parse(v)}};await handler({method:'POST',headers:{authorization:'Bearer '+token},body:{action,...body}},res);return {status:res.statusCode,...value}}}}
test('nonowners cannot read dashboard or grant themselves rewards',async()=>{const s=setup();s.as('member');assert.equal((await s.call('dashboard')).status,403);assert.equal((await s.call('user',{uid:'member',kind:'reward',coins:100})).status,403);assert.equal(s.get('novaControl/progress/member'),null)});
test('invalid authentication rejected',async()=>{const s=setup();assert.equal((await s.call('status',{},'invalid')).status,401)});
test('codes redeem once and keep grants atomic',async()=>{const s=setup();assert.equal((await s.call('code',{code:'NOVA-TEST',coins:50,xp:500,levels:1,multiplier:2})).status,200);s.as('member');const first=await s.call('redeem',{code:'nova-test'});assert.equal(first.status,200);assert.equal(first.progress.coins,50);assert.equal((await s.call('redeem',{code:'NOVA-TEST'})).status,400);assert.equal(s.get('novaControl/progress/member').coins,50)});
test('chat bans are separate from Nova bans and appeals restore correct scope',async()=>{const s=setup();await s.call('user',{uid:'member',kind:'chatBan',value:true});assert.equal(s.get('novaControl/siteBans/member'),null);s.as('member');assert.equal((await s.call('status')).ban,null);await s.call('appeal',{scope:'chat',reason:'Please review my chat suspension.'});s.as('owner');await s.call('appealReview',{uid:'member',approve:true});assert.equal(s.get('novaChatV2/bans/member'),null);await s.call('user',{uid:'member',kind:'siteBan',value:true});s.as('member');assert.equal((await s.call('pulse')).status,403);assert.equal((await s.call('appeal',{reason:'Please review my account suspension.'})).status,200)});
test('owner accounts cannot be demoted or banned',async()=>{const s=setup();assert.equal((await s.call('user',{uid:'owner',kind:'role',value:'member'})).status,400);assert.equal((await s.call('user',{uid:'owner',kind:'siteBan',value:true})).status,400)});
test('event multipliers capped and challenges reset through a version',async()=>{const s=setup();assert.equal((await s.call('event',{xpMultiplier:51,coinMultiplier:1,minutes:60})).status,400);assert.equal((await s.call('event',{xpMultiplier:50,coinMultiplier:2,minutes:60})).status,200);await s.call('resetChallenges');assert.equal(s.get('novaControl/events/challengeVersion'),1)});
test('pulse creates four challenges and does not award idle XP',async()=>{const s=setup();s.as('member');const r=await s.call('pulse',{active:false});assert.equal(r.status,200);assert.equal(r.progress.xp,0);assert.equal(r.progress.challenges.length,4);assert.deepEqual(r.progress.challenges.map(c=>c.reward),[50,100,150,250])});
test('public poll results do not expose voter account IDs',async()=>{const s=setup();s.set('novaControl/polls/p',{title:'Vote',options:['A','B'],votes:{secretUid:0},closesAt:Date.now()+10000});s.as('member');const r=await s.call('public');assert.deepEqual(r.polls.p.counts,[1,0]);assert.equal(r.polls.p.votes,undefined)});
import fs from 'node:fs';
const rules=JSON.parse(fs.readFileSync(new URL('../firebase-voice.rules.json',import.meta.url))).rules;
const snap=value=>({exists:()=>value!=null,val:()=>value??null,child:path=>snap(path.split('/').reduce((n,k)=>n?.[k],value))});
test('Chat writes reject site-banned and muted accounts',()=>{const expression=rules.novaChatV2.channels.$channel.messages.$message['.write'];for(const mode of ['normal','siteBan','mute']){const source={novaAccounts:{alice:{}},novaControl:{siteBans:mode==='siteBan'?{alice:{at:1}}:{}},novaChatV2:{roles:{alice:'member'},mutes:mode==='mute'?{alice:20000}:{},sendClock:{alice:{at:9900,key:'m1',path:'channels/general/messages'}}}};const context={auth:{uid:'alice',token:{firebase:{sign_in_provider:'password'}}},root:snap(source),data:snap(null),newData:snap({author:'alice',text:'hi',createdAt:10000}),now:10000,$channel:'general',$message:'m1'};assert.equal(Function(...Object.keys(context),'return '+expression)(...Object.values(context)),mode==='normal')}});
test('live broadcasts enforce ownership and one vote with private ballots',async()=>{const s=setup();s.as('member');assert.equal((await s.call('livePublish',{text:'Hi'})).status,403);s.as('owner');assert.equal((await s.call('livePublish',{kind:'poll',text:'Next game?',options:'A\nB',seconds:60})).status,200);const id=s.get('novaControl/live').id;s.as('member');assert.equal((await s.call('liveVote',{id,choice:1})).status,200);assert.equal((await s.call('liveVote',{id,choice:0})).alreadyVoted,true);const feed=await s.call('liveFeed');assert.deepEqual(feed.live.counts,[0,1]);assert.equal(feed.live.votes,undefined);assert.equal(feed.live.name,'Owner');s.set('novaControl/live/expiresAt',1);assert.equal((await s.call('liveFeed')).live,null);assert.equal((await s.call('liveVote',{id,choice:0})).status,400);s.as('owner');await s.call('liveEnd');assert.equal(s.get('novaControl/live'),null)});

test('votes stay isolated when a new live poll replaces the old one',async()=>{const s=setup();await s.call('livePublish',{kind:'poll',text:'One',options:'A\nB',seconds:15});const old=s.get('novaControl/live').id;await s.call('livePublish',{kind:'poll',text:'Two',options:'A\nB',seconds:15});s.as('member');assert.equal((await s.call('liveVote',{id:old,choice:0})).status,400);assert.deepEqual((await s.call('liveFeed')).live.counts,[0,0]);});

test('only existing owners can grant full owner access',async()=>{const s=setup();s.as('member');assert.equal((await s.call('user',{uid:'member',kind:'role',value:'owner'})).status,403);s.as('owner');assert.equal((await s.call('user',{uid:'member',kind:'role',value:'owner'})).status,200);s.as('member');assert.equal((await s.call('dashboard')).status,200);assert.equal((await s.call('user',{uid:'owner',kind:'role',value:'member'})).status,400);assert.ok(Object.values(s.get('novaControl/audit')).some(a=>a.role==='owner'))});
test('today timeline records concurrent rises and drops rather than cumulative visitors',async()=>{const s=setup();const realNow=Date.now;let time=realNow();Date.now=()=>time;try{s.set('novaControl/activity/member',{at:time});const first=await s.call('dashboard');assert.equal(Object.values(first.timeline).at(-1).count,1);time+=61000;const drop=await s.call('dashboard');assert.deepEqual(Object.values(drop.timeline).map(p=>p.count),[1,0]);s.set('novaControl/activity/owner',{at:time});s.set('novaControl/activity/member',{at:time});time+=61000;s.set('novaControl/activity/owner',{at:time});s.set('novaControl/activity/member',{at:time});const rise=await s.call('dashboard');assert.deepEqual(Object.values(rise.timeline).map(p=>p.count),[1,0,2])}finally{Date.now=realNow}});

test('codes with hash and underscore create and redeem case-insensitively once',async()=>{const s=setup();const reward={code:'AICHATUPDATE#2027',coins:50,xp:1000,levels:10,multiplier:5,minutes:60,days:30};assert.equal((await s.call('code',reward)).status,200);assert.equal((await s.call('code',reward)).error,'That code already exists.');s.as('member');const redeemed=await s.call('redeem',{code:'aichatupdate#2027'});assert.equal(redeemed.status,200);assert.equal(redeemed.progress.coins,50);assert.equal(redeemed.progress.multiplier,5);assert.equal((await s.call('redeem',{code:reward.code})).status,400);s.as('owner');assert.equal((await s.call('code',{code:'NOVA_TEST-2'})).status,200)});
