import test from 'node:test';import assert from 'node:assert/strict';import {createHandler} from '../api/owner-control.js';
function setup(){const data={novaAccounts:{owner:{name:'Owner'},member:{name:'Member'}},novaChatV2:{roles:{owner:'owner',member:'member'}}};let user='owner';const get=p=>p.split('/').reduce((v,k)=>v?.[k],data)??null;const set=(p,v)=>{let n=data;const keys=p.split('/');for(const k of keys.slice(0,-1))n=n[k]??={};if(v===null)delete n[keys.at(-1)];else n[keys.at(-1)]=structuredClone(v)};const snap=v=>({val:()=>structuredClone(v),exists:()=>v!==null});const db={ref(p){return {get:async()=>snap(get(p)),set:async v=>set(p,v),remove:async()=>set(p,null),update:async v=>set(p,{...get(p),...v}),push:async v=>set(p+'/id'+Math.random().toString().slice(2),v),transaction:async fn=>{const next=fn(structuredClone(get(p)));if(next===undefined)return {committed:false,snapshot:snap(get(p))};set(p,next);return {committed:true,snapshot:snap(next)}}}}};const handler=createHandler(async()=>({db,auth:{verifyIdToken:async token=>{if(token==='invalid')throw Error();return {uid:user,firebase:{sign_in_provider:'password'}}}}}));return {data,get,set,as:u=>user=u,async call(action,body={},token='valid'){let value;const res={setHeader(){},end(v){value=JSON.parse(v)}};await handler({method:'POST',headers:{authorization:'Bearer '+token},body:{action,...body}},res);return {status:res.statusCode,...value}}}}
test('nonowners cannot read dashboard or grant themselves rewards',async()=>{const s=setup();s.as('member');assert.equal((await s.call('dashboard')).status,403);assert.equal((await s.call('user',{uid:'member',kind:'reward',coins:100})).status,403);assert.equal(s.get('novaControl/progress/member'),null)});
test('invalid authentication rejected',async()=>{const s=setup();assert.equal((await s.call('status',{},'invalid')).status,401)});
test('codes redeem once and keep grants atomic',async()=>{const s=setup();assert.equal((await s.call('code',{code:'NOVA-TEST',coins:50,xp:500,levels:1,multiplier:2})).status,200);s.as('member');const first=await s.call('redeem',{code:'nova-test'});assert.equal(first.status,200);assert.equal(first.progress.coins,50);assert.equal((await s.call('redeem',{code:'NOVA-TEST'})).status,400);assert.equal(s.get('novaControl/progress/member').coins,50)});
test('chat bans are separate from Nova bans and appeals restore correct scope',async()=>{const s=setup();await s.call('user',{uid:'member',kind:'chatBan',value:true});assert.equal(s.get('novaControl/siteBans/member'),null);s.as('member');assert.equal((await s.call('status')).ban,null);await s.call('appeal',{scope:'chat',reason:'Please review my chat suspension.'});s.as('owner');await s.call('appealReview',{uid:'member',approve:true});assert.equal(s.get('novaChatV2/bans/member'),null);await s.call('user',{uid:'member',kind:'siteBan',value:true});s.as('member');assert.equal((await s.call('pulse')).status,403);assert.equal((await s.call('appeal',{reason:'Please review my account suspension.'})).status,200)});
test('owner accounts cannot be demoted or banned',async()=>{const s=setup();assert.equal((await s.call('user',{uid:'owner',kind:'role',value:'member'})).status,400);assert.equal((await s.call('user',{uid:'owner',kind:'siteBan',value:true})).status,400)});
test('event multipliers capped and challenges reset through a version',async()=>{const s=setup();assert.equal((await s.call('event',{xpMultiplier:51,coinMultiplier:1,minutes:60})).status,400);assert.equal((await s.call('event',{xpMultiplier:50,coinMultiplier:2,minutes:60})).status,200);await s.call('resetChallenges');assert.equal(s.get('novaControl/events/challengeVersion'),1)});
test('pulse creates four challenges and does not award idle XP',async()=>{const s=setup();s.as('member');const r=await s.call('pulse',{active:false});assert.equal(r.status,200);assert.equal(r.progress.xp,0);assert.equal(r.progress.challenges.length,4);assert.deepEqual(r.progress.challenges.map(c=>c.reward),[50,100,150,250])});
test('public poll results do not expose voter account IDs',async()=>{const s=setup();s.set('novaControl/polls/p',{title:'Vote',options:['A','B'],votes:{secretUid:0},closesAt:Date.now()+10000});s.as('member');const r=await s.call('public');assert.deepEqual(r.polls.p.counts,[1,0]);assert.equal(r.polls.p.votes,undefined)});
import fs from 'node:fs';
const rules=JSON.parse(fs.readFileSync(new URL('../firebase-voice.rules.json',import.meta.url))).rules;
const snap=value=>({exists:()=>value!=null,val:()=>value??null,child:path=>snap(path.split('/').reduce((n,k)=>n?.[k],value))});
test('Chat writes reject site-banned and muted accounts',()=>{const expression=rules.novaChatV2.channels.$channel.messages.$message['.write'];for(const mode of ['normal','siteBan','mute']){const source={novaAccounts:{alice:{}},novaControl:{siteBans:mode==='siteBan'?{alice:{at:1}}:{}},novaChatV2:{roles:{alice:'member'},mutes:mode==='mute'?{alice:20000}:{},sendClock:{alice:{at:9900,key:'m1',path:'channels/general/messages'}}}};const context={auth:{uid:'alice',token:{firebase:{sign_in_provider:'password'}}},root:snap(source),data:snap(null),newData:snap({author:'alice',text:'hi',createdAt:10000}),now:10000,$channel:'general',$message:'m1'};assert.equal(Function(...Object.keys(context),'return '+expression)(...Object.values(context)),mode==='normal')}});
test('live broadcasts enforce ownership and one vote with private ballots',async()=>{const s=setup();s.as('member');assert.equal((await s.call('livePublish',{text:'Hi'})).status,403);s.as('owner');assert.equal((await s.call('livePublish',{kind:'poll',text:'Next game?',options:'A\nB',seconds:60})).status,200);const id=s.get('novaControl/live').id;s.as('member');assert.equal((await s.call('liveVote',{id,choice:1})).status,200);assert.equal((await s.call('liveVote',{id,choice:0})).status,400);const feed=await s.call('liveFeed');assert.deepEqual(feed.live.counts,[0,1]);assert.equal(feed.live.votes,undefined);assert.equal(feed.live.name,'Owner');s.set('novaControl/live/expiresAt',1);assert.equal((await s.call('liveFeed')).live,null);assert.equal((await s.call('liveVote',{id,choice:0})).status,400);s.as('owner');await s.call('liveEnd');assert.equal(s.get('novaControl/live'),null)});
