import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../remote-agent/renderer.js',import.meta.url),'utf8');
for(const captureMode of ['normal','quality-unsupported','retry','auto'])for(const rejectTuning of [false,true])test(captureMode+' screen sharing sends an offer '+(rejectTuning?'even when optional encoder tuning is unsupported':'with supported encoder settings'),async()=>{
 const elements=new Map(),get=id=>{if(!elements.has(id))elements.set(id,{hidden:false,value:'',textContent:''});return elements.get(id)};let heartbeat,offer=false,attempts=0,captureAttempts=0,peer;
 const track={kind:'video',applyConstraints:async()=>{if(captureMode==='quality-unsupported')throw Error('Unsupported quality')},getSettings:()=>({width:1920,height:1080,frameRate:60}),stop(){}};
 const sender={track,getParameters:()=>({encodings:[{}]}),setParameters:async params=>{attempts++;assert.ok(!params.degradationPreference||['balanced','maintain-resolution','maintain-framerate'].includes(params.degradationPreference));assert.equal(params.encodings[0].maxFramerate,60);if(rejectTuning)throw Error('Unsupported tuning')}};
 const api={state:async()=>({device:{name:'Test',id:'test'},enabled:true,autoConnect:captureMode==='auto'}),heartbeat:async()=>({device:{enabled:true},session:{id:'session',status:'requested',viewer:'test'}}),approve:async()=>captureMode==='auto'?{auto:true,sourceId:'primary'}:true,onStop(){},poll:async()=>({iceServers:[],signals:[],offset:0}),signal:async body=>{if(body.signal.type==='offer')offer=true},stop:async()=>{},input(){}};
 class Peer{constructor(){peer=this;this.localDescription=null}addTrack(){}getSenders(){return [sender]}createDataChannel(){return {}}async createOffer(){return {type:'offer',sdp:'test'}}async setLocalDescription(value){this.localDescription=value}close(){}}
 vm.runInNewContext(source,{window:{novaRemote:api},document:{getElementById:get},navigator:{mediaDevices:{getUserMedia:async options=>{assert.equal(captureMode,'auto');assert.equal(options.video.mandatory.chromeMediaSourceId,'primary');assert.equal(options.audio,false);return {getVideoTracks:()=>[track],getTracks:()=>[track]}},getDisplayMedia:async options=>{assert.equal(options.video,true);if(captureMode==='retry'&&++captureAttempts===1){const error=Error('Could not start video source');error.name='NotReadableError';throw error}return {getVideoTracks:()=>[track],getTracks:()=>[track]}}}},RTCPeerConnection:Peer,setInterval:fn=>{heartbeat=fn},setTimeout:()=>0,clearTimeout(){},console:{warn(){}},confirm:()=>false});
 await new Promise(resolve=>setImmediate(resolve));await heartbeat();await get('approve').onclick();await get('share').onclick();if(captureMode==='retry'){assert.equal(get('active').hidden,false);assert.equal(get('share').hidden,false);assert.match(get('notice').textContent,/Unlock your PC/);await get('share').onclick()}assert.equal(offer,true,get("notice").textContent);assert.equal(attempts,rejectTuning?2:1);assert.equal(get('active').hidden,false);peer.connectionState='disconnected';peer.onconnectionstatechange();assert.equal(get('active').hidden,false);assert.match(get('notice').textContent,/Waiting for the viewer/);peer.connectionState='connected';peer.onconnectionstatechange();assert.match(get('notice').textContent,/Connected/);
});

const main=await readFile(new URL('../remote-agent/main.cjs',import.meta.url),'utf8');
const captureHandler=main.slice(main.indexOf('session.defaultSession.setDisplayMediaRequestHandler('),main.indexOf("ipcMain.handle('state'"));
for(const revoked of [false,true])test('fresh primary display capture '+(revoked?'is denied if approval ends during source lookup':'uses the current source'),async()=>{
 let handler,finish,result;const frame={},fresh={display_id:'42',id:'fresh'};
 const context={active:'approved',enabled:true,lastProof:Date.now(),win:{webContents:{mainFrame:frame}},screenSource:{id:'stale'},Date,screen:{getPrimaryDisplay:()=>({id:42})},desktopCapturer:{getSources:()=>new Promise(resolve=>{finish=resolve})},session:{defaultSession:{setDisplayMediaRequestHandler:fn=>{handler=fn}}}};
 vm.runInNewContext(captureHandler,context);const pending=handler({frame},value=>{result=value});if(revoked)context.active=null;finish([fresh]);await pending;assert.equal(result.video,revoked?undefined:fresh);
});

for(const fps of [120,240])for(const unsupported of [false,true])test('host applies '+fps+' FPS target '+(unsupported?'without ending stream when unsupported':'to capture and encoder'),async()=>{let constraints={frameRate:{ideal:60,max:60}},encoded,ack;const track={applyConstraints:async c=>{constraints=c},getConstraints:()=>constraints,getSettings:()=>({frameRate:constraints.frameRate.ideal})};const sender={track,getParameters:()=>({encodings:[{}]}),setParameters:async p=>{if(unsupported)throw Error('Unsupported');encoded=p.encodings[0].maxFramerate}};const channel={readyState:'open',send:v=>{ack=JSON.parse(v)}};const mockPeer={getSenders:()=>[sender]},mockStream={getVideoTracks:()=>[track]},elements=new Map(),get=id=>{if(!elements.has(id))elements.set(id,{});return elements.get(id)};const ctx={window:{novaRemote:{onStop(){},state:async()=>({}),stop:async()=>{}}},document:{getElementById:get},matchMedia(){},setInterval(){},setTimeout(){},clearTimeout(){},console:{warn(){}},mockPeer,mockStream};vm.runInNewContext(source+"\nactive='s';pc=mockPeer;stream=mockStream;globalThis.runFPS=changeFPS;",ctx);await ctx.runFPS({fps},channel,'s');assert.equal(ack.ok,!unsupported);assert.equal(ack.fps,fps);assert.equal(constraints.frameRate.ideal,unsupported?60:fps);if(!unsupported)assert.equal(encoded,fps);ack=null;await ctx.runFPS({fps:999},channel,'s');assert.equal(ack,null);await ctx.runFPS({fps},channel,'unauthorized-session');assert.equal(ack,null)});

test('host polling tolerates one temporary failure while explicit session end still stops',async()=>{
 const handlers=new Map(),context={ipcMain:{handle:(name,fn)=>handlers.set(name,fn)},trusted(){},active:'s',lastProof:Date.now(),request:async()=>{throw Error('Network timeout')},Date,end:()=>{context.ended=true}};
 const start=main.indexOf("ipcMain.handle('poll'");const end=main.indexOf("ipcMain.handle(",start+20);vm.runInNewContext(main.slice(start,end),context);await assert.rejects(handlers.get('poll')({}, {session:'s'}),/Temporary remote service interruption/);assert.equal(context.ended,undefined);context.request=async()=>{const error=Error('Session ended.');error.status=410;throw error};await assert.rejects(handlers.get('poll')({}, {session:'s'}),/Session ended/);assert.equal(context.ended,true);
});
