import test from 'node:test';import assert from 'node:assert/strict';import {remoteRelay} from '../server/remote-relay.mjs';
const env={NOVA_TURN_URL:'turn:relay.example:3478,turn:relay.example:3478?transport=tcp,turns:relay.example:443?transport=tcp',NOVA_TURN_USERNAME:'user',NOVA_TURN_CREDENTIAL:'password'};
test('restricted Wi-Fi selects only the configured TLS relay on 443',()=>{const c=remoteRelay({env,mode:'relay'});assert.equal(c.iceTransportPolicy,'relay');assert.equal(c.relayTLSConfigured,true);assert.deepEqual(c.iceServers[0].urls,['turns:relay.example:443?transport=tcp']);assert.equal(c.iceServers.length,1)});
test('automatic mode retains normal ICE with all valid configured relay paths',()=>{const c=remoteRelay({env});assert.equal(c.iceTransportPolicy,'all');assert.equal(c.iceServers.length,2);assert.equal(c.iceServers[1].urls.length,3)});
test('incomplete credentials, invalid addresses and incorrect ports are not reported as ready',()=>{for(const value of [{},{...env,NOVA_TURN_CREDENTIAL:''},{...env,NOVA_TURN_URL:'https://relay.example,turn:relay.example:99999,turns://relay.example:443'}]){const c=remoteRelay({env:value,mode:'relay'});assert.equal(c.relayTLSConfigured,false);assert.equal(c.iceServers.length,0)}assert.equal(remoteRelay({env:{...env,NOVA_TURN_URL:'turn:relay.example:443?transport=tcp'}}).relayTLSConfigured,false)});
test('REST credentials expire with the approved session without exposing the signing secret',()=>{const c=remoteRelay({env:{...env,NOVA_TURN_SECRET:'secret'},uid:'u',expires:3600000,mode:'relay'});assert.equal(c.iceServers[0].username,'3660:u');assert.ok(c.iceServers[0].credential);assert.ok(!JSON.stringify(c).includes('secret'))});

test('ExpressTURN dashboard hostname supports UDP and TCP without a URL scheme',()=>{const c=remoteRelay({env:{...env,NOVA_TURN_URL:'free.expressturn.com:3478'}});assert.deepEqual(c.iceServers[1].urls,['turn:free.expressturn.com:3478','turn:free.expressturn.com:3478?transport=tcp']);assert.equal(c.relayTLSConfigured,false)});
test('existing static credentials use ExpressTURN defaults when URL is missing, without inventing TLS',()=>{const c=remoteRelay({env:{NOVA_TURN_USERNAME:'u',NOVA_TURN_CREDENTIAL:'p'}});assert.equal(c.relayConfigured,true);assert.equal(c.relayTLSConfigured,false);assert.equal(c.iceServers[1].urls.length,2)});
