import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../remote-agent/renderer.js',import.meta.url),'utf8');
for(const rejectTuning of [false,true])test('screen sharing sends an offer '+(rejectTuning?'even when optional encoder tuning is unsupported':'with supported encoder settings'),async()=>{
 const elements=new Map(),get=id=>{if(!elements.has(id))elements.set(id,{hidden:false,value:'',textContent:''});return elements.get(id)};let heartbeat,offer=false,attempts=0;
 const track={kind:'video',applyConstraints:async()=>{},getSettings:()=>({width:1920,height:1080,frameRate:60}),stop(){}};
 const sender={track,getParameters:()=>({encodings:[{}]}),setParameters:async params=>{attempts++;assert.ok(!params.degradationPreference||['balanced','maintain-resolution','maintain-framerate'].includes(params.degradationPreference));assert.equal(params.encodings[0].maxFramerate,60);if(rejectTuning)throw Error('Unsupported tuning')}};
 const api={state:async()=>({device:{name:'Test',id:'test'},enabled:true}),heartbeat:async()=>({device:{enabled:true},session:{id:'session',status:'requested',viewer:'test'}}),approve:async()=>true,onStop(){},poll:async()=>({iceServers:[],signals:[],offset:0}),signal:async body=>{if(body.signal.type==='offer')offer=true},stop:async()=>{},input(){}};
 class Peer{constructor(){this.localDescription=null}addTrack(){}getSenders(){return [sender]}createDataChannel(){return {}}async createOffer(){return {type:'offer',sdp:'test'}}async setLocalDescription(value){this.localDescription=value}close(){}}
 vm.runInNewContext(source,{window:{novaRemote:api},document:{getElementById:get},navigator:{mediaDevices:{getDisplayMedia:async()=>({getVideoTracks:()=>[track],getTracks:()=>[track]})}},RTCPeerConnection:Peer,setInterval:fn=>{heartbeat=fn},setTimeout:()=>0,clearTimeout(){},console:{warn(){}},confirm:()=>false});
 await new Promise(resolve=>setImmediate(resolve));await heartbeat();await get('approve').onclick();await get('share').onclick();assert.equal(offer,true,get("notice").textContent);assert.equal(attempts,rejectTuning?2:1);assert.equal(get('active').hidden,false);
});
