import test from 'node:test';import assert from 'node:assert/strict';import {createRemoteHandler} from '../api/remote.js';
function setup(){const data={novaAccounts:{alice:{name:'Alice'},bob:{name:'Bob'}}};let rules={'.read':false,'.write':false,novaRemote:{'.read':false,'.write':false}};
 const get=p=>p.split('/').reduce((v,k)=>v?.[k],data)??null,set=(p,v)=>{let row=data;const keys=p.split('/');for(const k of keys.slice(0,-1))row=row[k]??={};if(v===null)delete row[keys.at(-1)];else row[keys.at(-1)]=structuredClone(v)};
 const query=(p,key)=>{let equal,end,limit=Infinity;const q={equalTo(v){equal=v;return q},endAt(v){end=v;return q},limitToFirst(v){limit=v;return q},get:async()=>snap(Object.fromEntries(Object.entries(get(p)||{}).filter(([,row])=>equal!==undefined?row[key]===equal:row[key]<=end).slice(0,limit)))};return q};
 const snap=value=>({val:()=>structuredClone(value),exists:()=>value!==null});const db={getRulesJSON:async()=>({rules}),ref:p=>({orderByChild:key=>query(p,key),get:async()=>snap(get(p)),set:async v=>set(p,v),update:async v=>{for(const [k,value]of Object.entries(v))set(p+'/'+k,value)},transaction:async fn=>{const value=fn(structuredClone(get(p)));if(value===undefined)return {committed:false,snapshot:snap(get(p))};set(p,value);return {committed:true,snapshot:snap(value)}}})};
 const handler=createRemoteHandler(async()=>({db,auth:{verifyIdToken:async token=>{if(!['alice','bob','anonymous'].includes(token))throw Error();return {uid:token,firebase:{sign_in_provider:token==='anonymous'?'anonymous':'password'}}}}}));
 const call=async(action,body={},token='alice')=>{let value;const res={setHeader(){},end(raw){value=JSON.parse(raw)}};await handler({method:'POST',headers:{authorization:'Bearer '+token},socket:{remoteAddress:'test'},body:{action,...body}},res);return {...value,httpStatus:res.statusCode}};
 async function pair(){const start=await call('pairStart',{name:'Gaming PC'},'');await call('pairClaim',{code:start.code});const finish=await call('pairFinish',{code:start.code,token:start.token},'');assert.equal(finish.httpStatus,200);return {...finish,auth:'device:'+finish.id+':'+finish.credential};}
 return {data,get,set,call,pair,rules:value=>rules=value};
}
test('pairing requires both an account claim and a private local-agent token',async()=>{const s=setup(),start=await s.call('pairStart',{name:'PC'},'');assert.equal((await s.call('pairFinish',{code:start.code,token:start.token},'')).httpStatus,400);assert.equal((await s.call('pairClaim',{code:start.code},'anonymous')).httpStatus,403);await s.call('pairClaim',{code:start.code});assert.equal((await s.call('pairFinish',{code:start.code,token:'wrong'},'')).httpStatus,401);assert.equal((await s.call('pairClaim',{code:start.code},'bob')).httpStatus,400)});
test('registration hashes credentials, disables access by default, and keeps devices private',async()=>{const s=setup(),d=await s.pair();const saved=s.get('novaRemote/devices/'+d.id);assert.equal(saved.enabled,false);assert.notEqual(saved.tokenHash,d.credential);assert.equal(saved.credential,undefined);assert.equal((await s.call('list',{},'bob')).devices.length,0);const list=await s.call('list');assert.equal(list.devices.length,1);assert.equal(list.devices[0].tokenHash,undefined);assert.equal((await s.call('heartbeat',{},'device:'+d.id+':wrong')).httpStatus,401)});
test('knowledge of a device ID cannot authorize access or change its settings',async()=>{const s=setup(),d=await s.pair();for(const action of ['connect','rename','disable','remove'])assert.equal((await s.call(action,{id:d.id,name:'Bad'},'bob')).httpStatus,404);assert.equal((await s.call('list',{},'invalid')).httpStatus,401);assert.equal((await s.call('enable',{id:d.id})).httpStatus,403)});
test('remote sessions require local enablement and host approval, then enforce signal direction',async()=>{const s=setup(),d=await s.pair();assert.equal((await s.call('connect',{id:d.id})).httpStatus,400);await s.call('enable',{},d.auth);const session=await s.call('connect',{id:d.id,viewer:'My laptop'});assert.equal(session.httpStatus,200);assert.equal((await s.call('approve',{session:session.session})).httpStatus,403);assert.equal((await s.call('signal',{session:session.session,signal:{type:'answer',sdp:'answer'}})).httpStatus,400);assert.equal((await s.call('approve',{session:session.session},d.auth)).httpStatus,200);assert.equal((await s.call('signal',{session:session.session,signal:{type:'offer',sdp:'offer'}})).httpStatus,400);assert.equal((await s.call('signal',{session:session.session,signal:{type:'offer',sdp:'offer'}},d.auth)).httpStatus,200);const poll=await s.call('poll',{session:session.session});assert.deepEqual(poll.signals,[{type:'offer',sdp:'offer'}]);assert.equal((await s.call('poll',{session:session.session},'bob')).httpStatus,404);assert.equal((await s.call('poll',{session:session.session,offset:poll.offset})).signals.length,0)});
test('disable, remove, expiration and bans all revoke an active session',async()=>{for(const mode of ['disable','remove','expire','ban']){const s=setup(),d=await s.pair();await s.call('enable',{},d.auth);const {session}=await s.call('connect',{id:d.id});await s.call('approve',{session},d.auth);if(mode==='expire')s.set('novaRemote/sessions/'+session+'/expires',Date.now()-1);else if(mode==='ban')s.set('novaControl/siteBans/alice',{at:Date.now()});else await s.call(mode,{id:d.id});assert.notEqual((await s.call('poll',{session},d.auth)).httpStatus,200);if(mode==='remove')assert.equal((await s.call('heartbeat',{},d.auth)).httpStatus,401)}});
test('disconnect cannot be undone by a delayed approval and simultaneous requests are rejected',async()=>{const s=setup(),d=await s.pair();await s.call('enable',{},d.auth);const {session}=await s.call('connect',{id:d.id});assert.equal((await s.call('connect',{id:d.id})).httpStatus,409);await s.call('disconnect',{session});assert.equal((await s.call('approve',{session},d.auth)).httpStatus,410);assert.equal((await s.call('connect',{id:d.id})).httpStatus,200)});
test('open database rules fail closed and pairing abuse is limited',async()=>{const s=setup();s.rules({'.read':false,'.write':false,novaRemote:{'.read':true}});assert.equal((await s.call('pairStart',{},'')).httpStatus,503);const safe=setup();for(let i=0;i<8;i++)assert.equal((await safe.call('pairStart',{},'')).httpStatus,200);assert.equal((await safe.call('pairStart',{},'')).httpStatus,429)});
test('session signals reject malformed payloads and are bounded',async()=>{const s=setup(),d=await s.pair();await s.call('enable',{},d.auth);const {session}=await s.call('connect',{id:d.id});await s.call('approve',{session},d.auth);assert.equal((await s.call('signal',{session,signal:{type:'candidate',candidate:{}}})).httpStatus,400);s.set('novaRemote/sessions/'+session+'/signals/viewer',Array.from({length:160},()=>({type:'candidate',candidate:{candidate:'x'}})));assert.equal((await s.call('signal',{session,signal:{type:'candidate',candidate:{candidate:'x'}}})).httpStatus,429)});
test('only the registered computer can approve its session',async()=>{const s=setup(),one=await s.pair(),two=await s.pair();await s.call('enable',{},one.auth);const {session}=await s.call('connect',{id:one.id});assert.equal((await s.call('approve',{session},two.auth)).httpStatus,404)});
