import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../Public/src/synapse-compat.js',import.meta.url),'utf8');
function fixture(){let release;const applied=[];class Peer{setRemoteDescription(){return new Promise(resolve=>{release=()=>{this.remoteDescription={type:'offer'};resolve()}})}addIceCandidate(c){assert.ok(this.remoteDescription);applied.push(c);return Promise.resolve()}createAnswer(){assert.ok(this.remoteDescription);return Promise.resolve({type:'answer'})}close(){}}const window={RTCPeerConnection:Peer};vm.runInNewContext(source,{window,Promise,WeakMap,DOMException,Response});return {api:window.NovaSynapseCompat,Peer,applied,release:()=>release()}}
test('buffers early ICE and waits for the remote description before answering',async()=>{const f=fixture();f.api.install();const pc=new f.Peer();const candidate=pc.addIceCandidate('early'),remote=pc.setRemoteDescription({}),answer=pc.createAnswer();await Promise.resolve();assert.equal(f.applied.length,0);f.release();await Promise.all([candidate,remote,answer]);assert.deepEqual(f.applied,['early'])});
test('close rejects pending candidates and does not apply them later',async()=>{const f=fixture();f.api.install();const pc=new f.Peer();const candidate=pc.addIceCandidate('early');pc.close();await assert.rejects(candidate,{name:'InvalidStateError'});assert.equal(f.applied.length,0)});
test('patches the broken loading call and injects compatibility before provider scripts',async()=>{const f=fixture();const response={body:'<head><script>socketBind;joinRoom;loading();</script>',headers:[['Content-Length','10'],['Content-Type','text/html']],status:200};const patched=await f.api.patchPlayer(response);assert.match(patched.body,/typeof loading/);assert.ok(patched.body.indexOf('__novaSynapseCompat')<patched.body.indexOf('socketBind'));assert.equal(patched.headers.length,1);const other={...response,body:'<head>Unrelated'};assert.equal(await f.api.patchPlayer(other),other)});

test('stale or repeated channel close cannot close a newer peer or throw on null',async()=>{
 const f=fixture(),html='<head><script>socketBind;joinRoom;_0x239d1b[a0_0x2ea2(0x252)] = () => {this.pc[a0_0x2ea2(0x1ff)]();this.pc = null;this[a0_0x2ea2(0x334)] = null;};</script>';
 const patched=await f.api.patchPlayer({body:html,headers:[]});const code=patched.body.slice(patched.body.lastIndexOf('<script>')+8,patched.body.lastIndexOf('</script>'));
 const channel={},keys={0x252:'onclose',0x1ff:'close',0x334:'channel'};let closes=0;const host={pc:{close(){closes++}},channel};vm.runInNewContext('(function(){'+code+'}).call(host)',{socketBind:null,joinRoom:null,host,_0x239d1b:channel,a0_0x2ea2:key=>keys[key]});
 channel.onclose();channel.onclose();assert.equal(closes,1);host.pc={close(){closes++}};host.channel={};channel.onclose();assert.equal(closes,1);
});
