import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {createVoiceHandler} from '../api/voice.js';
import {voiceIceConfig,roomCapacity} from '../server/voice-config.mjs';
function fixture(uid='alice',provider='password'){
 const data={novaAccounts:{alice:{name:'Alice',onboardingComplete:true},bob:{name:'Bob',onboardingComplete:true},eve:{name:'Eve',onboardingComplete:true}},novaChatV2:{friends:{alice:{bob:true},bob:{alice:true}},profiles:{alice:{name:'Alice'},bob:{name:'Bob'}}}};
 const value=path=>path.split('/').reduce((v,k)=>v?.[k],data)??null;
 function set(path,v){const keys=path.split('/'),last=keys.pop();let p=data;for(const k of keys)p=p[k]??={};if(v===null)delete p[last];else p[last]=structuredClone(v);}
 const snapshot=v=>({val:()=>structuredClone(v),exists:()=>v!==null});
 const ref=path=>({get:async()=>snapshot(value(path)),set:async v=>set(path,v),remove:async()=>set(path,null),child:k=>ref(path+'/'+k),transaction:async fn=>{const next=fn(structuredClone(value(path)));if(next===undefined)return {committed:false,snapshot:snapshot(value(path))};set(path,next);return {committed:true,snapshot:snapshot(next)};}});
 const handler=createVoiceHandler(async()=>({db:{ref},auth:{verifyIdToken:async()=>({uid,firebase:{sign_in_provider:provider}})}}));
 const invoke=async body=>{const res={statusCode:200,setHeader(){},status(code){this.statusCode=code;return this},json(v){this.data=v;return this;}};await handler({method:'POST',headers:{authorization:'Bearer verified'},body},res);return res;};
 return {data,set,invoke};
}
test('voice requires a real Nova account, not a legacy anonymous identity',async()=>{assert.equal((await fixture('alice','anonymous').invoke({action:'lobby'})).statusCode,401)});
test('both public rooms are independent and bounded',async()=>{const f=fixture();assert.equal((await f.invoke({action:'join',room:'server-vc-1',session:'s1'})).statusCode,200);const l=await f.invoke({action:'lobby'});assert.equal(Object.keys(l.data.rooms['server-vc-1'].members).length,1);assert.equal(Object.keys(l.data.rooms['server-vc-2'].members).length,0);assert.equal(roomCapacity('server-vc-1'),6)});
test('outsiders cannot join or signal a private call',async()=>{const f=fixture('eve');f.set('novaVoice/rooms/private',{created:Date.now(),allowed:['alice','bob'],members:{b:{uid:'bob',account:'bob',expires:Date.now()+45000}}});assert.equal((await f.invoke({action:'join',room:'private',session:'e'})).statusCode,403);assert.equal((await f.invoke({action:'signal',room:'private',session:'b',to:'e',signal:{type:'offer',sdp:'x'}})).statusCode,403)});
test('session ownership is checked before sending or removing media signaling',async()=>{const f=fixture();f.set('novaVoice/rooms/server-vc-1',{members:{b:{uid:'bob',account:'bob',expires:Date.now()+45000}}});assert.equal((await f.invoke({action:'leave',room:'server-vc-1',session:'b'})).statusCode,403);assert.ok(f.data.novaVoice.rooms['server-vc-1'].members.b)});
test('live camera, screen and mute state survives polling; leaving removes only that member',async()=>{const f=fixture();await f.invoke({action:'join',room:'server-vc-1',session:'a'});const poll=await f.invoke({action:'poll',room:'server-vc-1',session:'a',camera:true,screen:true,muted:true});assert.equal(poll.data.members.a.screen,true);assert.equal(poll.data.members.a.camera,true);assert.equal(poll.data.members.a.muted,true);await f.invoke({action:'leave',room:'server-vc-1',session:'a'});assert.deepEqual(f.data.novaVoice.rooms['server-vc-1'].members,{})});
test('six live users fill a public room; expired membership frees a slot',async()=>{const f=fixture();const members=Object.fromEntries(Array.from({length:6},(_,i)=>['s'+i,{uid:'u'+i,account:'u'+i,expires:Date.now()+45000}]));f.set('novaVoice/rooms/server-vc-2',{members});assert.equal((await f.invoke({action:'join',room:'server-vc-2',session:'a'})).statusCode,409);f.set('novaVoice/rooms/server-vc-2/members/s0/expires',1);assert.equal((await f.invoke({action:'join',room:'server-vc-2',session:'a'})).statusCode,200)});
test('private invitations require friendship and respect blocking',async()=>{const f=fixture();f.set('novaVoice/devices/eve',{account:'eve',lastSeen:Date.now()});assert.equal((await f.invoke({action:'call',target:'eve'})).statusCode,403);f.set('novaVoice/devices/bob',{account:'bob',lastSeen:Date.now()});f.set('novaChatV2/blocked/bob/alice',true);assert.equal((await f.invoke({action:'call',target:'bob'})).statusCode,403)});
test('TURN REST credentials expire and include TLS endpoint, without exposing the secret',()=>{const env={NOVA_TURN_URL:'turn:relay.example:3478?transport=udp,turns:relay.example:443?transport=tcp',NOVA_TURN_SECRET:'test-only-secret'};const c=voiceIceConfig(env,'alice',1000000);assert.equal(c.relayConfigured,true);assert.equal(c.relayTls,true);assert.equal(c.iceServers[1].username,'22600:alice');assert.equal(c.iceServers[1].credential,createHmac('sha1',env.NOVA_TURN_SECRET).update('22600:alice').digest('base64'));assert.ok(!JSON.stringify(c).includes(env.NOVA_TURN_SECRET));assert.equal(voiceIceConfig({NOVA_TURN_URL:'https://invalid'},'a').relayConfigured,false)});

test('voice respects current Chat mutes and Nova site bans',async()=>{const f=fixture();f.set('novaChatV2/mutes/alice',Date.now()+60000);assert.equal((await f.invoke({action:'join',room:'server-vc-1',session:'a'})).statusCode,403);f.set('novaChatV2/mutes/alice',null);f.set('novaControl/siteBans/alice',{reason:'restricted'});assert.equal((await f.invoke({action:'join',room:'server-vc-1',session:'a'})).statusCode,403)});
test('signaling reaches only a live member and is retained until acknowledgment',async()=>{const f=fixture();await f.invoke({action:'join',room:'server-vc-1',session:'a'});f.set('novaVoice/rooms/server-vc-1/members/b',{uid:'bob',account:'bob',expires:Date.now()+90000});const signal={type:'offer',sdp:'test-sdp'};assert.equal((await f.invoke({action:'signal',room:'server-vc-1',session:'a',to:'b',signal})).statusCode,200);assert.equal(Object.keys(f.data.novaVoice.rooms['server-vc-1'].signals.b).length,1);assert.equal((await f.invoke({action:'signal',room:'server-vc-1',session:'a',to:'outsider',signal})).statusCode,409)});
