(()=>{
 const watcher=new MutationObserver(()=>{const panel=document.getElementById('nova-lol-practice');if(panel){watcher.disconnect();decorate(panel)}});watcher.observe(document.documentElement,{childList:true,subtree:true});const existing=document.getElementById('nova-lol-practice');if(existing){watcher.disconnect();decorate(existing)}
 function decorate(panel){
 if(panel.dataset.novaMenuVersion==='2')return;panel.dataset.novaMenuVersion='2';
 const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
 const style=document.createElement('style');style.textContent=`
 #nova-lol-practice .lol-layout{grid-template-columns:minmax(0,1fr) 54px!important}#nova-lol-practice nav{order:2;padding:8px 5px}#nova-lol-practice nav button{font-size:20px;min-height:42px;text-align:center}#nova-lol-practice .lol-content{min-width:0}
 .nova-owner-welcome{position:absolute;inset:0;z-index:8;background:#0b0b0efa;display:grid;place-content:center;text-align:center;pointer-events:none;border-radius:inherit}.nova-owner-welcome small{color:#ef3340;letter-spacing:3px;font-size:10px}.nova-owner-welcome strong{font-size:24px;max-width:350px;overflow-wrap:anywhere;min-height:60px;margin-top:16px;color:#fff;text-shadow:0 0 22px #ef334077}
 .nova-character{height:160px;display:grid;place-items:center;background:radial-gradient(ellipse,#ef334023,transparent 65%);border:1px solid #ffffff12;border-radius:12px;margin:10px 0}.nova-character svg{height:138px;filter:drop-shadow(0 0 10px #ef334055)}.nova-tool-chips{display:flex;gap:6px;flex-wrap:wrap}.nova-tool-chips span{padding:5px 8px;border-radius:20px;background:#ef334020;border:1px solid #ef334044;color:#ffc5cc;font-size:10px}
 `;document.head.append(style);
 const nav=panel.querySelector('nav'),content=panel.querySelector('.lol-content');
 for(const [id,title]of [['aim','Aim controls'],['visual','Scene & overlays'],['macro','Input shortcuts'],['settings','Your preferences']]){const heading=document.createElement('h2');heading.className='nova-section-heading';heading.textContent=title;document.getElementById('lol-pane-'+id).prepend(heading)}
 for(const [id,icon,label]of [['aim','◎','Aim'],['visual','◈','Visual'],['macro','⌘','Macro'],['settings','⚙','Settings']]){const b=document.getElementById('lol-tab-'+id);b.textContent=icon;b.title=label;b.setAttribute('aria-label',label)}
 const button=document.createElement('button');button.type='button';button.textContent='♙';button.title='Character';button.setAttribute('role','tab');button.setAttribute('aria-label','Character');button.setAttribute('aria-controls','nova-character-pane');button.setAttribute('aria-selected','false');nav.prepend(button);
 const page=document.createElement('div');page.id='nova-character-pane';page.setAttribute('role','tabpanel');page.hidden=true;page.innerHTML='<h3>Your loadout</h3><div class="nova-character"><svg viewBox="0 0 100 150" aria-label="Character preview" role="img"><circle cx="50" cy="24" r="17" fill="#25252c" stroke="#ef3340" stroke-width="2"/><path d="M31 47 Q50 38 69 47 L77 88 L64 92 L62 65 L61 100 L65 141 L52 141 L50 107 L47 141 L34 141 L39 100 L38 65 L36 92 L23 88Z" fill="#25252c" stroke="#ef3340" stroke-width="2"/></svg></div><div class="nova-tool-chips"></div><p>Your enabled tools. This preview represents your controls, not another player.</p>';
 content.append(page);const chips=page.querySelector('.nova-tool-chips');
 function update(){chips.replaceChildren();const enabled=[...panel.querySelectorAll('input[type=checkbox]:checked:not(:disabled)')].filter(x=>!['lol-compact','nova-potato'].includes(x.id)).map(x=>x.closest('label')?.textContent.trim()).filter(Boolean);if(document.getElementById('lol-aim').getAttribute('aria-pressed')==='true')enabled.unshift('Aim assist');if(document.getElementById('nova-potato')?.checked)enabled.push('Potato graphics');for(const text of enabled.length?enabled:['No tools enabled']){const chip=document.createElement('span');chip.textContent=text;chips.append(chip)}}
 panel.addEventListener('change',update);panel.addEventListener('click',()=>queueMicrotask(update));update();
 nav.addEventListener('click',e=>{if(e.target.closest('button')!==button){page.hidden=true;button.setAttribute('aria-selected','false')}});
 button.onclick=()=>{for(const pane of content.querySelectorAll('[role=tabpanel]'))pane.hidden=pane!==page;for(const b of nav.querySelectorAll('button'))b.setAttribute('aria-selected',String(b===button));update()};
 const aimButton=document.getElementById('lol-aim'),originalAimClick=aimButton.onclick;aimButton.onclick=event=>{originalAimClick?.(event);if(window.NovaLOLVisual?.state.aim){panel.hidden=true;const launcher=document.getElementById('nova-lol-launch');if(launcher)launcher.hidden=false;const canvas=document.getElementById('unity-canvas');canvas?.focus();try{const locked=canvas?.requestPointerLock?.();locked?.catch?.(()=>{document.getElementById('lol-status').textContent='Aim enabled · click the game to capture the cursor.'})}catch{document.getElementById('lol-status').textContent='Aim enabled · click the game to capture the cursor.'}}};
 const reloadPane=document.getElementById('lol-pane-macro');const reloadLabel=document.createElement('label');reloadLabel.className='check';const reloadToggle=document.createElement('input');reloadToggle.type='checkbox';reloadToggle.id='nova-reload-spam';reloadLabel.append(reloadToggle,' Reload spam');const reloadNote=document.createElement('p');reloadNote.textContent='Sends R every 150 ms while the game cursor is captured. Stops in menus. The game still controls reload duration.';reloadPane.append(reloadLabel,reloadNote);
 let reloadTimer=null,reloadHeld=false;const reloadCanvas=document.getElementById('unity-canvas');const reloadKey={key:'r',code:'KeyR',keyCode:82};const releaseReload=()=>{if(reloadHeld){window.NovaLOLInput?.keyboard(reloadCanvas,'keyup',reloadKey);reloadHeld=false}};const stopReload=()=>{clearTimeout(reloadTimer);reloadTimer=null;releaseReload()};const tickReload=()=>{if(!reloadToggle.checked||document.hidden||!document.hasFocus()||document.pointerLockElement!==reloadCanvas){stopReload();return}window.NovaLOLInput?.keyboard(reloadCanvas,'keydown',reloadKey);reloadHeld=true;reloadTimer=setTimeout(()=>{releaseReload();reloadTimer=setTimeout(tickReload,110)},40)};const syncReload=()=>{stopReload();if(reloadToggle.checked&&document.pointerLockElement===reloadCanvas&&!document.hidden)tickReload()};reloadToggle.onchange=syncReload;document.addEventListener('pointerlockchange',syncReload);document.addEventListener('visibilitychange',syncReload);window.addEventListener('blur',stopReload);window.addEventListener('pagehide',stopReload,{once:true});document.getElementById('lol-disable-all').addEventListener('click',()=>{reloadToggle.checked=false;stopReload()});
 const aimPane=document.getElementById('lol-pane-aim');const soft=document.createElement('button');soft.type='button';soft.textContent='Soft aim preset';soft.onclick=()=>{const speed=document.getElementById('lol-strength');speed.value=20;speed.dispatchEvent(new Event('input'));};aimPane.append(soft);
 const settings=document.getElementById('lol-pane-settings'),label=document.createElement('label');label.className='check';const potato=document.createElement('input');potato.type='checkbox';potato.id='nova-potato';potato.checked=localStorage.getItem('nova_buildnow_potato')==='true';label.append(potato,' Potato graphics');const note=document.createElement('p');note.textContent='Lower rendering resolution for less GPU load. Apply restarts the game; FPS gains depend on your device.';const apply=document.createElement('button');apply.type='button';apply.textContent='Apply graphics & restart';apply.onclick=()=>{localStorage.setItem('nova_buildnow_potato',String(potato.checked));location.reload()};settings.append(label,note,apply);
 // Character console: hide map/debug controls while keeping existing bindings intact.
 for(const id of ['broad-meshes','moving','esp','wireframe','motion','depth']){const field=document.getElementById('lol-'+id)?.closest('label');if(field)field.hidden=true}
 for(const text of aimPane.querySelectorAll('p'))text.textContent='Tracking uses moving model candidates. Player identity and head positions are estimates.';
 const field=(title,input,pane=aimPane)=>{const label=document.createElement('label');label.append(title,input);pane.append(label);return input};
 const mode=document.createElement('select');for(const [value,title]of [['soft','Soft aim'],['assist','Aim assist'],['auto','Aim + auto shoot'],['silent','Silent aim · unavailable']]){const option=document.createElement('option');option.value=value;option.textContent=title;option.disabled=value==='silent';mode.append(option)}mode.value='assist';field('Aim mode',mode);mode.onchange=()=>{const speed=document.getElementById('lol-strength'),shoot=document.getElementById('lol-auto-shoot');speed.value=mode.value==='soft'?20:mode.value==='auto'?75:40;speed.dispatchEvent(new Event('input'));shoot.checked=mode.value==='auto';shoot.dispatchEvent(new Event('change'));update()};
 const hold=document.createElement('input');hold.type='checkbox';field('Hold trigger key',hold);const trigger=document.createElement('input');trigger.type='text';trigger.maxLength=1;trigger.value='e';trigger.style.width='48px';field('Trigger key',trigger);const visual=window.NovaLOLVisual;hold.onchange=()=>{if(visual){visual.state.requireTrigger=hold.checked;visual.state.triggerDown=false}};const keyDown=e=>{if(e.target.closest?.('input,select,textarea')||panel.contains(e.target))return;if(e.key.toLowerCase()===trigger.value.toLowerCase()&&visual)visual.state.triggerDown=true};const keyUp=e=>{if(e.key.toLowerCase()===trigger.value.toLowerCase()&&visual)visual.state.triggerDown=false};window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',()=>{if(visual)visual.state.triggerDown=false});
 const aimPoint=document.createElement('select');for(const [value,title]of [['body','Center'],['head','Head estimate']]){const option=document.createElement('option');option.value=value;option.textContent=title;aimPoint.append(option)}field('Target point',aimPoint);aimPoint.onchange=()=>{if(visual)visual.state.aimPoint=aimPoint.value};document.getElementById('lol-range').closest('label').firstChild.textContent='Aim radius · pixels';
 const visuals=document.getElementById('lol-pane-visual');for(const [id,title]of [['boxes','Candidate boxes'],['lines','Candidate tracers']])document.getElementById('lol-'+id).closest('label').lastChild.textContent=' '+title;
 const heads=document.createElement('input');heads.type='checkbox';field('Head circles · estimated',heads,visuals);heads.onchange=()=>{if(visual)visual.state.headCircles=heads.checked};
 const unavailable=document.createElement('p');unavailable.textContent='Player-only and skeleton ESP need player and bone data that this build does not expose.';visuals.append(unavailable);
 const crossStyle=document.createElement('select');for(const shape of ['cross','dot','circle','diamond']){const option=document.createElement('option');option.value=shape;option.textContent=shape;crossStyle.append(option)}field('Crosshair style',crossStyle,visuals);crossStyle.onchange=()=>{document.getElementById('nova-lol-crosshair').dataset.shape=crossStyle.value};
 const resolution=document.createElement('select');for(const value of ['native','1024x768','1280x960','1440x1080','1280x1024']){const option=document.createElement('option');option.value=value;option.textContent=value==='native'?'Native':value.replace('x',' × ');resolution.append(option)}resolution.value=localStorage.getItem('nova_buildnow_resolution')||'native';field('Render resolution',resolution,settings);const applyResolution=document.createElement('button');applyResolution.textContent='Apply resolution & restart';applyResolution.onclick=()=>{localStorage.setItem('nova_buildnow_resolution',resolution.value);location.reload()};settings.append(applyResolution);const displayNote=document.createElement('p');displayNote.textContent='4:3 and 5:4 presets stretch to fill the screen. Applying restarts the game.';settings.append(displayNote);const cameraNote=document.createElement('p');cameraNote.textContent='FOV changes perspective projection: 90° keeps the original view; lower narrows it and higher widens it. This scale is relative to the game default.';aimPane.append(cameraNote);
 const zoom=document.createElement('input');zoom.type='range';zoom.min=60;zoom.max=120;zoom.step=1;zoom.value=localStorage.getItem('nova_buildnow_camera_fov')||'90';zoom.setAttribute('aria-label','Camera FOV');const zoomOutput=document.createElement('output');const zoomLabel=document.createElement('label');zoomLabel.append('Camera FOV',zoom,zoomOutput);settings.append(zoomLabel);const applyZoom=()=>{const degrees=Math.max(60,Math.min(120,Number(zoom.value)||90));zoomOutput.textContent=degrees+'°';if(visual)visual.state.zoom=1/Math.tan(degrees*Math.PI/360);localStorage.setItem('nova_buildnow_camera_fov',String(degrees))};zoom.oninput=applyZoom;applyZoom();
 const reset=document.createElement('button');reset.type='button';reset.textContent='Reset all settings';reset.onclick=()=>{document.getElementById('lol-disable-all').click();for(const key of ['nova-lol-appearance-v1','nova-lol-practice-bindings-v2','nova_buildnow_potato','nova_buildnow_resolution','nova_buildnow_stretch','nova_buildnow_zoom','nova_buildnow_camera_fov'])localStorage.removeItem(key);location.reload()};settings.append(reset);
 for(const id of ['mesh-color','box-color','line-color','ring-color','cross-color']){const input=document.getElementById('lol-'+id);input.value='#a390e5';input.dispatchEvent(new Event('input'))}
 const accent=document.getElementById('lol-menu-accent');accent.value='#9187ce';accent.dispatchEvent(new Event('input'));document.getElementById('lol-cross-color').value='#aaa0ee';document.getElementById('lol-cross-color').dispatchEvent(new Event('input'));
 const targetColumn=document.createElement('section');targetColumn.className='nova-target-column';const targetHeading=document.createElement('h3');targetHeading.textContent='TARGETING';targetColumn.append(targetHeading);for(const control of [document.getElementById('lol-range'),document.getElementById('lol-ring'),hold,trigger,aimPoint]){const label=control.closest('label');if(label)targetColumn.append(label)}const aimColumns=document.createElement('div');aimColumns.className='nova-aim-columns';const general=document.createElement('section');const generalHeading=document.createElement('h3');generalHeading.textContent='GENERAL';general.append(generalHeading);for(const child of [...aimPane.children])general.append(child);aimColumns.append(general,targetColumn);aimPane.append(aimColumns);
 const side=document.createElement('aside');side.className='nova-character-side';side.append(page.querySelector('h3'),page.querySelector('.nova-character'),chips);const sideNote=document.createElement('p');sideNote.textContent='Active controls';const figure=side.querySelector('svg');if(figure){figure.innerHTML='<defs><linearGradient id="nova-armor" x2="1" y2="1"><stop stop-color="#6478a4"/><stop offset="1" stop-color="#182238"/></linearGradient></defs><path d="M39 8 59 8 65 18 61 36 51 42 39 34 35 19Z" fill="url(#nova-armor)" stroke="#a0b4d9"/><path d="M38 20 62 20 59 26 41 26Z" fill="#090d16"/><path d="M33 43 50 38 67 43 71 72 63 92 38 92 29 72Z" fill="url(#nova-armor)" stroke="#7584a8"/><path d="M34 45 23 49 15 79 17 104 26 106 29 78 38 60M66 45 77 49 85 79 83 104 74 106 71 78 62 60" fill="url(#nova-armor)" stroke="#7584a8"/><path d="M39 91 48 96 47 118 43 142 30 142 34 116 34 98M61 91 52 96 53 118 57 142 70 142 66 116 66 98" fill="url(#nova-armor)" stroke="#7584a8"/><path d="M38 51H62V72H38ZM40 77H60M34 116H46M54 116H66" fill="#283b57" stroke="#889abc"/>'}side.append(sideNote);panel.querySelector('.lol-layout').append(side);button.hidden=true;page.hidden=true;
 nav.addEventListener('click',()=>{if(!reduced())content.animate([{opacity:.5,transform:'translateY(5px)'},{opacity:1,transform:'none'}],{duration:150})});
 let generation=0;function welcome(){const current=++generation;panel.querySelector('.nova-owner-welcome')?.remove();const overlay=document.createElement('div');overlay.className='nova-owner-welcome';const small=document.createElement('small');small.textContent='LOADING YOUR CONTROLS';const text=document.createElement('strong');overlay.append(small,text);panel.append(overlay);let name='';try{name=parent.novaHomeProfile?.name||parent.novaHomeProfile?.username||''}catch{}const message='Welcome'+(name?' '+name:'')+', Owner :}';let i=0;const finish=()=>{if(current!==generation)return;overlay.remove()};if(reduced()){text.textContent=message;setTimeout(finish,450);return}const type=()=>{if(current!==generation)return;text.textContent=message.slice(0,++i);if(i<message.length)setTimeout(type,28);else setTimeout(()=>{overlay.animate([{opacity:1},{opacity:0}],{duration:180}).finished.then(finish).catch(finish)},300)};type()}
 new MutationObserver(()=>{if(!panel.hidden){if(!reduced())panel.animate([{opacity:0,transform:'translateY(9px) scale(.98)'},{opacity:1,transform:'none'}],{duration:180,easing:'ease-out'});welcome()}else{generation++;panel.querySelector('.nova-owner-welcome')?.remove()}}).observe(panel,{attributes:true,attributeFilter:['hidden']});
 const hide=document.getElementById('lol-hide');hide.addEventListener('click',e=>{if(reduced())return;e.stopImmediatePropagation();panel.animate([{opacity:1,transform:'none'},{opacity:0,transform:'translateY(7px) scale(.98)'}],{duration:140}).finished.then(()=>{panel.hidden=true;document.getElementById('nova-lol-launch').hidden=false}).catch(()=>{})},{capture:true});welcome();
 }
})();
