(()=>{
 const watcher=new MutationObserver(()=>{const panel=document.getElementById('nova-lol-practice');if(panel){watcher.disconnect();decorate(panel)}});watcher.observe(document.documentElement,{childList:true,subtree:true});const existing=document.getElementById('nova-lol-practice');if(existing){watcher.disconnect();decorate(existing)}
 function decorate(panel){
 if(panel.dataset.novaMenuVersion==='2')return;panel.dataset.novaMenuVersion='2';
 const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
 const style=document.createElement('style');style.textContent=`
 #nova-lol-practice .lol-layout{grid-template-columns:minmax(0,1fr) 54px!important}#nova-lol-practice nav{order:2;padding:8px 5px}#nova-lol-practice nav button{font-size:20px;min-height:42px;text-align:center}#nova-lol-practice .lol-content{min-width:0}
 .nova-owner-welcome{position:absolute;inset:0;z-index:8;background:#0b0b0efa;display:grid;place-content:center;text-align:center;pointer-events:none;border-radius:inherit}.nova-owner-welcome small{color:#ef3340;letter-spacing:3px;font-size:10px}.nova-owner-welcome strong{font-size:24px;max-width:350px;overflow-wrap:anywhere;min-height:60px;margin-top:16px;color:#fff;text-shadow:0 0 22px #ef334077}
 .nova-character{height:160px;display:grid;place-items:center;background:radial-gradient(ellipse,#ef334023,transparent 65%);border:1px solid #ffffff12;border-radius:12px;margin:10px 0}.nova-character svg{height:138px;filter:drop-shadow(0 0 10px #ef334055)}.nova-tool-chips{display:flex;gap:6px;flex-wrap:wrap}.nova-tool-chips span{padding:5px 8px;border-radius:20px;background:#ef334020;border:1px solid #ef334044;color:#ffc5cc;font-size:10px}
 `;document.head.append(style);
 const nav=panel.querySelector('nav'),content=panel.querySelector('.lol-content');
 for(const [id,icon,label]of [['aim','◎','Aim'],['visual','◈','Visual'],['macro','⌘','Macro'],['settings','⚙','Settings']]){const b=document.getElementById('lol-tab-'+id);b.textContent=icon;b.title=label;b.setAttribute('aria-label',label)}
 const button=document.createElement('button');button.type='button';button.textContent='♙';button.title='Character';button.setAttribute('role','tab');button.setAttribute('aria-label','Character');button.setAttribute('aria-controls','nova-character-pane');button.setAttribute('aria-selected','false');nav.prepend(button);
 const page=document.createElement('div');page.id='nova-character-pane';page.setAttribute('role','tabpanel');page.hidden=true;page.innerHTML='<h3>Your loadout</h3><div class="nova-character"><svg viewBox="0 0 100 150" aria-label="Character preview" role="img"><circle cx="50" cy="24" r="17" fill="#25252c" stroke="#ef3340" stroke-width="2"/><path d="M31 47 Q50 38 69 47 L77 88 L64 92 L62 65 L61 100 L65 141 L52 141 L50 107 L47 141 L34 141 L39 100 L38 65 L36 92 L23 88Z" fill="#25252c" stroke="#ef3340" stroke-width="2"/></svg></div><div class="nova-tool-chips"></div><p>Your enabled tools. This preview represents your controls, not another player.</p>';
 content.append(page);const chips=page.querySelector('.nova-tool-chips');
 function update(){chips.replaceChildren();const enabled=[...panel.querySelectorAll('input[type=checkbox]:checked:not(:disabled)')].filter(x=>!['lol-compact','nova-potato'].includes(x.id)).map(x=>x.closest('label')?.textContent.trim()).filter(Boolean);if(document.getElementById('lol-aim').getAttribute('aria-pressed')==='true')enabled.unshift('Aim assist');if(document.getElementById('nova-potato')?.checked)enabled.push('Potato graphics');for(const text of enabled.length?enabled:['No tools enabled']){const chip=document.createElement('span');chip.textContent=text;chips.append(chip)}}
 panel.addEventListener('change',update);panel.addEventListener('click',()=>queueMicrotask(update));update();
 nav.addEventListener('click',e=>{if(e.target.closest('button')!==button){page.hidden=true;button.setAttribute('aria-selected','false')}});
 button.onclick=()=>{for(const pane of content.querySelectorAll('[role=tabpanel]'))pane.hidden=pane!==page;for(const b of nav.querySelectorAll('button'))b.setAttribute('aria-selected',String(b===button));update()};
 const settings=document.getElementById('lol-pane-settings'),label=document.createElement('label');label.className='check';const potato=document.createElement('input');potato.type='checkbox';potato.id='nova-potato';potato.checked=localStorage.getItem('nova_buildnow_potato')==='true';label.append(potato,' Potato graphics');const note=document.createElement('p');note.textContent='Lower rendering resolution for less GPU load. Apply restarts the game; FPS gains depend on your device.';const apply=document.createElement('button');apply.type='button';apply.textContent='Apply graphics & restart';apply.onclick=()=>{localStorage.setItem('nova_buildnow_potato',String(potato.checked));location.reload()};settings.append(label,note,apply);
 let generation=0;function welcome(){const current=++generation;panel.querySelector('.nova-owner-welcome')?.remove();const overlay=document.createElement('div');overlay.className='nova-owner-welcome';const small=document.createElement('small');small.textContent='NOVA · OWNER ACCESS';const text=document.createElement('strong');overlay.append(small,text);panel.append(overlay);let name='';try{name=parent.novaHomeProfile?.name||parent.novaHomeProfile?.username||''}catch{}const message='Welcome'+(name?' '+name:'')+', Owner :}';let i=0;const finish=()=>{if(current!==generation)return;overlay.remove()};if(reduced()){text.textContent=message;setTimeout(finish,450);return}const type=()=>{if(current!==generation)return;text.textContent=message.slice(0,++i);if(i<message.length)setTimeout(type,28);else setTimeout(()=>{overlay.animate([{opacity:1},{opacity:0}],{duration:180}).finished.then(finish).catch(finish)},300)};type()}
 new MutationObserver(()=>{if(!panel.hidden){if(!reduced())panel.animate([{opacity:0,transform:'translateY(9px) scale(.98)'},{opacity:1,transform:'none'}],{duration:180,easing:'ease-out'});welcome()}else{generation++;panel.querySelector('.nova-owner-welcome')?.remove()}}).observe(panel,{attributes:true,attributeFilter:['hidden']});
 const hide=document.getElementById('lol-hide');hide.addEventListener('click',e=>{if(reduced())return;e.stopImmediatePropagation();panel.animate([{opacity:1,transform:'none'},{opacity:0,transform:'translateY(7px) scale(.98)'}],{duration:140}).finished.then(()=>{panel.hidden=true;document.getElementById('nova-lol-launch').hidden=false}).catch(()=>{})},{capture:true});welcome();
 }
})();
