import {randomUUID} from 'node:crypto';
export async function manageServer(db,uid,b){
 if((await db.ref('novaChatV2/roles/'+uid).get()).val()!=='owner')throw Error('Only owners can manage server roles and channels.');
 const root='novaChatV2/',valid=v=>typeof v==='string'&&/^[a-zA-Z0-9_-]{1,80}$/.test(v),name=String(b.name||'').trim();
 if(b.kind==='category'){if(name.length<1||name.length>40)throw Error('Use a category name under 40 characters.');const id=b.id||randomUUID();if(!valid(id))throw Error('Invalid category.');await db.ref(root+'serverCategories/'+id).set({name,order:Number(b.order)||Date.now()});return {ok:true}}
 if(b.kind==='channel'){if(!/^[a-z0-9-]{1,40}$/.test(name))throw Error('Use lowercase letters, numbers and hyphens.');if(!valid(b.category)||!(await db.ref(root+'serverCategories/'+b.category).get()).exists())throw Error('Choose a category.');if(['welcome','general','announcements','updates','links','leaks','report','suggestions','owner-lounge','ai-assistance','community-links'].includes(name))throw Error('That channel name is reserved.');await db.ref(root+'serverChannels/'+name).set({name,category:b.category,staffOnly:b.staffOnly===true,readOnly:b.readOnly===true});return {ok:true}}
 if(b.kind==='role'){if(name.length<1||name.length>30)throw Error('Use a role name under 30 characters.');if(!/^#[0-9a-f]{6}$/i.test(b.from)||!/^#[0-9a-f]{6}$/i.test(b.to))throw Error('Choose two gradient colors.');const id=b.id||randomUUID();if(!valid(id)||['owner','admin','moderator','member','nitro'].includes(id))throw Error('Invalid custom role ID.');await db.ref(root+'customRoles/'+id).set({name,from:b.from,to:b.to,permission:['administrator','moderator','member'].includes(b.permission)?b.permission:'member',order:Number(b.order)||0});const members=(await db.ref(root+'memberRoles').get()).val()||{};for(const [person,roles]of Object.entries(members))if(roles[id])await refreshAccess(db,person);return {ok:true}}
 if(b.kind==='assign'){if(!valid(b.uid)||!(await db.ref('novaAccounts/'+b.uid).get()).exists()||!valid(b.role)||!(await db.ref(root+'customRoles/'+b.role).get()).exists())throw Error('Choose a user and a custom role.');await db.ref(root+'memberRoles/'+b.uid+'/'+b.role).set(b.enabled===false?null:true);await refreshAccess(db,b.uid);return {ok:true}}
 if(b.kind==='deleteChannel'){if(!valid(b.id))throw Error('Invalid channel.');await db.ref(root+'serverChannels/'+b.id).remove();return {ok:true}}
 throw Error('Choose a server setting.');
}
async function refreshAccess(db,uid){const definitions=(await db.ref('novaChatV2/customRoles').get()).val()||{},roles=(await db.ref('novaChatV2/memberRoles/'+uid).get()).val()||{};const permissions=Object.keys(roles).map(id=>definitions[id]?.permission);await db.ref('novaChatV2/staffAccess/'+uid).set({administrator:permissions.includes('administrator'),moderator:permissions.some(p=>['administrator','moderator'].includes(p))})}
