const {app,BrowserWindow,ipcMain,desktopCapturer,session,safeStorage,dialog,screen,globalShortcut,shell}=require('electron');
const fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process');
const {shouldEndSession}=require('./session-state.cjs');
const {allowCapturePermission}=require('./capture-permission.cjs');
const ORIGIN='https://novaoffical.vercel.app';let win,device,pair,active,helper,screenSource,enabled=false,lastProof=0;
const vault=()=>path.join(app.getPath('userData'),'device.enc');
async function request(action,body={},paired=true){const response=await fetch(ORIGIN+'/api/remote',{method:'POST',headers:{'Content-Type':'application/json',...(paired&&device?{Authorization:'Bearer device:'+device.id+':'+device.credential}:{})},body:JSON.stringify({action,...body}),signal:AbortSignal.timeout(10000)});const result=await response.json();if(!response.ok)throw Error(result.error||'Nova Remote is unavailable.');return result;}
function save(){if(!safeStorage.isEncryptionAvailable())throw Error('Windows credential encryption is unavailable.');fs.writeFileSync(vault(),safeStorage.encryptString(JSON.stringify(device)),{mode:0o600})}
function trusted(event){if(!win||event.sender!==win.webContents||event.senderFrame!==win.webContents.mainFrame||!event.senderFrame.url.startsWith('file://'))throw Error('Untrusted agent window.');}
function end(reason){const id=active;active=null;screenSource=null;if(helper){helper.stdin.write('{"type":"release"}\n');const child=helper;helper=null;setTimeout(()=>child.kill(),100)}win?.webContents.send('stopped',reason);if(id)request('disconnect',{session:id}).catch(()=>{});}
async function startInputHelper(id){
 const child=spawn('powershell.exe',['-NoLogo','-NoProfile','-Command',fs.readFileSync(path.join(__dirname,'input.ps1'),'utf8')],{windowsHide:true,stdio:['pipe','pipe','pipe']});helper=child;
 await new Promise((resolve,reject)=>{let ready=false,output='',errors='';const timer=setTimeout(()=>finish(Error('Windows input helper did not start.')),15000);
 function finish(error){clearTimeout(timer);if(error){if(helper===child)end(error.message);reject(error)}else{ready=true;resolve()}}
 child.stdout.on('data',chunk=>{output+=chunk.toString();if(!ready&&output.includes('NOVA_INPUT_READY'))finish()});
 child.stderr.on('data',chunk=>{errors=(errors+chunk.toString()).slice(0,1000)});
 child.on('error',error=>{if(!ready)finish(Error('Windows input helper: '+error.message));else if(active===id)end(error.message)});
 child.on('exit',code=>{const message='Windows input helper stopped'+(errors?': '+errors.trim():'. Exit '+code);if(!ready)finish(Error(message));else if(active===id&&helper===child)end(message)});
 });
}
const codeKeys={Escape:27,Tab:9,Enter:13,Backspace:8,Delete:46,Insert:45,Home:36,End:35,PageUp:33,PageDown:34,ArrowLeft:37,ArrowUp:38,ArrowRight:39,ArrowDown:40,Space:32,ShiftLeft:160,ShiftRight:161,ControlLeft:162,ControlRight:163,AltLeft:164,AltRight:165,MetaLeft:91,MetaRight:92,CapsLock:20,Minus:189,Equal:187,BracketLeft:219,BracketRight:221,Backslash:220,Semicolon:186,Quote:222,Comma:188,Period:190,Slash:191,Backquote:192};for(let i=0;i<26;i++)codeKeys['Key'+String.fromCharCode(65+i)]=65+i;for(let i=0;i<10;i++)codeKeys['Digit'+i]=48+i;for(let i=1;i<=12;i++)codeKeys['F'+i]=111+i;
app.whenReady().then(()=>{
 try{if(fs.existsSync(vault())&&safeStorage.isEncryptionAvailable())device=JSON.parse(safeStorage.decryptString(fs.readFileSync(vault())))}catch{}
 win=new BrowserWindow({width:570,height:720,minWidth:480,minHeight:640,title:'Nova Remote',icon:path.join(__dirname,'nova.png'),backgroundColor:'#101118',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});
 win.setMenuBarVisibility(false);win.loadFile('agent.html');win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());
 session.defaultSession.setPermissionCheckHandler((contents,permission,origin,details)=>contents===win.webContents&&!!active&&Date.now()-lastProof<10000&&allowCapturePermission(permission,details)&&details.isMainFrame!==false);
 session.defaultSession.setPermissionRequestHandler((contents,permission,callback,details)=>callback(contents===win.webContents&&!!active&&Date.now()-lastProof<10000&&allowCapturePermission(permission,details)&&details?.isMainFrame!==false));
 session.defaultSession.setDisplayMediaRequestHandler(async(req,callback)=>{
 const id=active;const allowed=()=>id&&active===id&&enabled&&Date.now()-lastProof<10000&&req.frame===win.webContents.mainFrame;
 if(!allowed()){callback({});return}
 try{const sources=await desktopCapturer.getSources({types:['screen'],thumbnailSize:{width:0,height:0}});const source=sources.find(s=>s.display_id===String(screen.getPrimaryDisplay().id));if(!allowed()||!source){callback({});return}screenSource=source;callback({video:source})}catch{callback({})}
 });
 ipcMain.handle('state',event=>{trusted(event);return {device:device?{id:device.id,name:device.name,profile:device.profile}:null,origin:ORIGIN,enabled}});
 ipcMain.handle('login',async(event,body)=>{trusted(event);const identifier=String(body.identifier||'').trim(),password=String(body.password||'');if(!identifier||!password)throw Error('Enter your email or username and password.');
 const firebaseKey='AIzaSyDV9MRbv7IDXjowddQoXAN1hJPlCGMyxR8';let endpoint='signInWithPassword',payload={email:identifier,password,returnSecureToken:true};
 if(!identifier.includes('@')){const response=await fetch(ORIGIN+'/api/account-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:identifier,password}),signal:AbortSignal.timeout(15000)});const result=await response.json();if(!response.ok)throw Error('Nova login ('+response.status+'): '+(result.error||'Login request failed.'));endpoint='signInWithCustomToken';payload={token:result.token,returnSecureToken:true};}
 const response=await fetch('https://identitytoolkit.googleapis.com/v1/accounts:'+endpoint+'?key='+firebaseKey,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(15000)}),result=await response.json();if(!response.ok)throw Error(result.error?.message==='TOO_MANY_ATTEMPTS_TRY_LATER'?'Too many login attempts. Try again later.':'Incorrect email or password.');
 const registered=await fetch(ORIGIN+'/api/remote',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+result.idToken},body:JSON.stringify({action:'registerDevice',name:String(body.name||'My Windows PC').slice(0,60)}),signal:AbortSignal.timeout(15000)});const next=await registered.json();if(!registered.ok)throw Error(next.error||'Could not register computer.');enabled=false;end();if(device)await request('disable').catch(()=>{});device=next;pair=null;save();return {id:device.id,name:device.name,profile:device.profile};
 });
 ipcMain.handle('browser-login',async(event,name)=>{trusted(event);if(device)throw Error('Log out before connecting a different account.');pair=await request('pairStart',{name:String(name||'My Windows PC').slice(0,60)},false);await shell.openExternal(ORIGIN+'/remote-login.html?code='+encodeURIComponent(pair.code));return true});
 ipcMain.handle('pair-start',async(event,name)=>{trusted(event);if(device)throw Error('Remove the existing computer before pairing again.');pair=await request('pairStart',{name:String(name).slice(0,60)},false);return {code:pair.code,expires:pair.expires}});
 ipcMain.handle('pair-poll',async event=>{trusted(event);if(!pair)return null;return request('pairPoll',{code:pair.code,token:pair.token},false)});
 ipcMain.handle('pair-finish',async event=>{trusted(event);if(!pair)throw Error('Start pairing first.');const result=await request('pairPoll',{code:pair.code,token:pair.token},false);if(!result.claimed)throw Error('Enter your code on Nova first.');const answer=await dialog.showMessageBox(win,{type:'question',buttons:['Cancel','Pair this computer'],defaultId:0,cancelId:0,message:'Pair with '+result.owner+'?',detail:'Confirm this is your Nova account. Remote access stays disabled until you enable it.'});if(answer.response!==1)return null;device=await request('pairFinish',{code:pair.code,token:pair.token},false);save();pair=null;return {id:device.id,name:device.name}});
 ipcMain.handle('enable',async event=>{trusted(event);if(!device)throw Error('Pair this computer first.');const result=await dialog.showMessageBox(win,{type:'question',buttons:['Cancel','Enable remote access'],defaultId:0,cancelId:0,message:'Enable Nova Remote on this computer?',detail:'Only your Nova account can request access. You must approve every session here. Keep this window open; closing it disables access.'});if(result.response!==1)return false;await request('enable');enabled=true;return true});
 ipcMain.handle('heartbeat',async event=>{trusted(event);if(!device)return null;const observedSession=active;try{const value=await request('heartbeat');if(value.device.enabled&&!enabled){await request('disable');value.device.enabled=false;value.session=null;}lastProof=Date.now();if(device.name!==value.device.name||JSON.stringify(device.profile)!==JSON.stringify(value.profile)){device.name=value.device.name;device.profile=value.profile;save()}if(shouldEndSession(value,observedSession,active)){enabled=value.device.enabled;end()}return value}catch(e){end();throw e}});
 ipcMain.handle('approve',async(event,id)=>{trusted(event);if(!enabled||active)throw Error('Remote access is unavailable.');const proof=await request('heartbeat');if(proof.session?.id!==id||proof.session.status!=='requested')throw Error('Connection request expired.');const result=await dialog.showMessageBox(win,{type:'warning',buttons:['Reject','Allow this session'],defaultId:0,cancelId:0,message:'Allow remote screen and keyboard control?',detail:'Requested by your Nova account from: '+proof.session.viewer+'\nOnly approve a connection you are making. Stop immediately with Ctrl+Shift+F12 or the Disconnect button.'});if(result.response!==1){await request('disconnect',{session:id});return false}await request('approve',{session:id});active=id;lastProof=Date.now();const sources=await desktopCapturer.getSources({types:['screen'],thumbnailSize:{width:0,height:0}});screenSource=sources.find(s=>s.display_id===String(screen.getPrimaryDisplay().id));if(!screenSource){end();throw Error('Primary display capture unavailable.');}await startInputHelper(id);if(active!==id)throw Error('Session ended during approval.');return true});
 ipcMain.handle('signal',async(event,body)=>{trusted(event);if(body.session!==active)throw Error('Session ended.');return request('signal',body)});
 ipcMain.handle('poll',async(event,body)=>{trusted(event);if(body.session!==active)throw Error('Session ended.');try{return await request('poll',body)}catch(e){end();throw e}});
 ipcMain.handle('stop',async event=>{trusted(event);end();return true});
 ipcMain.handle('disable',async event=>{trusted(event);enabled=false;end();if(device)await request('disable');return true});
 ipcMain.handle('forget',async event=>{trusted(event);enabled=false;end();if(device)await request('disable').catch(()=>{});device=null;if(fs.existsSync(vault()))fs.unlinkSync(vault());return true});
 let budget=0,at=Date.now();ipcMain.on('input',(event,message)=>{trusted(event);if(!active||message.session!==active||!enabled||Date.now()-lastProof>10000||!helper?.stdin.writable)return;if(Date.now()-at>=1000){budget=0;at=Date.now()}if(++budget>240)return;const p=message.packet;if(!p||!['move','relative','button','key','wheel','release'].includes(p.type))return;const value={type:p.type};if(['move','button'].includes(p.type)){if(!Number.isFinite(p.x)||!Number.isFinite(p.y))return;value.x=Math.max(0,Math.min(1,p.x));value.y=Math.max(0,Math.min(1,p.y));}if(p.type==='relative'){if(!Number.isFinite(p.dx)||!Number.isFinite(p.dy))return;value.dx=Math.round(Math.max(-2000,Math.min(2000,p.dx)));value.dy=Math.round(Math.max(-2000,Math.min(2000,p.dy)))}if(p.type==='button'){value.locked=p.locked===true;if(![0,1,2].includes(p.button)||typeof p.down!=='boolean')return;value.button=p.button;value.down=p.down}if(p.type==='key'){if(!codeKeys[p.code]||typeof p.down!=='boolean')return;value.vk=codeKeys[p.code];value.down=p.down}if(p.type==='wheel'){if(!Number.isFinite(p.delta))return;value.delta=Math.max(-120,Math.min(120,p.delta))}helper.stdin.write(JSON.stringify(value)+'\n');});
 setInterval(()=>{if(active&&Date.now()-lastProof>10000)end()},1000);globalShortcut.register('Control+Shift+F12',end);win.on('close',()=>{enabled=false;end();if(device)request('disable').catch(()=>{})});
});app.on('window-all-closed',()=>app.quit());app.on('will-quit',()=>{end();globalShortcut.unregisterAll()});
