const api=window.novaRemote,$=id=>document.getElementById(id);let device,enabled=false,requested,active,pc,stream,offset=0,pollTimer,busy=false,rejected,remoteCandidates=[],localCandidates=[],offerSent=false;
function message(text){$('notice').textContent=text}
function stop(){const old=pc;pc=null;old?.close();stream?.getTracks().forEach(t=>t.stop());stream=null;active=null;clearTimeout(pollTimer);$('active').hidden=true;$('request').hidden=true;}
api.onStop(reason=>{stop();if(reason)message(reason)});
async function refresh(){const state=await api.state();device=state.device;enabled=state.enabled;$('pairing').hidden=!!device;$('device').hidden=!device;if(device){$('device-name').textContent=device.name;$('device-id').textContent=device.id}$('enable').hidden=enabled;$('disable').hidden=!enabled;$('status').textContent=enabled?'Online · waiting for an approved session':'Remote access disabled';}
$('start').onclick=async()=>{try{const result=await api.pairStart($('name').value);$('pair-code').textContent=result.code;message('Pairing code expires in ten minutes.')}catch(e){message(e.message)}};
$('finish').onclick=async()=>{try{const result=await api.pairFinish();if(result){device=result;await refresh();message('Paired. Enable access when you want to connect.')}}catch(e){message(e.message)}};
$('enable').onclick=async()=>{try{await api.enable();await refresh()}catch(e){message(e.message)}};
$('disable').onclick=async()=>{stop();try{await api.disable();await refresh()}catch(e){message(e.message)}};
$('stop').onclick=()=>{stop();api.stop().catch(e=>message(e.message))};
$('forget').onclick=async()=>{if(!confirm('Forget this computer? Pair again to use it later.'))return;stop();await api.forget();await refresh()};
$('approve').onclick=async()=>{const id=requested;if(!id||active)return;$('approve').disabled=true;try{const allowed=await api.approve(id);if(!allowed){rejected=id;return}active=id;offset=0;remoteCandidates=[];localCandidates=[];offerSent=false;$('request').hidden=true;$('active').hidden=false;$('share').hidden=false;$('session-heading').textContent='Session approved';$('session-copy').textContent='Click Start screen sharing when you are ready. Your screen is not being shared yet.';message('Approved. Click Start screen sharing to begin.')}catch(e){fail(e)}finally{$('approve').disabled=false}};
$('share').onclick=async()=>{if(!active||pc)return;const id=active;$('share').disabled=true;try{stream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:60,max:60},width:{max:1920},height:{max:1080}},audio:false});$('session-heading').textContent='● Remote session active';$('session-copy').textContent='Your primary display is being shared. The connected browser can control your mouse and keyboard.';message('Sharing your desktop. Disconnect at any time.');stream.getVideoTracks()[0].onended=()=>{stop();api.stop()};const config=await api.poll({session:id,offset});pc=new RTCPeerConnection({iceServers:config.iceServers});for(const track of stream.getTracks()){track.contentHint='motion';const sender=pc.addTrack(track,stream);const params=sender.getParameters();if(params.encodings?.length){params.encodings[0].maxBitrate=12000000;params.encodings[0].maxFramerate=60;params.degradationPreference='maintain-framerate';await sender.setParameters(params)}}const channel=pc.createDataChannel('nova-input',{ordered:true});channel.onmessage=event=>{try{const packet=JSON.parse(event.data);api.input({session:id,packet})}catch{}};channel.onclose=()=>api.input({session:id,packet:{type:'release'}});pc.onicecandidate=e=>{if(e.candidate){const signal={type:'candidate',candidate:e.candidate.toJSON()};if(offerSent)api.signal({session:id,signal}).catch(fail);else localCandidates.push(signal)}};pc.onconnectionstatechange=()=>{if(['failed','disconnected','closed'].includes(pc?.connectionState))fail(Error('Connection ended.'))};await pc.setLocalDescription(await pc.createOffer());await api.signal({session:id,signal:{type:'offer',sdp:pc.localDescription.sdp}});offerSent=true;for(const signal of localCandidates.splice(0))await api.signal({session:id,signal});await poll();$('share').hidden=true;}catch(e){fail(e)}finally{$('share').disabled=false}};
function fail(e){message(e.message);stop();api.stop().catch(()=>{})}
async function poll(){if(!active||!pc)return;try{const result=await api.poll({session:active,offset});offset=result.offset;for(const signal of result.signals){if(signal.type==='answer'){await pc.setRemoteDescription(signal);for(const candidate of remoteCandidates.splice(0))await pc.addIceCandidate(candidate)}else if(signal.type==='candidate'){if(pc.remoteDescription)await pc.addIceCandidate(signal.candidate);else remoteCandidates.push(signal.candidate)}}pollTimer=setTimeout(poll,1500)}catch(e){fail(e)}}
setInterval(async()=>{if(busy)return;busy=true;try{if(!device){const pair=await api.pairPoll();$('finish').hidden=!pair?.claimed;if(pair?.claimed)message('Pairing requested by '+pair.owner+'. Confirm this is your account.')}else{const result=await api.heartbeat();enabled=result.device.enabled;$('status').textContent=enabled?'Online · access enabled':'Remote access disabled';$('enable').hidden=enabled;$('disable').hidden=!enabled;if(result.session?.status==='requested'&&result.session.id!==rejected&&!active){requested=result.session.id;$('viewer').textContent=result.session.viewer;$('request').hidden=false}else if(!active)$('request').hidden=true;}}catch(e){message(e.message);if(active)fail(e)}finally{busy=false}},2000);refresh().catch(e=>message(e.message));
