const api=window.novaRemote,$=id=>document.getElementById(id);let device,enabled=false,requested,active,pc,stream,offset=0,pollTimer,busy=false,rejected,remoteCandidates=[],localCandidates=[],offerSent=false,browserLoginPending=false;
function message(text){$('notice').textContent=text}
function stop(){const old=pc;pc=null;old?.close();stream?.getTracks().forEach(t=>t.stop());stream=null;active=null;clearTimeout(pollTimer);$('active').hidden=true;$('request').hidden=true;}
api.onStop(reason=>{stop();if(reason)message(reason)});
async function refresh(){const state=await api.state();device=state.device;profile(device?.profile);enabled=state.enabled;$('pairing').hidden=!!device;$('device').hidden=!device;if(device){$('device-name').textContent=device.name;$('device-id').textContent=device.id}$('enable').hidden=enabled;$('disable').hidden=!enabled;$('status').textContent=enabled?'Online · waiting for an approved session':'Remote access disabled';}
$('browser-login').onclick=async()=>{try{await api.browserLogin($('name').value);browserLoginPending=true;message('Complete login in your browser, then confirm your account in the Windows dialog.')}catch(e){message(e.message)}};
$('login-form').onsubmit=async event=>{event.preventDefault();$('login-submit').disabled=true;try{await api.login({identifier:$('identifier').value,password:$('password').value,name:$('name').value});$('password').value='';await refresh();message('Logged in. Enable remote access, then open Computer on Nova using this account.')}catch(e){$('password').value='';message(e.message)}finally{$('login-submit').disabled=false}};
function profile(value){$('account-profile').hidden=!value;if(!value)return;$('profile-name').textContent=value.name||'Nova player';const image=$('profile-photo');const photo=/^(https:|data:image\/)/.test(value.photo||'')?value.photo:'nova.png';if(image.getAttribute('src')!==photo)image.src=photo;image.onerror=()=>{image.onerror=null;image.src='nova.png'}}
$('enable').onclick=async()=>{try{await api.enable();await refresh()}catch(e){message(e.message)}};
$('disable').onclick=async()=>{stop();try{await api.disable();await refresh()}catch(e){message(e.message)}};
$('stop').onclick=()=>{stop();api.stop().catch(e=>message(e.message))};
$('forget').onclick=async()=>{if(!confirm('Log out and disable remote access on this computer?'))return;stop();await api.forget();await refresh()};
$('approve').onclick=async()=>{const id=requested;if(!id||active)return;$('approve').disabled=true;try{const allowed=await api.approve(id);if(!allowed){rejected=id;return}active=id;offset=0;remoteCandidates=[];localCandidates=[];offerSent=false;$('request').hidden=true;$('active').hidden=false;$('share').hidden=false;$('session-heading').textContent='Session approved';$('session-copy').textContent='Click Start screen sharing when you are ready. Your screen is not being shared yet.';message('Approved. Click Start screen sharing to begin.')}catch(e){fail(e)}finally{$('approve').disabled=false}};
$('share').onclick=async()=>{if(!active||pc)return;const id=active;$('share').disabled=true;try{stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});if(active!==id){stream.getTracks().forEach(t=>t.stop());stream=null;return}const videoTrack=stream.getVideoTracks()[0];try{await videoTrack.applyConstraints({width:{ideal:1920,max:1920},height:{ideal:1080,max:1080},frameRate:{ideal:60,max:60}})}catch{console.warn('Capture quality tuning unavailable; keeping the working display stream.')}$('session-heading').textContent='● Remote session active';$('session-copy').textContent='Your primary display is being shared. The connected browser can control your mouse and keyboard.';const settings=videoTrack.getSettings();message('Sharing '+settings.width+' × '+settings.height+' at '+Math.round(settings.frameRate||0)+' FPS. Target: 1920 × 1080 / 60 FPS. Disconnect at any time.');stream.getVideoTracks()[0].onended=()=>{stop();api.stop()};const config=await api.poll({session:id,offset});pc=new RTCPeerConnection({iceServers:config.iceServers});for(const track of stream.getTracks()){track.contentHint='motion';pc.addTrack(track,stream)}const channel=pc.createDataChannel('nova-input',{ordered:true});channel.onmessage=event=>{try{const packet=JSON.parse(event.data);api.input({session:id,packet})}catch{}};channel.onclose=()=>api.input({session:id,packet:{type:'release'}});pc.onicecandidate=e=>{if(e.candidate){const signal={type:'candidate',candidate:e.candidate.toJSON()};if(offerSent)api.signal({session:id,signal}).catch(fail);else localCandidates.push(signal)}};pc.onconnectionstatechange=()=>{if(['failed','disconnected','closed'].includes(pc?.connectionState))fail(Error('Connection ended.'))};await pc.setLocalDescription(await pc.createOffer());for(const sender of pc.getSenders()){if(sender.track?.kind!=='video')continue;const params=sender.getParameters();if(params.encodings?.length){params.encodings[0].maxBitrate=24000000;params.encodings[0].maxFramerate=60;params.encodings[0].scaleResolutionDownBy=1;params.degradationPreference='maintain-resolution';try{await sender.setParameters(params)}catch{delete params.degradationPreference;try{await sender.setParameters(params)}catch{console.warn('Optional encoder tuning unavailable; continuing with browser defaults.')}}}}await api.signal({session:id,signal:{type:'offer',sdp:pc.localDescription.sdp}});offerSent=true;for(const signal of localCandidates.splice(0))await api.signal({session:id,signal});await poll();$('share').hidden=true;}catch(e){if(active===id&&!pc&&!stream){message((e.name==='NotReadableError'||/Could not start video source/i.test(e.message))?'Windows could not start screen capture. Unlock your PC, close other screen-sharing apps, then click Start screen sharing again.':e.name==='NotAllowedError'?'Screen sharing was not allowed. Click Start screen sharing to try again.':e.message);$('share').hidden=false}else fail(e)}finally{$('share').disabled=false}};
function fail(e){message(e.message);stop();api.stop().catch(()=>{})}
async function poll(){if(!active||!pc)return;try{const result=await api.poll({session:active,offset});offset=result.offset;for(const signal of result.signals){if(signal.type==='answer'){await pc.setRemoteDescription(signal);for(const candidate of remoteCandidates.splice(0))await pc.addIceCandidate(candidate)}else if(signal.type==='candidate'){if(pc.remoteDescription)await pc.addIceCandidate(signal.candidate);else remoteCandidates.push(signal.candidate)}}pollTimer=setTimeout(poll,1500)}catch(e){fail(e)}}
setInterval(async()=>{if(busy)return;busy=true;try{if(!device){if(browserLoginPending){const result=await api.pairPoll();if(result?.claimed){browserLoginPending=false;const paired=await api.pairFinish();if(paired){await refresh();message('Logged in. Enable remote access to connect.')}}}return}else{const result=await api.heartbeat();profile(result.profile);enabled=result.device.enabled;$('status').textContent=enabled?'Online · access enabled':'Remote access disabled';$('enable').hidden=enabled;$('disable').hidden=!enabled;if(result.session?.status==='requested'&&result.session.id!==rejected&&!active){requested=result.session.id;$('viewer').textContent=result.session.viewer;$('request').hidden=false}else if(!active)$('request').hidden=true;}}catch(e){message(e.message);if(active)fail(e)}finally{busy=false}},2000);refresh().catch(e=>message(e.message));
