import {gameCatalog,publicStatuses,statusUpdate} from '../server/game-status.mjs';
import {withSharedBackend} from '../server/shared-backend.mjs';
import {syncChatProfile} from '../server/chat-profile-sync.mjs';
import {leaderboard} from '../server/leaderboard.mjs';
import {nitroThemes,validGradient} from '../Public/src/nitro-themes.js';
import {playerProgress,totalXP as total,levelForXP as level} from '../server/player-progress.mjs';
import {isProtectedOwner,restoreProtectedOwner,protectedOwnerIds} from '../server/protected-owners.mjs';
import {cloudPopular} from '../server/cloud-popular.mjs';
import {accountData} from '../server/account-data.mjs';
import {manageServer} from '../server/chat-server.mjs';
import {catalog,storeAction} from '../server/chat-store.mjs';
import {services} from '../server/voice-service.js';
import {createHash,randomUUID} from 'node:crypto';
const integer=(n,min,max)=>{n=Number(n);if(!Number.isSafeInteger(n)||n<min||n>max)throw Error('Number must be between '+min+' and '+max);return n};
const text=(s,max=4000)=>String(s||'').trim().slice(0,max),valid=s=>typeof s==='string'&&s.length&&s.length<129&&!/[.#$\[\]/]/.test(s);
const recordActivity=async(db,now)=>{const activity=(await db.ref('novaControl/activity').get()).val()||{};const count=Object.values(activity).filter(a=>now-a.at>=0&&now-a.at<60000).length;const day=new Date(now).toISOString().slice(0,10);await db.ref('novaControl/concurrency/'+day+'/'+Math.floor(now/60000)).set({at:now,count});return count};
const initial=()=>({xp:0,coins:0,challenges:[],resetAt:0,redeemed:{}});
export const createHandler=(service=services)=>async(req,res)=>{const reply=(code,data)=>{res.statusCode=code;res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))};if(req.method!=='POST')return reply(405,{error:'Use POST.'});
try{let backend;try{backend=await service(false)}catch(e){return reply(503,{error:e.message||'Nova server services are unavailable.'})}const {auth,db}=backend;let who;try{who=await auth.verifyIdToken((req.headers.authorization||'').replace(/^Bearer /,''),true)}catch{return reply(401,{error:'Sign in again.'})}if(who.firebase?.sign_in_provider==='anonymous')return reply(403,{error:'Sign in with a Nova account.'});const account=(await db.ref('novaAccounts/'+who.uid).get()).val();if(!account)return reply(403,{error:'Complete your account setup.'});let b=req.body;if(!b){let raw='';for await(const c of req){raw+=c;if(raw.length>250000)return reply(413,{error:'Request too large'})}b=JSON.parse(raw||'{}')}if(typeof b==='string')b=JSON.parse(b);const action=b.action;
const [baseRole,ban]=await Promise.all(['novaChatV2/roles/'+who.uid,'novaControl/siteBans/'+who.uid].map(p=>db.ref(p).get()));const protectedOwner=isProtectedOwner(who.uid);if(protectedOwner)await restoreProtectedOwner(db,who.uid,baseRole.val());const access=(await db.ref('novaChatV2/staffAccess/'+who.uid).get()).val()||{};const role={val:()=>(protectedOwner||baseRole.val()==='owner')?'owner':access.administrator?'admin':access.moderator?'moderator':baseRole.val()};const owner=protectedOwner||baseRole.val()==='owner';const now=Date.now();
const notifyAccountChange=(uid,subject,message)=>db.ref('novaChatV2/botMessages/'+uid).push({author:'nova-bot',kind:'account-update',subject,text:message,staffName:account.name||'Nova staff',staffPhoto:account.photo||'',staffRole:role.val()||'member',createdAt:now}).catch(()=>{});
if(action==='gameStatuses')return reply(200,{statuses:publicStatuses((await db.ref('novaControl/gameStatuses').get()).val()||{},await gameCatalog())});
if(action==='status')return reply(200,{owner,ban:protectedOwner?null:ban.val(),progress:(await db.ref('novaControl/progress/'+who.uid).get()).val()});
if(action==='appeal'){const reason=text(b.reason,2000);if(reason.length<10)throw Error('Explain your appeal in at least 10 characters.');await db.ref('novaControl/appeals/'+who.uid).set({uid:who.uid,name:account.name,reason,scope:b.scope==='chat'?'chat':'nova',at:now,status:'pending'});return reply(200,{ok:true})}
if(ban.exists()&&!protectedOwner)return reply(403,{error:'Your Nova access is suspended.'});
if(action==='syncChatProfile'){if(!protectedOwner&&(await db.ref('novaChatV2/bans/'+who.uid).get()).exists())return reply(403,{error:'Your Chat access is suspended.'});return reply(200,await syncChatProfile(db,who.uid,account,now));}
if(['leaderboard','leaderboardPulse','leaderboardProfile'].includes(action))return reply(200,await leaderboard(db,who.uid,action,b,now));
if(['cloudPick','cloudPopular'].includes(action))return reply(200,await cloudPopular(db,who.uid,action,b));
if(action==='accountData')return reply(200,await accountData(db,who.uid,b));
if(action==='giveAllCosmetics'){if(!owner)return reply(403,{error:'Only owners can grant shop items.'});if(!valid(b.uid)||!(await db.ref('novaAccounts/'+b.uid).get()).exists())throw Error('Choose a valid user.');const items=await catalog();await db.ref('novaControl/inventory/'+b.uid).transaction(inventory=>{inventory=inventory||{};for(const item of items)if(!inventory[item.id]?.count)inventory[item.id]={count:1,unlockedAt:now};return inventory});await db.ref('novaControl/audit').push({action:'giveAllCosmetics',actor:who.uid,target:b.uid,count:items.length,at:now});await notifyAccountChange(b.uid,'New cosmetics',(account.name||'Nova Owner')+' granted you the cosmetic collection. Open your inventory to see your items.');return reply(200,{ok:true,count:items.length})}
if(action==='serverManage')return reply(200,await manageServer(db,who.uid,b));
const progress=db.ref('novaControl/progress/'+who.uid);
if(['storeGamble','storeStatus','buyNitro','openCase','equipCosmetic','nitroAnimation','giftNitro','ackNitroGift','usernameFont','profileTheme','unequipCosmetic'].includes(action))return reply(200,await storeAction({db,uid:who.uid,account,action,b,now,initial}));
if(action==='redeem'){const code=text(b.code,64).toUpperCase();if(!/^[A-Z0-9#_-]{3,64}$/.test(code))throw Error('Enter a valid reward code.');const hash=createHash('sha256').update(code).digest('hex');const reward=(await db.ref('novaControl/codes/'+hash).get()).val();if(!reward||reward.disabled||reward.expiresAt<now)throw Error('This code is unavailable or expired.');const result=await progress.transaction(p=>{p=p||initial();p.redeemed=p.redeemed||{};if(p.redeemed[hash])return;p.redeemed[hash]=now;p.coins+=reward.coins;p.xp=Math.min(total(2000),Math.max(p.xp+reward.xp,total(Math.min(2000,level(p.xp)+reward.levels))));if(reward.multiplier>1){p.multiplier=reward.multiplier;p.multiplierUntil=now+reward.minutes*60000}return p});if(!result.committed)throw Error('You already redeemed this code.');return reply(200,{ok:true,progress:result.snapshot.val()})}
if(action==='pulse'){const config=(await db.ref('novaControl/events').get()).val()||{};const catalog=JSON.parse(await (await import('node:fs/promises')).readFile(new URL('../Public/library-games.json',import.meta.url),'utf8'));const game=catalog.find(g=>String(g.id)===String(b.game));const active=b.active===true&&!!game;const result=await progress.transaction(p=>{p=p||initial();const seconds=active&&p.lastActive&&now-p.lastAt<=35000?Math.min(20,(now-p.lastAt)/1000):0;if(!p.challenges?.length||(p.resetAt&&p.resetAt<=now)||p.challengeVersion!==(config.challengeVersion||0)){const pool=catalog.slice().sort((a,z)=>createHash('sha256').update(who.uid+String(Math.floor(now/5400000))+String(a.id)).digest('hex').localeCompare(createHash('sha256').update(who.uid+String(Math.floor(now/5400000))+String(z.id)).digest('hex')));p.challenges=pool.slice(0,4).map((g,i)=>({id:String(g.id),name:g.name,art:g.art,minutes:[10,15,20,30][i],reward:[100,200,300,500][i],seconds:0,claimed:false}));p.resetAt=0;p.challengeVersion=config.challengeVersion||0;p.challengeRewardsVersion=2}if(p.challengeRewardsVersion!==2){for(const c of p.challenges)if(!c.claimed){const i=[10,15,20,30].indexOf(c.minutes);if(i>=0)c.reward=[100,200,300,500][i]}p.challengeRewardsVersion=2}const multiplier=config.until>now?config.xpMultiplier||1:1,personal=p.multiplierUntil>now?p.multiplier||1:1;p.xp=Math.min(total(2000),p.xp+seconds*100/60*Math.max(multiplier,personal));for(const c of p.challenges)if(active&&c.id===String(b.game)&&!c.claimed){c.seconds=Math.min(c.minutes*60,c.seconds+seconds);if(c.seconds>=c.minutes*60){c.claimed=true;p.coins+=Math.round(c.reward*(config.until>now?config.coinMultiplier||1:1))}}if(p.challenges.every(c=>c.claimed)&&!p.resetAt)p.resetAt=now+5400000;p.activeSeconds=(p.activeSeconds||0)+seconds;p.lastAt=now;p.lastActive=active;return p});const day=new Date(now).toISOString().slice(0,10);await db.ref('novaControl/activity/'+who.uid).set({at:now,name:account.name,photo:account.photo||'',game:active?String(b.game):null});await db.ref('novaControl/days/'+day+'/'+who.uid).set(now);if(/^[a-f0-9-]{36}$/.test(b.session||''))await db.ref('novaControl/visits/'+day+'/'+who.uid+'/'+b.session).set(true);await recordActivity(db,now);return reply(200,{progress:result.snapshot.val()})}
if(action==='public'){const [updates,polls,events]=await Promise.all(['updates','polls','events'].map(k=>db.ref('novaControl/'+k).get()));return reply(200,{updates:updates.val()||{},polls:Object.fromEntries(Object.entries(polls.val()||{}).map(([id,p])=>[id,{title:p.title,text:p.text,authorName:p.authorName||'Nova Owner',authorPhoto:p.authorPhoto||'',options:p.options,closesAt:p.closesAt,choice:p.votes?.[who.uid]??null,counts:p.options.map((_,i)=>Object.values(p.votes||{}).filter(v=>v===i).length)}])),events:events.val()||{}})}
if(action==='vote'){if(!valid(b.id))throw Error('Invalid poll');const poll=(await db.ref('novaControl/polls/'+b.id).get()).val();if(!poll||poll.closesAt<=now)throw Error('Poll is closed.');const choice=integer(b.choice,0,poll.options.length-1);const vote=await db.ref('novaControl/polls/'+b.id+'/votes/'+who.uid).transaction(v=>v===null?choice:undefined);if(!vote.committed)throw Error('You already voted.');return reply(200,{ok:true})}
if(action==='liveFeed'){const live=(await db.ref('novaControl/live').get()).val();if(!live||live.expiresAt<=now)return reply(200,{live:null});const {votes:legacyVotes,...safe}=live;const votes=(await db.ref('novaControl/liveVotes/'+live.id).get()).val()||legacyVotes||{};return reply(200,{live:{...safe,counts:(live.options||[]).map((_,i)=>Object.values(votes||{}).filter(v=>v===i).length),choice:votes?.[who.uid]??null}})}
if(action==='liveVote'){if(!valid(b.id))throw Error('Invalid poll.');const live=(await db.ref('novaControl/live').get()).val();if(!live||live.id!==b.id||live.expiresAt<=Date.now())throw Error('This poll has ended.');if(!Array.isArray(live.options))throw Error('This announcement is not a poll.');const choice=integer(b.choice,0,live.options.length-1);if(live.votes?.[who.uid]!=null)return reply(200,{ok:true,alreadyVoted:true});const result=await db.ref('novaControl/liveVotes/'+b.id+'/'+who.uid).transaction(v=>v===null?choice:undefined);return reply(200,{ok:true,alreadyVoted:!result.committed})}
if(action==='profileShowcase'){const {validateShowcase}=await import('../server/profile-showcase.mjs');const games=await validateShowcase(b.games);await db.ref('novaChatV2/profiles/'+who.uid).update({showcase:games});return reply(200,{ok:true,games})}
if(action==='profileUpdate'){const name=text(b.name,24),bio=text(b.bio,240),photo=text(b.photo,100000),banner=text(b.banner,100000);if(!/^[a-zA-Z0-9_ -]{2,24}$/.test(name))throw Error('Use 2–24 letters, numbers, spaces, underscores or hyphens.');for(const url of [photo,banner])if(url&&!/^https:\/\/|^data:image\/(png|jpeg|webp|gif);base64,/.test(url))throw Error('Use an HTTPS image or GIF.');if(!['online','offline','dnd'].includes(b.status))throw Error('Invalid status.');await db.ref('novaAccounts/'+who.uid).update({name,photo,updatedAt:now});await db.ref('novaChatV2/profiles/'+who.uid).update({name,photo,bio,banner,status:b.status,novaTag:b.novaTag===true});return reply(200,{ok:true})}
if(action==='themeStatus'){const premium=(await db.ref('novaControl/nitro/'+who.uid).get()).val(),saved=(await db.ref('novaChatV2/preferences/'+who.uid).get()).val()||{},nitro=premium===true||premium?.until>now;const theme=saved.theme||'black';return reply(200,{theme:!nitro&&(nitroThemes[theme]||theme==='custom')?'black':theme,gradient:saved.gradient||null,nitro})}
if(action==='chatTheme'){const premium=(await db.ref('novaControl/nitro/'+who.uid).get()).val();const allowed=['dark','black','light',...(premium===true||premium?.until>now?[...Object.keys(nitroThemes),'custom']:[])];if(!allowed.includes(b.theme))throw Error('This theme requires Nova Nitro.');if(b.theme==='custom'&&!validGradient(b.gradient))throw Error('Choose three valid colors and an angle between 0 and 360.');await db.ref('novaChatV2/preferences/'+who.uid).update({theme:b.theme,...(b.theme==='custom'?{gradient:b.gradient}:{})});return reply(200,{ok:true})}
if(action==='nameColorRole'){const chosen=String(b.role||'');if(chosen){const base=(await db.ref('novaChatV2/roles/'+who.uid).get()).val()||'member',assigned=(await db.ref('novaChatV2/memberRoles/'+who.uid).get()).val()||{},custom=(await db.ref('novaChatV2/customRoles/'+chosen).get()).val(),premium=(await db.ref('novaControl/nitro/'+who.uid).get()).val();if(chosen!==base&&!(assigned[chosen]&&custom)&&!(chosen==='nitro'&&(premium===true||premium?.until>now)))throw Error('Choose a role you already have.');}await db.ref('novaChatV2/profiles/'+who.uid+'/nameColorRole').set(chosen||null);return reply(200,{ok:true})}
if(action==='staffCommand'){if(!['owner','admin','moderator'].includes(role.val()))return reply(403,{error:'Staff only.'});if(!valid(b.uid)||!(await db.ref('novaAccounts/'+b.uid).get()).exists())throw Error('Choose a valid user.');if((isProtectedOwner(b.uid)||(await db.ref('novaChatV2/roles/'+b.uid).get()).val()==='owner')&&b.command!=='status')throw Error('Owner accounts are protected.');if(b.command==='status')return reply(200,{chatBanned:(await db.ref('novaChatV2/bans/'+b.uid).get()).exists(),novaBanned:(await db.ref('novaControl/siteBans/'+b.uid).get()).exists(),muteUntil:(await db.ref('novaChatV2/mutes/'+b.uid).get()).val()||0});if(b.scope==='nova'||b.command==='give'){if(!owner)return reply(403,{error:'Only owners can ban from Nova or grant rewards.'})}if(b.command==='ban'||b.command==='unban'){await db.ref(b.scope==='nova'?'novaControl/siteBans/'+b.uid:'novaChatV2/bans/'+b.uid).set(b.command==='unban'?null:b.scope==='nova'?{reason:text(b.reason,500)||'Owner moderation',at:now}:true)}else if(b.command==='mute'){await db.ref('novaChatV2/mutes/'+b.uid).set(now+integer(b.minutes,1,10080)*60000)}else if(b.command==='unmute'){await db.ref('novaChatV2/mutes/'+b.uid).remove()}else if(b.command==='give'){const amount=integer(b.amount,1,b.reward==='coins'?1000000:10000000);if(!['xp','coins','levels'].includes(b.reward))throw Error('Choose xp, coins or levels.');await db.ref('novaControl/progress/'+b.uid).transaction(p=>{p=p||initial();if(b.reward==='coins')p.coins+=amount;else p.xp=Math.min(total(2000),b.reward==='levels'?total(Math.min(2000,level(p.xp)+amount)):p.xp+amount);return p})}else throw Error('Unknown command.');await db.ref('novaControl/audit').push({action:'staffCommand',command:b.command,actor:who.uid,target:b.uid,at:now});if(b.command==='give')await notifyAccountChange(b.uid,'Nova reward received',(account.name||'Nova Owner')+' granted you '+Number(b.amount).toLocaleString()+' '+b.reward+'.');return reply(200,{ok:true})}
if(action==='leaveGroup'){if(!valid(b.id))throw Error('Choose a valid group.');const group=(await db.ref('novaChatV2/groups/'+b.id).get()).val();if(!group?.members?.[who.uid])throw Error('You are not a member of this group.');await db.ref('novaChatV2/groups/'+b.id).transaction(g=>{if(!g?.members?.[who.uid])return;delete g.members[who.uid];const ids=Object.keys(g.members);if(!ids.length)return null;if(g.owner===who.uid)g.owner=ids[0];return g});await db.ref('novaChatV2/userGroups/'+who.uid+'/'+b.id).remove();return reply(200,{ok:true})}
if(action==='staffReply'||action==='reply'||action==='deleteFeedback'){if(!['owner','admin','moderator'].includes(role.val()))return reply(403,{error:'Staff only.'});if(!valid(b.uid)||!valid(b.id))throw Error('Invalid submission.');const ticket=(await db.ref('novaChatV2/feedback/'+b.uid+'/'+b.id).get()).val();if(!ticket)throw Error('Submission not found.');if(action==='deleteFeedback'){await db.ref('novaChatV2/feedback/'+b.uid+'/'+b.id).remove();await db.ref('novaChatV2/feedbackReplies/'+b.uid+'/'+b.id).remove()}else{const message=text(b.text);if(!message)throw Error('Enter a reply.');const id=randomUUID();await db.ref('novaChatV2/feedbackReplies/'+b.uid+'/'+b.id+'/'+id).set({author:who.uid,text:message,createdAt:now});await db.ref('novaChatV2/botMessages/'+b.uid+'/'+id).set({author:'nova-bot',text:message,subject:ticket.subject,kind:ticket.kind,staffName:account.name,staffRole:role.val(),createdAt:now})}await db.ref('novaControl/audit').push({actor:who.uid,action,target:b.uid,at:now});return reply(200,{ok:true})}
if(!owner)return reply(403,{error:'Only owners can use this panel.'});
const audit=(details)=>db.ref('novaControl/audit').push({actor:who.uid,action,at:now,...details});
if(['userInventory','setPlayerProgress','removeUserItem'].includes(action)){
 if(!valid(b.uid)||!(await db.ref('novaAccounts/'+b.uid).get()).exists())throw Error('Choose a valid account.');
 if(action==='setPlayerProgress'){
  const coins=integer(b.coins,0,1000000000),chosenLevel=integer(b.level,1,2000);
  const result=await db.ref('novaControl/progress/'+b.uid).transaction(p=>({...initial(),...p,coins,xp:total(chosenLevel)}));
  await audit({target:b.uid,coins,level:chosenLevel});await notifyAccountChange(b.uid,'Your progress was updated',(account.name||'Nova Owner')+' set your balance to '+coins.toLocaleString()+' Nova Coins and level '+chosenLevel+'.');
  return reply(200,{ok:true,...playerProgress(result.snapshot.val())});
 }
 const items=await catalog(),inventoryRef=db.ref('novaControl/inventory/'+b.uid);
 if(action==='removeUserItem'){
  if(b.all!==true&&!valid(b.id))throw Error('Choose a valid item.');
  let removed=[];const result=await inventoryRef.transaction(inventory=>{inventory=inventory||{};removed=b.all===true?Object.keys(inventory):Object.hasOwn(inventory,b.id)?[b.id]:[];for(const id of removed)delete inventory[id];return Object.keys(inventory).length?inventory:null});
  if(!result.committed||!removed.length)throw Error('No matching items remain in this inventory.');
  await db.ref('novaChatV2/profiles/'+b.uid).transaction(p=>{p=p||{};for(const field of ['decoration','effect','chatBanner','banner'])if(removed.includes(p[field]))delete p[field];return p});
  await audit({target:b.uid,removed,all:b.all===true});await notifyAccountChange(b.uid,'Your inventory was updated',(account.name||'Nova Owner')+' removed '+removed.length+' profile item'+(removed.length===1?'':'s')+' from your inventory.');
 }
 const [inventory,profile,progress]=await Promise.all([inventoryRef.get(),db.ref('novaChatV2/profiles/'+b.uid).get(),db.ref('novaControl/progress/'+b.uid).get()]);
 const equipped=profile.val()||{};
 return reply(200,{...playerProgress(progress.val()),items:Object.entries(inventory.val()||{}).map(([id,owned])=>{const item=items.find(i=>i.id===id);return {id,name:item?.name||id,kind:item?.kind||'Unknown',src:item?.src||'',rarity:item?.rarity||'',count:owned?.count||1,equipped:['decoration','effect','chatBanner','banner'].some(field=>equipped[field]===id)}})});
}
if(action==='setGameStatus'){const {id,value}=await statusUpdate(b,now);await db.ref('novaControl/gameStatuses/'+id).set(value);await audit({target:id,status:value.status});return reply(200,{ok:true,record:value})}
if(action==='livePublish'){const message=text(b.text,500);if(!message)throw Error('Enter a message or poll question.');const options=b.kind==='poll'?String(b.options||'').split('\n').map(v=>text(v,80)).filter(Boolean):null;if(options&&(options.length<2||options.length>6))throw Error('Enter 2–6 poll options.');const live={id:randomUUID(),text:message,name:account.name||'Nova Owner',photo:account.photo||'',author:who.uid,at:now,expiresAt:now+integer(b.seconds||15,15,600)*1000,...(options?{options}:{})};await db.ref('novaControl/live').set(live);await audit({kind:b.kind});return reply(200,{ok:true})}
if(action==='liveEnd'){await db.ref('novaControl/live').remove();await audit({});return reply(200,{ok:true})}
if(action==='dashboard'){await recordActivity(db,now);const timelineDays=Array.from({length:3},(_,i)=>new Date(now-i*86400000).toISOString().slice(0,10));const timeline=Object.assign({},...(await Promise.all(timelineDays.map(d=>db.ref('novaControl/concurrency/'+d).get()))).map(s=>s.val()||{}));const names=['activity','days','visits','progress','siteBans','appeals','events','updates','polls','audit'];const snaps=await Promise.all(names.map(n=>db.ref('novaControl/'+n).get()));const data=Object.fromEntries(names.map((n,i)=>[n,snaps[i].val()||{}]));const [users,roles,bans,feedback]=await Promise.all(['novaAccounts','novaChatV2/roles','novaChatV2/bans','novaChatV2/feedback'].map(n=>db.ref(n).get()));return reply(200,{...data,timeline,protectedOwnerIds,canManageOwners:protectedOwner,users:Object.entries(users.val()||{}).map(([uid,u])=>({uid,name:u.name,photo:u.photo,createdAt:u.createdAt,...playerProgress(data.progress[uid])})),roles:roles.val()||{},chatBans:bans.val()||{},feedback:feedback.val()||{}})}
if(action==='logs'){const channel=text(b.channel,50);if(!['general','announcements','updates','leaks','links','welcome','community-links','owner-lounge','ai-assistance'].includes(channel))throw Error('Choose a server channel.');return reply(200,{messages:(await db.ref('novaChatV2/channels/'+channel+'/messages').orderByChild('createdAt').limitToLast(100).get()).val()||{}})}
if(action==='user'){if(!valid(b.uid)||!(await db.ref('novaAccounts/'+b.uid).get()).exists())throw Error('Choose a valid account.');const targetRole=(await db.ref('novaChatV2/roles/'+b.uid).get()).val();if(['role','chatBan','siteBan','mute'].includes(b.kind)&&(isProtectedOwner(b.uid)||(targetRole==='owner'&&!(b.kind==='role'&&protectedOwner))))throw Error('Owner accounts are protected.');if(b.kind==='role'){if(!['member','moderator','admin','owner'].includes(b.value))throw Error('Invalid role');await db.ref('novaChatV2/roles/'+b.uid).set(b.value)}else if(b.kind==='chatBan')await db.ref('novaChatV2/bans/'+b.uid).set(b.value?true:null);else if(b.kind==='siteBan')await db.ref('novaControl/siteBans/'+b.uid).set(b.value?{reason:text(b.reason,500)||'Account suspended by owner',at:now}:null);else if(b.kind==='mute')await db.ref('novaChatV2/mutes/'+b.uid).set(b.minutes?now+integer(b.minutes,1,10080)*60000:null);else if(b.kind==='nitro'){await db.ref('novaControl/nitro/'+b.uid).set({until:now+integer(b.days,1,365)*86400000})}else if(b.kind==='reward'){const coins=integer(b.coins||0,0,1000000),xp=integer(b.xp||0,0,10000000),levels=integer(b.levels||0,0,1999);await db.ref('novaControl/progress/'+b.uid).transaction(p=>{p=p||initial();p.coins+=coins;p.xp=Math.min(total(2000),Math.max(p.xp+xp,total(Math.min(2000,level(p.xp)+levels))));return p})}else throw Error('Unknown user action');await audit({target:b.uid,kind:b.kind,...(b.kind==='role'?{role:b.value}:{})});if(['role','reward','nitro'].includes(b.kind))await notifyAccountChange(b.uid,b.kind==='role'?'Your role was updated':b.kind==='nitro'?'Nova Nitro added':'Nova rewards added',b.kind==='role'?'Your Nova role is now '+b.value+'.':b.kind==='nitro'?(account.name||'Nova Owner')+' granted you '+b.days+' days of Nitro.':(account.name||'Nova Owner')+' granted you '+[[Number(b.coins||0),'Nova Coins'],[Number(b.xp||0),'XP'],[Number(b.levels||0),'levels']].filter(([amount])=>amount>0).map(([amount,label])=>amount.toLocaleString()+' '+label).join(', ')+'. Your balance and level will update shortly.');return reply(200,{ok:true})}
if(action==='event'){const xpMultiplier=integer(b.xpMultiplier,1,50),coinMultiplier=integer(b.coinMultiplier,1,10),minutes=integer(b.minutes,1,1440);await db.ref('novaControl/events').update({id:randomUUID(),title:text(b.title,80)||'Community boost',author:who.uid,authorName:account.name||'Nova Owner',authorPhoto:account.photo||'',startedAt:now,xpMultiplier,coinMultiplier,until:now+minutes*60000});await audit({title:text(b.title,80)||'Community boost',xpMultiplier,coinMultiplier,minutes});return reply(200,{ok:true})}
if(action==='endEvent'){await db.ref('novaControl/events').update({until:now});await audit({});return reply(200,{ok:true})}
if(action==='resetChallenges'){await db.ref('novaControl/events/challengeVersion').transaction(n=>(n||0)+1);await audit({});return reply(200,{ok:true})}
if(action==='giftOnline'){const amount=integer(b.coins,1,100000),people=(await db.ref('novaControl/activity').get()).val()||{};const ids=Object.keys(people).filter(id=>now-people[id].at<60000);await Promise.all(ids.map(async id=>{await db.ref('novaControl/progress/'+id).transaction(p=>{p=p||initial();p.coins+=amount;return p});await notifyAccountChange(id,'Nova coin gift',(account.name||'Nova Owner')+' granted you '+amount.toLocaleString()+' Nova Coins in an online community gift.');}));await audit({amount,recipients:ids.length});return reply(200,{ok:true,count:ids.length})}
if(action==='code'){const code=text(b.code,64).toUpperCase();if(!/^[A-Z0-9#_-]{3,64}$/.test(code))throw Error('Use 3–64 letters, numbers, #, underscores or hyphens.');const hash=createHash('sha256').update(code).digest('hex');const reward={coins:integer(b.coins||0,0,1000000),xp:integer(b.xp||0,0,10000000),levels:integer(b.levels||0,0,1999),multiplier:integer(b.multiplier||1,1,50),minutes:integer(b.minutes||60,1,1440),expiresAt:now+integer(b.days||30,1,365)*86400000};const r=await db.ref('novaControl/codes/'+hash).transaction(v=>v?undefined:reward);if(!r.committed)throw Error('That code already exists.');await audit({code});return reply(200,{ok:true})}
if(action==='publish'){const title=text(b.title,100),body=text(b.text);if(!title||!body)throw Error('Enter a title and text.');if(b.kind==='poll'){const options=String(b.options||'').split('\n').map(v=>text(v,100)).filter(Boolean);if(options.length<2||options.length>6)throw Error('Enter 2–6 options on separate lines.');await db.ref('novaControl/polls').push({title,text:body,author:who.uid,authorName:account.name||'Nova Owner',authorPhoto:account.photo||'',options,at:now,closesAt:now+integer(b.hours||24,1,168)*3600000})}else if(b.kind==='update'){await db.ref('novaControl/updates').push({title,text:body,at:now,author:account.name,authorUid:who.uid,authorRole:role.val()})}else{await db.ref('novaChatV2/channels/announcements/messages').push({author:who.uid,text:title+'\n'+body,createdAt:now})}await audit({kind:b.kind,title});return reply(200,{ok:true})}
if(action==='reply'){if(!valid(b.uid)||!valid(b.id))throw Error('Invalid report');const message=text(b.text);if(!message)throw Error('Enter a reply.');await db.ref('novaChatV2/feedbackReplies/'+b.uid+'/'+b.id).push({author:who.uid,text:message,createdAt:now});await audit({target:b.uid});return reply(200,{ok:true})}
if(action==='appealReview'){if(!valid(b.uid))throw Error('Invalid account');const appeal=(await db.ref('novaControl/appeals/'+b.uid).get()).val();if(!appeal)throw Error('Appeal not found');if(b.approve)await db.ref(appeal.scope==='chat'?'novaChatV2/bans/'+b.uid:'novaControl/siteBans/'+b.uid).remove();await db.ref('novaControl/appeals/'+b.uid).update({status:b.approve?'approved':'declined',reviewedAt:now});await audit({target:b.uid});return reply(200,{ok:true})}
return reply(400,{error:'Unknown action.'});
}catch(e){return reply(400,{error:e.message||'Request failed.'})}};
export default withSharedBackend('owner-control',createHandler());
