import {services} from '../server/voice-service.js';
import {createHash,randomUUID} from 'node:crypto';
const total=l=>500*(l-1)+125*(l-1)*(l-2),level=x=>{let l=1;while(l<2000&&x>=total(l+1))l++;return l};
const integer=(n,min,max)=>{n=Number(n);if(!Number.isSafeInteger(n)||n<min||n>max)throw Error('Number must be between '+min+' and '+max);return n};
const text=(s,max=4000)=>String(s||'').trim().slice(0,max),valid=s=>typeof s==='string'&&s.length&&s.length<129&&!/[.#$\[\]/]/.test(s);
const initial=()=>({xp:0,coins:0,challenges:[],resetAt:0,redeemed:{}});
export const createHandler=(service=services)=>async(req,res)=>{const reply=(code,data)=>{res.statusCode=code;res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))};if(req.method!=='POST')return reply(405,{error:'Use POST.'});
try{const {auth,db}=await service(false);let who;try{who=await auth.verifyIdToken((req.headers.authorization||'').replace(/^Bearer /,''),true)}catch{return reply(401,{error:'Sign in again.'})}if(who.firebase?.sign_in_provider==='anonymous')return reply(403,{error:'Sign in with a Nova account.'});const account=(await db.ref('novaAccounts/'+who.uid).get()).val();if(!account)return reply(403,{error:'Complete your account setup.'});let b=req.body;if(!b){let raw='';for await(const c of req){raw+=c;if(raw.length>20000)return reply(413,{error:'Request too large'})}b=JSON.parse(raw||'{}')}if(typeof b==='string')b=JSON.parse(b);const action=b.action;
const [role,ban]=await Promise.all(['novaChatV2/roles/'+who.uid,'novaControl/siteBans/'+who.uid].map(p=>db.ref(p).get()));const owner=role.val()==='owner';const now=Date.now();
if(action==='status')return reply(200,{owner,ban:ban.val(),progress:(await db.ref('novaControl/progress/'+who.uid).get()).val()});
if(action==='appeal'){const reason=text(b.reason,2000);if(reason.length<10)throw Error('Explain your appeal in at least 10 characters.');await db.ref('novaControl/appeals/'+who.uid).set({uid:who.uid,name:account.name,reason,scope:b.scope==='chat'?'chat':'nova',at:now,status:'pending'});return reply(200,{ok:true})}
if(ban.exists())return reply(403,{error:'Your Nova access is suspended.'});
const progress=db.ref('novaControl/progress/'+who.uid);
if(action==='redeem'){const code=text(b.code,64).toUpperCase();if(!/^[A-Z0-9-]{3,64}$/.test(code))throw Error('Enter a valid reward code.');const hash=createHash('sha256').update(code).digest('hex');const reward=(await db.ref('novaControl/codes/'+hash).get()).val();if(!reward||reward.disabled||reward.expiresAt<now)throw Error('This code is unavailable or expired.');const result=await progress.transaction(p=>{p=p||initial();p.redeemed=p.redeemed||{};if(p.redeemed[hash])return;p.redeemed[hash]=now;p.coins+=reward.coins;p.xp=Math.min(total(2000),Math.max(p.xp+reward.xp,total(Math.min(2000,level(p.xp)+reward.levels))));if(reward.multiplier>1){p.multiplier=reward.multiplier;p.multiplierUntil=now+reward.minutes*60000}return p});if(!result.committed)throw Error('You already redeemed this code.');return reply(200,{ok:true,progress:result.snapshot.val()})}
if(action==='pulse'){const config=(await db.ref('novaControl/events').get()).val()||{};const catalog=JSON.parse(await (await import('node:fs/promises')).readFile(new URL('../Public/library-games.json',import.meta.url),'utf8'));const game=catalog.find(g=>String(g.id)===String(b.game));const active=b.active===true&&!!game;const result=await progress.transaction(p=>{p=p||initial();const seconds=active&&p.lastActive&&now-p.lastAt<=35000?Math.min(20,(now-p.lastAt)/1000):0;if(!p.challenges?.length||(p.resetAt&&p.resetAt<=now)||p.challengeVersion!==(config.challengeVersion||0)){const pool=catalog.slice().sort((a,z)=>createHash('sha256').update(who.uid+String(Math.floor(now/5400000))+String(a.id)).digest('hex').localeCompare(createHash('sha256').update(who.uid+String(Math.floor(now/5400000))+String(z.id)).digest('hex')));p.challenges=pool.slice(0,4).map((g,i)=>({id:String(g.id),name:g.name,art:g.art,minutes:[10,15,20,30][i],reward:[50,100,150,250][i],seconds:0,claimed:false}));p.resetAt=0;p.challengeVersion=config.challengeVersion||0}const multiplier=config.until>now?config.xpMultiplier||1:1,personal=p.multiplierUntil>now?p.multiplier||1:1;p.xp=Math.min(total(2000),p.xp+seconds*100/60*Math.max(multiplier,personal));for(const c of p.challenges)if(active&&c.id===String(b.game)&&!c.claimed){c.seconds=Math.min(c.minutes*60,c.seconds+seconds);if(c.seconds>=c.minutes*60){c.claimed=true;p.coins+=Math.round(c.reward*(config.until>now?config.coinMultiplier||1:1))}}if(p.challenges.every(c=>c.claimed)&&!p.resetAt)p.resetAt=now+5400000;p.activeSeconds=(p.activeSeconds||0)+seconds;p.lastAt=now;p.lastActive=active;return p});const day=new Date(now).toISOString().slice(0,10);await db.ref('novaControl/activity/'+who.uid).set({at:now,name:account.name,photo:account.photo||'',game:active?String(b.game):null});await db.ref('novaControl/days/'+day+'/'+who.uid).set(now);if(/^[a-f0-9-]{36}$/.test(b.session||''))await db.ref('novaControl/visits/'+day+'/'+who.uid+'/'+b.session).set(true);return reply(200,{progress:result.snapshot.val()})}
if(action==='public'){const [updates,polls,events]=await Promise.all(['updates','polls','events'].map(k=>db.ref('novaControl/'+k).get()));return reply(200,{updates:updates.val()||{},polls:Object.fromEntries(Object.entries(polls.val()||{}).map(([id,p])=>[id,{title:p.title,text:p.text,options:p.options,closesAt:p.closesAt,counts:p.options.map((_,i)=>Object.values(p.votes||{}).filter(v=>v===i).length)}])),events:events.val()||{}})}
if(action==='vote'){if(!valid(b.id))throw Error('Invalid poll');const poll=(await db.ref('novaControl/polls/'+b.id).get()).val();if(!poll||poll.closesAt<now)throw Error('Poll is closed.');const choice=integer(b.choice,0,poll.options.length-1);const vote=await db.ref('novaControl/polls/'+b.id+'/votes/'+who.uid).transaction(v=>v===null?choice:undefined);if(!vote.committed)throw Error('You already voted.');return reply(200,{ok:true})}
if(action==='liveFeed'){const live=(await db.ref('novaControl/live').get()).val();if(!live||live.expiresAt<=now)return reply(200,{live:null});const {votes,...safe}=live;return reply(200,{live:{...safe,counts:(live.options||[]).map((_,i)=>Object.values(votes||{}).filter(v=>v===i).length),choice:votes?.[who.uid]??null}})}
if(action==='liveVote'){const choice=integer(b.choice,0,5);const result=await db.ref('novaControl/live').transaction(p=>{if(!p||p.id!==b.id||p.expiresAt<=now||!p.options||choice>=p.options.length||p.votes?.[who.uid]!=null)return;p.votes??={};p.votes[who.uid]=choice;return p});if(!result.committed)throw Error('Poll closed or already voted.');return reply(200,{ok:true})}
if(!owner)return reply(403,{error:'Only owners can use this panel.'});
const audit=(details)=>db.ref('novaControl/audit').push({actor:who.uid,action,at:now,...details});
if(action==='livePublish'){const message=text(b.text,500);if(!message)throw Error('Enter a message or poll question.');const options=b.kind==='poll'?String(b.options||'').split('\n').map(v=>text(v,80)).filter(Boolean):null;if(options&&(options.length<2||options.length>6))throw Error('Enter 2–6 poll options.');const live={id:randomUUID(),text:message,name:account.name||'Nova Owner',photo:account.photo||'',author:who.uid,at:now,expiresAt:now+integer(b.seconds||60,15,600)*1000,...(options?{options}:{})};await db.ref('novaControl/live').set(live);await audit({kind:b.kind});return reply(200,{ok:true})}
if(action==='liveEnd'){await db.ref('novaControl/live').remove();await audit({});return reply(200,{ok:true})}
if(action==='dashboard'){const names=['activity','days','visits','progress','siteBans','appeals','events','updates','polls','audit'];const snaps=await Promise.all(names.map(n=>db.ref('novaControl/'+n).get()));const data=Object.fromEntries(names.map((n,i)=>[n,snaps[i].val()||{}]));const [users,roles,bans,feedback]=await Promise.all(['novaAccounts','novaChatV2/roles','novaChatV2/bans','novaChatV2/feedback'].map(n=>db.ref(n).get()));return reply(200,{...data,users:Object.entries(users.val()||{}).map(([uid,u])=>({uid,name:u.name,photo:u.photo,createdAt:u.createdAt})),roles:roles.val()||{},chatBans:bans.val()||{},feedback:feedback.val()||{}})}
if(action==='logs'){const channel=text(b.channel,50);if(!['general','announcements','updates','leaks','links','welcome','community-links','owner-lounge','ai-assistance'].includes(channel))throw Error('Choose a server channel.');return reply(200,{messages:(await db.ref('novaChatV2/channels/'+channel+'/messages').orderByChild('createdAt').limitToLast(100).get()).val()||{}})}
if(action==='user'){if(!valid(b.uid)||!(await db.ref('novaAccounts/'+b.uid).get()).exists())throw Error('Choose a valid account.');const targetRole=(await db.ref('novaChatV2/roles/'+b.uid).get()).val();if(['role','chatBan','siteBan','mute'].includes(b.kind)&&targetRole==='owner')throw Error('Owner accounts are protected.');if(b.kind==='role'){if(!['member','moderator','admin'].includes(b.value))throw Error('Invalid role');await db.ref('novaChatV2/roles/'+b.uid).set(b.value)}else if(b.kind==='chatBan')await db.ref('novaChatV2/bans/'+b.uid).set(b.value?true:null);else if(b.kind==='siteBan')await db.ref('novaControl/siteBans/'+b.uid).set(b.value?{reason:text(b.reason,500)||'Account suspended by owner',at:now}:null);else if(b.kind==='mute')await db.ref('novaChatV2/mutes/'+b.uid).set(b.minutes?now+integer(b.minutes,1,10080)*60000:null);else if(b.kind==='reward'){const coins=integer(b.coins||0,0,1000000),xp=integer(b.xp||0,0,10000000),levels=integer(b.levels||0,0,1999);await db.ref('novaControl/progress/'+b.uid).transaction(p=>{p=p||initial();p.coins+=coins;p.xp=Math.min(total(2000),Math.max(p.xp+xp,total(Math.min(2000,level(p.xp)+levels))));return p})}else throw Error('Unknown user action');await audit({target:b.uid,kind:b.kind});return reply(200,{ok:true})}
if(action==='event'){const xpMultiplier=integer(b.xpMultiplier,1,50),coinMultiplier=integer(b.coinMultiplier,1,10),minutes=integer(b.minutes,1,1440);await db.ref('novaControl/events').update({xpMultiplier,coinMultiplier,until:now+minutes*60000});await audit({xpMultiplier,coinMultiplier});return reply(200,{ok:true})}
if(action==='resetChallenges'){await db.ref('novaControl/events/challengeVersion').transaction(n=>(n||0)+1);await audit({});return reply(200,{ok:true})}
if(action==='giftOnline'){const amount=integer(b.coins,1,100000),people=(await db.ref('novaControl/activity').get()).val()||{};const ids=Object.keys(people).filter(id=>now-people[id].at<60000);await Promise.all(ids.map(id=>db.ref('novaControl/progress/'+id).transaction(p=>{p=p||initial();p.coins+=amount;return p})));await audit({amount,recipients:ids.length});return reply(200,{ok:true,count:ids.length})}
if(action==='code'){const code=text(b.code,64).toUpperCase();if(!/^[A-Z0-9-]{3,64}$/.test(code))throw Error('Use 3–64 letters, numbers or hyphens.');const hash=createHash('sha256').update(code).digest('hex');const reward={coins:integer(b.coins||0,0,1000000),xp:integer(b.xp||0,0,10000000),levels:integer(b.levels||0,0,1999),multiplier:integer(b.multiplier||1,1,50),minutes:integer(b.minutes||60,1,1440),expiresAt:now+integer(b.days||30,1,365)*86400000};const r=await db.ref('novaControl/codes/'+hash).transaction(v=>v?undefined:reward);if(!r.committed)throw Error('That code already exists.');await audit({code});return reply(200,{ok:true})}
if(action==='publish'){const title=text(b.title,100),body=text(b.text);if(!title||!body)throw Error('Enter a title and text.');if(b.kind==='poll'){const options=String(b.options||'').split('\n').map(v=>text(v,100)).filter(Boolean);if(options.length<2||options.length>6)throw Error('Enter 2–6 options on separate lines.');await db.ref('novaControl/polls').push({title,text:body,options,at:now,closesAt:now+integer(b.hours||24,1,168)*3600000})}else if(b.kind==='update'){await db.ref('novaControl/updates').push({title,text:body,at:now,author:account.name})}else{await db.ref('novaChatV2/channels/announcements/messages').push({author:who.uid,text:title+'\n'+body,createdAt:now})}await audit({kind:b.kind,title});return reply(200,{ok:true})}
if(action==='reply'){if(!valid(b.uid)||!valid(b.id))throw Error('Invalid report');const message=text(b.text);if(!message)throw Error('Enter a reply.');await db.ref('novaChatV2/feedbackReplies/'+b.uid+'/'+b.id).push({author:who.uid,text:message,createdAt:now});await audit({target:b.uid});return reply(200,{ok:true})}
if(action==='appealReview'){if(!valid(b.uid))throw Error('Invalid account');const appeal=(await db.ref('novaControl/appeals/'+b.uid).get()).val();if(!appeal)throw Error('Appeal not found');if(b.approve)await db.ref(appeal.scope==='chat'?'novaChatV2/bans/'+b.uid:'novaControl/siteBans/'+b.uid).remove();await db.ref('novaControl/appeals/'+b.uid).update({status:b.approve?'approved':'declined',reviewedAt:now});await audit({target:b.uid});return reply(200,{ok:true})}
return reply(400,{error:'Unknown action.'});
}catch(e){return reply(400,{error:e.message||'Request failed.'})}};
export default createHandler();
